### ISSUE TITLE
Test common GUI workflows

### ISSUE THREAD

**Issue by scrum2a** [opensim-org/opensim-gui#1008]
We have made a bunch of changes to core and GUI since the last time we did user testing of the GUI. We should use the GUI artifact for the sets change. Download it by clicking "Details" next to "appveyor/pr" here: https://github.com/opensim-org/opensim-gui/pull/1005

- [x] tutorials (5 pts, Carmichael successfully tested Tug of War with OpenSim 4.0-2018-10-01-76939822)
- [x] tools that use ExternalLoads (5 pts)
- [x] MarkerSets (loading/saving markers from files) (5 pts Ayman)
- [x] loading RRA adjusted model crashes due to lingering `ExternalLoads` in model's `ComponentSet` (#1005) [subject01_simbody_adjusted.osim](https://github.com/opensim-org/opensim-gui/files/2426285subject01_simbody_adjusted.osim.txt)
- [x] Creating an ExternalLoads from scratch in the GUI (8 pts) (created ExternalLoads for inverse dynamics with OpenSim 4.0-2018-10-01-76939822)
- [x] Double clicking Bodies, Muscles, ... nodes throws exception (likely because sets created on the fly for GUI use are not wired correctly to underlying model (they don't own their objects either)
- [x] MarkerSet constructor from file still has wrong signature, doesn't throw if it fails.
- [x] Deleting Markers does not work because it deletes from set not component tree

**Comment by aymanhab** [comment]
Trying to load leg6dof9musc model included with build, got message about knee_angle_pat_r wrong coordinate type. Not sure if this is specific to this build or master version of model is out of date as well.

**Comment by aymanhab** [comment]
@aseth1 @jimmyDunne I'm looking into MarkerSet issues now

**Comment by aseth1** [comment]
> Trying to load leg6dof9musc model included with build, got message about knee_angle_pat_r wrong coordinate type. Not sure if this is specific to this build or master version of model is out of date as well.

leg6dof9musc from models repo loads without error, but the one distributed with the build does.  Seems specific to the build.

**Comment by aymanhab** [comment]
Saving works fine but loading saved markers fails and throws exception

**Comment by aseth1** [comment]
> Double clicking Bodies, Muscles, ... nodes throws exception (likely because sets created on the fly for GUI use are not wired correctly to underlying model (they don't own their objects either)

I would not use `ModelComponentSets` for the display purposes in the GUI. If you just need a collection use `Set`s.  `ModelComponentsSet`  is an integral part of a Model not just a bag of pointers.

**Comment by aseth1** [comment]
Previewing marker data fails. Seems to be the same failure for `BodySet`, `ForceSet`, etc... likely related to `MarkerSet`.

**Comment by aymanhab** [comment]
> I would not use `ModelComponentSets` for the display purposes in the GUI. If you just need a collection use `Set`s. `ModelComponentsSet` is an integral part of a Model not just a bag of pointers.

Thanks @aseth1 I tried calling connectToModel on these sets and that seemed to resolve the problem, what would be the downside? Remember that templates do not pass through SWIG so if we want a different typed container we'll have to instantiate it for every type or get a generic container safedowncast downstream.

**Comment by aymanhab** [comment]
@aseth1 The nodes in the Navigator are all backed exclusively by OpenSimObject so a generic Java container will not do the trick without major rework. Before this change all Sets and Groups derived from OpenSim::Object and changing this now would be quite disruptive.

**Comment by aseth1** [comment]
I see. Thanks for clarifying. I think it is OK to SWIG wrap the specific `Set` instances that you need.

**Comment by aymanhab** [comment]
Looking further into the MarkerSet issues:
- Removal from the Set uses the generic Set operation (since there's no ModelComponentSet remove), resulting in removal being broken, downstream effects of trying to load Marker with same name fails.

**Comment by aymanhab** [comment]
Trying to make PathPointSet into a plain Set to avoid extra 'pathpointset' on every pathpoint's path 😄 which leads to longer path and extra level of ../ still in progress.

**Comment by scrum2a** [comment]
@carmichaelong Muscle Tug of War

**Comment by aymanhab** [comment]
The change to PathPointSet appears to be working (since ownership was restored to previous state). Change was committed to branch.

**Comment by aymanhab** [comment]
MarkerSet issue exposes a bigger hole that's outside the scope of this issue/PR. Sets have built in methods to add/remove which are accessible as properties but the changes don't propagate to the component-tree.
The GUI uses the sets exclusively to access Markers, same for the tools so changes to component-tree is irrelevant. I strongly recommend we document the caveat rather than try to significant changes at this point.

**Comment by carmichaelong** [comment]
Finished muscle tug of war successfully. Added note in the first post that it's completed.

**Comment by jenhicks** [comment]
@jimmyDunne Do you have updates on tutorials testing? Which ones are you testing? 

@aseth1 Have you tested the tutorials? Any updates to report?

**Comment by aseth1** [comment]
I tested creating and using external Tools and ran into only one issue that I reported in #1005:

> [ ] crash due to RRA adjusted model containing ExternalLoads in ComponentSet.
> [subject01_simbody_adjusted.osim.txt](https://github.com/opensim-org/opensim-gui/files/2426285/subject01_simbody_adjusted.osim.txt)

**Comment by jimmyDunne** [comment]
I have tested all the introductory examples and they seem to be working. There are some minor issues, but they are things that have either previously existed (Choppy motion from dragging the motion scroller) or don't hinder the example (Messages that MuscleAnalysis() is unable to evaluate muscle dynamics when plotting muscle forces or generated moments) 

Tutorial SImulation-Based Design to Prevent Ankle Injuries — When opening the Control Functions tree view, the boxes are unclickable and I cannot change any values, nor even view them.

**Comment by aymanhab** [comment]
@jimmyDunne can you attach or link to the file that you have problem editing so we can try in different builds? Thanks

**Comment by jimmyDunne** [comment]
I have gone through the examples and now move back to working on the master branch. Thanks.

**Comment by scrum2a** [comment]
@aseth1  can you make separate issues?

**Comment by aymanhab** [comment]
Deletion of Markers should be fixed due to PR #1023
