### ISSUE TITLE
Allow users to change port number for Visualizer

### ISSUE THREAD

**Issue by scrum2a** [opensim-org/opensim-gui#1014]
Rather than force users to use port 8002, allow users to change the port number.

Can use a flag in opensim.conf.

**Comment by aymanhab** [comment]
@chrisdembia if we merge this on both repos, GUI first then opensim-visualizer then it should be no op to application, then we can test changes port number afterwards. Thoughts?

**Comment by chrisdembia** [comment]
Sounds good. Go ahead.

**Comment by aymanhab** [comment]
PR to opensim-gui has been merged. usage by opensim-visualizer is in PR https://github.com/opensim-org/opensim-gui/pull/1047

**Comment by scrum2a** [comment]
@chrisdembia will send out instructions for testing.

**Comment by chrisdembia** [comment]
To test:

1. Place the following in <opensim-install>/etc
[OpenSim.conf.txt](https://github.com/opensim-org/opensim-gui/files/2550468/OpenSim.conf.txt) (rename to `OpenSim.conf`).
2. Ensure the visualizer still works (load a model, make sure it shows up in the GUI).
3. Open a web browser and navigate to `http://localhost:8999/threejs/editor/index.html` and ensure the visualizer shows up here. Make sure that `http://localhost:8002/threejs/editor/index.html` does NOT show the visualizer.
4. Ensure that setting the port in `OpenSim.conf` to either 80 or 9000 causes the port to be 8002 (in a web browser), and that the GUI visualizer still works.

**Comment by chrisdembia** [comment]
I performed the steps above on Mac and everything worked as expected.

**Comment by aymanhab** [comment]
@carmichaelong Thanks for testing. Browsers are nasty in caching URLs, so if that worked once I'd assume we're good. we're not publicly supporting using the browser anyway. Can you use a different browser (Chrome, Firefox,etc...)?

**Comment by carmichaelong** [comment]
I just did a few steps that seem to agree with the caching issue:
1. Went to port 8999 again. It opened up the visualizer.
2. Hit Shift+F5 to force a full refresh. Visualizer doesn't show up.
