### ISSUE TITLE
Child/parent frame sockets cannot disambiguate between two frames with the same name

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-gui#1018]
Testing was done using arm26.osim on W10 Pro with OpenSim 4.0-2018-10-12-3071a2d5:

Now with the Joint upgrade code always adding two offset frames, the pull-down for child/parent frame for Sockets has two frames with the same name (note both `base_offset` and `r_humerus_offset` below):
![socket-same-names](https://user-images.githubusercontent.com/7455790/46970126-0f35d900-d06d-11e8-9248-2c6019c6c306.png)

There are two types of problems when an error pops up involving one of these duplicate names:

**Case 1**
1. Open arm26
2. Navigate to Joints --> offset
3. Change `PhysicalFrame:child_frame` to `r_humerus_offset` (either one)
4. Error thrown because there were multiple frames with the same name:
![image](https://user-images.githubusercontent.com/7455790/46970276-866b6d00-d06d-11e8-86e7-5c7960a48d91.png)

**Case 2**
1. Open arm26
2. Navigate to Joints --> offset
3. Change `PhysicalFrame:child_frame` to `base_offset` (either one)
4. Although there are two `PhysicalOffsetFrame`s with the name `base_offset` (the other is owned by Joint `r_shoulder`), either one will only choose the `base_offset` owned by the Joint `offset`. No error/warning is shown to the user.

@aymanhab

**Comment by aymanhab** [comment]
This should address issues #1018, #1025, leftover of #825
