### ISSUE TITLE
Parent/child frame of a joint can be edited in two locations

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-gui#1019]
![image](https://user-images.githubusercontent.com/7455790/46970603-6be5c380-d06e-11e8-9b4b-3ae4e96691ba.png)

With arm26 on W10 Pro with OpenSim 4.0-2018-10-12-3071a2d5. Both the Property and Socket stay in sync and seem to behave as expected, but having both may confuse some users.

**Comment by aymanhab** [comment]
Thanks for reporting @carmichaelong In the past we actively filtered these out to avoid duplication but the change to socket property names apparently broke that filter and caused them to slip through.
