### ISSUE TITLE
RRA produces adjusted model with ExternalLoads that crashes upon loading and RRA tool is crashing on launch

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#1021]
### Steps to reproduce
- load `subject01_simbody.osim` from OutputReference of gait2354 tutorial 
- run RRATool with provided setup file and select input motion from OutputReference
- load the adjusted model, *subject01_simbody_adjusted.osim*, generated by RRA (fails)

### Expected result
- `ExternalLoads` does not appear in the RRA adjusted model file and model loads in GUI without issue

### Actual result
- RRA adjusted model crashes due to lingering ExternalLoads in model's ComponentSet (#1005) [subject01_simbody_adjusted.osim](https://github.com/opensim-org/opensim-gui/files/2426285subject01_simbody_adjusted.osim.txt)

### Environment and GUI version
As of #1005

**Comment by aseth1** [comment]
related to #1008

**Comment by aymanhab** [comment]
@aseth1 Thanks for the fix, is there work to be done on the GUI side as well? My understanding is that the RRA adjusted model now doesn't have ExternalLoads but the GUI should still not crash if the user creates a valid model with ExternalLoads, has this been addressed? Thanks.

**Comment by aseth1** [comment]
@aymanhab I verified with OpeSnim4.0-2018-10-12-ba06a01b on Windows that the model with ExternalLoads does not crash the GUI and correctly appear in the navigator. In https://github.com/opensim-org/opensim-core/pull/2314 I fix the issue of RRA producing an adjusted model containing the `ExternalLoads` added by the Tool.

**Comment by aymanhab** [comment]
Thanks @aseth1 so I think this can be moved to need verifying

**Comment by nickbianco** [comment]
Testing this on Windows 10, [AppVeyor build 1.0.1899](https://ci.appveyor.com/project/opensim-org/opensim-gui/builds/19593779/artifacts). 

After loading the model, clicking `Reduce Residuals...` in the drop down crashes the GUI. This is true for any model that I try in the Models folder, not just `subject01_simbody.osim`.

**Comment by jenhicks** [comment]
@aymanhab The same happens for me. CMC + SO + Forward + Analyze also crash when trying to launch. Scale, IK, ID are ok. 

OpenSim 4.0-2018-10-17-f9ad640

**Comment by aymanhab** [comment]
Thanks for reporting @jenhicks 
The stack trace points to ExternalLoads_getExternalLoadsModelKinematicsFileName()
Any clue why that would crash now @aseth1 based on the recent updates to ExternalLoads? 
I'll build a debuggable environment to get to the bottom of it anyway.

**Comment by aymanhab** [comment]
@jenhicks I got to the bottom of this.

The issue boils down to the following: in the past AbstractTool (used as base class for all tools that crash now but not ID) used to have a member  _externalLoads that the GUI used to query to populate the form/dialog. This member was removed in https://github.com/opensim-org/opensim-core/pull/2285 and replaced with a reference initialized to nullptr (DynamicsTool still has the member variable so it doesn't crash). 

I'm puzzled that this didn't crash and burn during testing then, I'd suspect it's a bug/issue with the ci build system or mixing libraries since this should always crash.

**Comment by aymanhab** [comment]
@chrisdembia I changed the estimate based on what I know now since testing the variety of tools that use ExternalLoads is a signficant undertaking, that is after I investigate and find a fix.

**Comment by aseth1** [comment]
> I'm puzzled that this didn't crash and burn during testing then, I'd suspect it's a bug/issue with the ci build system or mixing libraries since this should always crash.

There is no use of the pointer in the API or test cases. If it is vital for GUI operation there should be uses cases in testOpenSimContext or in the java related scripts so I know to update or to let you know.

**Comment by aymanhab** [comment]
@aseth1 I was referring to the tests we made on the integrated GUI and API build with the change to sets that didn't show the issue, you actually tested that yourself.

On further investigation, the change in PR #2285 is not what's causing the crash but rather the change in PR #2315 which absolutely has no business changing tools based on the PR title (Fix bug in inducedAccelerationSolver). I'm testing rolling back this change to the Tools. If that works I will open a PR and we can discuss.

**Comment by aseth1** [comment]
The change was made in https://github.com/opensim-org/opensim-core/pull/2314 and was just merged into #2315.

**Comment by aseth1** [comment]
@aymanhab thanks for explaining the reasoning for having a live data member instead of a reference. I did not know that it was there as scratch space to support building ExternalLoads in the GUI. Let's restore the data member for that purpose, and also leave the reference pointer so that I can keep track of the ExternalLoads that gets added to the model, so it can be removed so that this issue does not return.

**Comment by aymanhab** [comment]
Rolling back the change in  https://github.com/opensim-org/opensim-core/pull/2314 allows the tools to open but restores the crash at the end of RRA as expected, also exposes another problem with external loads described in https://github.com/opensim-org/opensim-core/issues/2324
Not sure this is the only other side effect of refactoring ExternalLoads, still exploring/testing

**Comment by aymanhab** [comment]
Verified the dialogs open and the tools run as expected (except for editing old ExternalLoads files #2324). Spot check results look ok.

**Comment by chrisdembia** [comment]
The workflow above now causes the following error:

```
Exception:
  AbstractTool: could not find external loads kinematics file
  'subject01_walk1_ik.mot'.
```

Mac 4.0-2018-10-31-f21f17f

**Comment by chrisdembia** [comment]
Nevermind; I just needed to run IK first.

**Comment by chrisdembia** [comment]
Verified on Mac.
