### ISSUE TITLE
Drop-down menu for a Marker's parent_frame is populated with the current Model's Frames rather than its own Frames

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-gui#1026]
1. Open leg39
2. Open arm26
3. Navigate to leg39 -> R.ASIS
4. Open drop-down menu for Socket --> `PhysicalFrame:parent_frame` and note that the `Frame`s for arm26 are shown rather than leg39
![image](https://user-images.githubusercontent.com/7455790/47052828-f3aafb00-d15e-11e8-878f-04a74d4dfedd.png)

W10 Pro OpenSim 4.0-2018-10-16-6011b19b

**Comment by aymanhab** [comment]
This actually occurs in 3.3 as well, still a bad bug 🔥
