### ISSUE TITLE
Write abstract to advertise webinar

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#1028]
Due October 30

**Comment by jenhicks** [comment]
I drafted an abstract here:
https://docs.google.com/document/d/1ET_qzyjsO1BK_7YT_4nTdU_cqyLTx3yz398WA1MKKBM/edit#

We should finalize by Tuesday (Oct 30) morning to allow us to start advertising the webinar.

@aymanhab @aseth1 @tkuchida (and anyone else who would like to provide feedback)

**Comment by jenhicks** [comment]
Thanks for the helpful suggestions @tkuchida .

**Comment by jenhicks** [comment]
Thoughts on a title?

**Comment by jenhicks** [comment]
One idea: Jumping into OpenSim 4.0

**Comment by tkuchida** [comment]
"Jumping (and swinging)…" to include the pendulum example? 🐸 🐒

**Comment by aymanhab** [comment]
Swinging (as in trying to hit) may not give the right connotation ;)

**Comment by tkuchida** [comment]
It would be swinging *into* (https://idioms.thefreedictionary.com/swing+into+action).

**Comment by scrum2a** [comment]
@aseth1 will prepare a model building demo for tomorrow (may present on his own laptop).
title: Jumping into OpenSim 4.0

@aymanhab will do the visualizer demo on Jen's machine.
