### ISSUE TITLE
Visualizer demo: develop and test workflow

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#1030]

**Comment by aymanhab** [comment]
@jenhicks Are the models/data files available on dropbox or somewhere we can start trying things out? Thanks

**Comment by jenhicks** [comment]
The latest version of the files are here (from World Congress):
Dropbox/OpenSim Documentation/conference-exhibits/WCB2018

I will probably make some tweaks for the webinar, but those are a good starting point.

**Comment by aymanhab** [comment]
@jenhicks is the most recent version of the demo files on Dropbox? Thanks

**Comment by jenhicks** [comment]
Sorry for the delayed response ... yes, latest version should be on dropbox. I will make sure everything is synced as soon as I get into the office (about 15 minutes).
