### ISSUE TITLE
Update Matlab scripting documentation for osimList2MatlabCell()

### ISSUE THREAD

**Issue by scrum2a** [opensim-org/opensim-gui#1034]

**Comment by jimmyDunne** [comment]
@carmichaelong @chrisdembia, if you can review and edit [my edits](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Scripting+with+Matlab#ScriptingwithMatlab-Usingamodel's%22Lists%22throughiterators)?

**Comment by jimmyDunne** [comment]
Yep, I am a dumb-dumb that forgot already that we changed it. Thanks!!

I have updated accordingly, sorry for the time waste.

**Comment by carmichaelong** [comment]
No worries at all. Thanks for updating. I also added a mention of the file into the Utilities table above to highlight it more.
