### ISSUE TITLE
Test fallout from ExternalLoads

### ISSUE THREAD

**Issue by scrum2a** [opensim-org/opensim-gui#1035]
- Read in 3.3 version and 4.0 version.
- Create ExternalLoads from scratch.
- Test with and without data_source that exist.
- With and without the kinematics_for_external_loads.
- Use tools.
  - InverseDynamics.
  - CMC, RRA, Analyze (Static Optimization).
- Filtering for kinematics_for_external_loads.

**Comment by aymanhab** [comment]
As of now the jumper's static optimization setup fails dereferencing the null forceData because getDocument() returns false. Need more investigation. (@chrisdembia that's the reason behind the so crash)

**Comment by chrisdembia** [comment]
RRA runs fine if I remove the `external_loads_model_kinematics_file` option, even if a filtering frequency is still specified.

**BUG**: The GUI crashes if the `datafile` field is empty. I'm investigating a fix.

**Comment by chrisdembia** [comment]
I tested the following GUI scripts and they ran without error:

- alterTendonSlackLength
- editProperties
- plotMuscleFiberLengthAgainstFile
- runMultipleIKTrials
- runScaling

I ran the following and it had an error (not a big deal):

- [ ] plotMuscleMomentArmAgainstMotion
<img width="981" alt="image" src="https://user-images.githubusercontent.com/846001/47829687-e50b3900-dd45-11e8-8867-c192f34bcd20.png">


I did not run:

- [ ] tetsShowModelSummary
- [ ] strengthenModel
- [ ] runTutorialOne
- [ ] runTutorialTwo
- [ ] runTutorialThree
- [ ] makeUlnaHeavy
- [ ] createControlsFromStorage

**Comment by chrisdembia** [comment]
I tested creating an ExternalLoads from scratch in the GUI and had no issue.

**Comment by jimmyDunne** [comment]
runTuTorialThree crashes the GUI out entirely. Am investigating now....

**Comment by aymanhab** [comment]
Thanks @jimmyDunne since crashes can only happen on core, I'm guessing it's the same issue that @chrisdembia fixed already in PR https://github.com/opensim-org/opensim-core/pull/2350
Will test after merging.

**Comment by aymanhab** [comment]
@jimmyDunne @aseth1 @chrisdembia The fundamental problem, looking at this script is that it does initSystem on the the model loaded in the GUI. This creates a new State object that backs the current model and makes the state that the GUI relies on for display corrupt/dissociated. All problems are  downstream effects, that's why in all other cases we clone the model first to begin.

**Comment by aymanhab** [comment]
@chrisdembia Did you update the setup file not to include a model file?

**Comment by chrisdembia** [comment]
@aymanhab no

**Comment by aymanhab** [comment]
Thanks, would be good to have @aseth1 do that in his environment so there are no confounding factors.
