### ISSUE TITLE
Update ModelBuilder.py for sets being components

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#1036]
This line in ModelBuilder.py should be updated so that the example still works, given that sets are now components:

https://github.com/opensim-org/opensim-gui/blob/f9ad640d243aacdf825a8c2345fb7fa5c150ce48/Gui/opensim/Scripts/ModelBuilder.py#L32

**Comment by aymanhab** [comment]
@aseth1 are you modifying the script while making the pendulum model? If not I can take this over. Please let me know.

**Comment by aseth1** [comment]
Yes, I'v been modifying it.
