### ISSUE TITLE
Arm26 CMC example: missing files

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-gui#1050]
### Steps to reproduce
Ran the [CMC example on confluence](https://simtk-confluence.stanford.edu/display/OpenSim/Example+-+Computed+Muscle+Control
) with the arm26 model. 

### Expected result
Normal coordinate tracking behavior.  

#### Weird tracking result
In the second main section labeled "Changing the Desired Kinematics", the tutorial asks you to modify the inverse kinematics results by replacing the shoulder elevation column with the values from the elbow flexion column. Upon doing this, towards the end of the time window this happens: 
![image](https://user-images.githubusercontent.com/23224439/48036061-95e54f80-e11b-11e8-8409-86404fe0bb21.png)

I tried setting the shoulder elevation to half the elbow flexion values and that worked fine. But the original instructions should also work since shoulder elevation can range [-90, 180] degrees while elbow flexion is restricted to [0, 130]. 

#### Missing control constraints file.
In addition to the tracking error, the sample control constraints file that the confluence example references is missing from the Arm26 CMC subdirectory. 

### Environment and GUI version
Windows 10, Artifact 2018-11-02-e6f8d11e, AppVeyor build 1.0.1942

**Comment by aseth1** [comment]
@nickbianco can you run the example in 3.3 and verify that the same behavior is occurring. I saw similar behavior just running forward in 4.0 the muscle points seem default to origin when the state is NaN and that is a bug! But, it was also returning NaN in 3.3 so the result may not be a bug although not a great example to be putting out there.

**Comment by nickbianco** [comment]
@aseth1 just tested on 3.3 and I get a similar error. Towards the end of the simulation the disappears, and the whole model disappears if you try to rotate it.

**Comment by aymanhab** [comment]
Thanks Nick, these are different ways to handle NaNs. In 3.3 we were
allowed to set garbage transforms causing model to disappear, now we're
limited to sensible rigid body transforms for bodies but path points are
computed as difference between 2 Nans which end up as 0 🤗 the fix should
be upstream rather than handling garbage and NaNs in state but that's not
on the table for 4.0.

**Comment by nickbianco** [comment]
Alright. For now we could remove the section from the confluence example where the user edits the kinematics by hand.

**Comment by jenhicks** [comment]
Make sure the issue of drawing paths with NaNs is still open

**Comment by aymanhab** [comment]
File is also missing in 3.3 distribution

**Comment by aymanhab** [comment]
https://github.com/opensim-org/opensim-gui/issues/762

**Comment by chrisdembia** [comment]
Should we move this issue out of the sprint then?

**Comment by nickbianco** [comment]
The actuator constraints are missing in 3.3, but it would be nice to include in the 4.0 distribution. The confluence tutorial would benefit from having the actuator constraints section.

**Comment by nickbianco** [comment]
I created the control constraints file if someone with a GUI environment wants to create a PR:
[arm26_ControlConstraints.txt](https://github.com/opensim-org/opensim-gui/files/2558762/arm26_ControlConstraints.txt)

**Comment by nickbianco** [comment]
@jimmyDunne do yo thang

**Comment by chrisdembia** [comment]
This is in progress only because we need to update the opensim-models submodule in opensim-gui.

**Comment by carmichaelong** [comment]
Looks like the file is correctly placed into <Resources>/Models/Arm26/ComputedMuscleControl, and the example can be done.

It also looks like it is not in the reference folder (<Resources>/Models/Arm26/OutputReference/ComputedMuscleControl), but all the other files for setup are in there. Should this file also be added to the corresponding CMC OutputReference folder?

**Comment by chrisdembia** [comment]
> Should this file also be added to the corresponding CMC OutputReference folder?

Interesting... I don't think we should have a duplicate in the repo but maybe CMake should put a copy in OutputReference.

**Comment by carmichaelong** [comment]
Moving this to verified on windows and started a new issue with things to do beyond 4.0.
