### ISSUE TITLE
Plotting can change position of the model

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#1052]
### Steps to reproduce
Load the wrist model
Plot the flexion moment arm as a function of flexion for the pre/post ECU
Close the plot and change the elbow flexion angle.

### Expected result
Wrist flexion does not change

### Actual result
Wrist flexes

(include screen grabs where appropriate)

### Environment and GUI version
Mac OpenSim 4.0-2018-11-06-f854814

**Comment by carmichaelong** [comment]
Replicated issue with arm26 and then tested that this was fixed in OpenSim 4.0-2018-11-08-ca20f56c.

@chrisdembia you mentioned this before, should there be another issue made for this (for after 4.0)?

> Another related issue: if I have loaded a motion with my model and then I put the model in some random pose and then open any of the tools or the plotter window, the model goes to the initial pose in the motion.

**Comment by chrisdembia** [comment]
Done https://github.com/opensim-org/opensim-gui/issues/1077
