### ISSUE TITLE
External Loads file needs full path to file otherwise exception

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#1066]
### Steps to reproduce
Use an External loads setup file that has a relative path to a force file where the path requires traversing up in the directory structure

### Expected result
Tool runs

### Actual result
Tool reports that the force file cannot be found 

User Report-
> figured out the issue - in the path referencing the external loads motion file, navigating up a folder and back down to a different folder doesn't work - fixed when input a direct path. CMC is unable to read ExternalLoads data file 'subject01_walk_grf.mot' - the file is subject01_walk_grf.xml - in the messages, it says it couldn't load the .mot file?

### Environment and GUI version
MAC and Windows

**Comment by aymanhab** [comment]
@jimmyDunne Find out what version the user is trying since this has changed significantly since the last publicly posted beta
