### ISSUE TITLE
Geometry is incorrectly displayed after using Scale Tool when using a model that has its own Geometry folder

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-gui#1078]

**Comment by carmichaelong** [comment]
@chrisdembia @aymanhab @jimmyDunne 

Although the files in the email are not compatible with 3.3, I was able to reproduce with the files from the Rajagopal model SimTK page:
![image](https://user-images.githubusercontent.com/7455790/48288653-bbc36a80-e421-11e8-8294-442b4554adc8.png)

Note that in order to reproduce, I deleted the `r_tibia.vtp` file from the OpenSim 3.3 Geometry folder (apparently it was available in this one).

Another thing to note here is that missing Geometry may only be one problem here. If a user has their own custom geometry with the same name, then when the model loads, they won't know if their custom Geometry is used or the one in the distribution. This could lead to someone incorrectly adjusting their model, for instance, if they see "incorrect" muscle paths (e.g., muscles crossing through bones or not connecting to bones) simply due to different geometry being used.

**Comment by carmichaelong** [comment]
In 4.0 using the files from the email, I got a similar effect as 3.3. Maybe I can't reproduce the same exact issue but a similar one?
![image](https://user-images.githubusercontent.com/7455790/48289264-b1a26b80-e423-11e8-85af-05a3f2c9249e.png)

**Comment by chrisdembia** [comment]
@rwj1 how do these fibulas compare to those in the output of your scaling?

**Comment by aymanhab** [comment]
At some point I think @jimmyDunne renamed bones since differnet models had different convention e.g. boneWhatever.vtp was meant as boneWhatever_r.vtp

**Comment by carmichaelong** [comment]
Since clearly 4.0 could also find my 3.3 folder, I deleted 3.3 and tried it again in 4.0 and get something closer to what was reported:
![image](https://user-images.githubusercontent.com/7455790/48289451-68065080-e424-11e8-8bff-f25c477be63b.png)

Saving out the scaled model and loading it again yields some bones back:
![image](https://user-images.githubusercontent.com/7455790/48289537-b3b8fa00-e424-11e8-814b-ae898eed8dd9.png)

Perhaps this means that the local Geometry folder is only used on loading a model from file and not when a Tool outputs a new model?

**Comment by aymanhab** [comment]
Yes, @carmichaelong that was the conjecture. If you save to the same folder as the model you started from then this whole issue goes away on reloading.

**Comment by chrisdembia** [comment]
I just chatted with @rwj1 and Lauren about this. Their issue is not that geometry doesn't show up; they have addressed this by changing the Geometry Path. The issue is that the fibula seems to end up in the incorrect location after scaling. The marker on the malleolus is no longer lined up with the fibula anymore.

**Comment by chrisdembia** [comment]
Here's what the fibula looks like from the attached model.

[scaled_model.osim.zip](https://github.com/opensim-org/opensim-gui/files/2567806/scaled_model.osim.zip)


<img width="1521" alt="image" src="https://user-images.githubusercontent.com/846001/48293592-c5a29900-e434-11e8-8ff4-49affccc47e9.png">

The malleolus marker seems to be in the correct place.

**Comment by chrisdembia** [comment]
The attached model exhibits the issue better.

<img width="325" alt="image" src="https://user-images.githubusercontent.com/846001/48294308-50d15e00-e438-11e8-95c5-772b6d66c4ea.png">
