### ISSUE TITLE
Built-in Geometry of Joints are not drawn correctly in 3js viewer

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#109]
Simple example of an EllipsoidJoint. In vtk (in 4.0) visualizes like this:

![ellipsoid_vtk](https://cloud.githubusercontent.com/assets/6494122/23643938/b097188c-02b9-11e7-8275-6aee8f123c8d.png).

But in the 3js view it looks like this:
![ellipsoid_3js](https://cloud.githubusercontent.com/assets/6494122/23643967/c2eee604-02b9-11e7-80d1-3af41fddcd68.jpg)

**Comment by aymanhab** [comment]
@jenhicks I tried to locate the model on Dropbox but can't find it, can you send me a link or tell me how to get it otherwise? Thanks

**Comment by aseth1** [comment]
@aymanhab you have access [here](https://www.dropbox.com/home/OpenSim%20Beta%20Testing%20Files/GUIAxesVisualization) to the test files.

**Comment by aseth1** [comment]
[Here](https://www.dropbox.com/home/OpenSim%20Beta%20Testing%20Files/GUIAxesVisualization) is also a link to download as a zip

**Comment by jenhicks** [comment]
The model looks ellipsoidal to me, but the shading is off. 
![ellipsoidviz](https://user-images.githubusercontent.com/4510959/37176699-fc2c5968-22d1-11e8-837a-7f9d44218590.jpg)

@aymanhab Is this a separate issue tracked somewhere?

**Comment by aymanhab** [comment]
This looks like two coincident pieces of geometry. VTK used to handle that a little better. There's issue #352 related to wrap geometry but I don't know if this's a wrap object or any other geometry
