### ISSUE TITLE
Webinar Follow-up

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#1092]
- [x] Prepare response to questions and post
- [x] Compile a set of follow-up links
- [x] Post pdf of slides

**Comment by jenhicks** [comment]
I think the Q and A is in pretty good shape now. If someone could start to compile a list of links we may want to send out (the 4.0 paper, where to download, etc.), that would be helpful. (Jackson is sick, so I'll probably be out for most of the rest of today)

**Comment by jenhicks** [comment]
@tkuchida @chrisdembia @aymanhab @jimmyDunne Below is a list of links. Let me know if anything is missing. Thanks!

Watch a recording of the webinar: JOY/JACQUELINE TO ADD

Download the slides from the webinar: JOY/JACQUELINE TO ADD

Review the Q&A from the webinar: JOY/JACQUELINE TO ADD

Download the OpenSim 4.0 software: https://simtk.org/frs/?group_id=91

Learn more about new features and how to upgrade: https://simtk-confluence.stanford.edu:8443/pages/viewpage.action?pageId=28409888

Read about OpenSim 4.0 in our PLOS Computational Biology Paper: https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006223

Access our documentation, including examples and tutorials:
https://simtk-confluence.stanford.edu:8443/display/OpenSim/OpenSim+Documentation

Review and ask questions on our user's forum: https://simtk.org/plugins/phpBB/indexPhpbb.php?f=91

**Comment by jimmyDunne** [comment]
Perhaps the forum announcement thread where I am making daily updates; https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=9760&p=0&start=0&view=&sid=ae0d9c9d804de7bace0dcd335beaf824

**Comment by jenhicks** [comment]
I sent everything over to Joy and Jackie. Let me know if there is any final feedback before we send out the email on Wednesday morning.

**Comment by tkuchida** [comment]
@jenhicks I made a couple minor edits to the Google Doc which can be ignored.
