### ISSUE TITLE
Change to capitalization of filename must be propagated

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#1096]
leg39.osim -> Leg39.osim (PR https://github.com/opensim-org/opensim-models/pull/111)
Must be changed here as well: https://github.com/opensim-org/opensim-gui/blob/3354c2472ce00d7883b86b7c2570f36145cda41a/Gui/opensim/Scripts/runMultipleIKTrials.py#L77
and possibly elsewhere.

**Comment by jenhicks** [comment]
I'm still not 100% following why the lowercase filename created an issue. Do the other lowercase model filenames also create an issue? I'd like to understand the issue better before we make any additional changes.

**Comment by chrisdembia** [comment]
Linux is case-sensitive, while Mac and Windows are case-insensitive (but case-preserving), so the issue only occurs on Linux.

**Comment by jenhicks** [comment]
I'd lean towards reverting until we have more details about what's happening. @jimmyDunne do you have more details?

**Comment by tkuchida** [comment]
https://github.com/opensim-org/opensim-models/pull/112 was reverted; propagating that change here by closing this Issue.
