### ISSUE TITLE
Transforming marker previewed marker data (.trc) results in invalid TRC format file

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#1102]
### Steps to reproduce
- Use Preview Experimental Data... to view marker data in a .trc file.
- use the Transform option (right click on previewed trc file in navigator) to rotate data -90degs about X (now Y is up).
- save the data to a new transformed file
- attempt to perform IK with the new transformed .trc file

### Expected result
- IK runs normally with new .trc file

### Actual result
- invalid delimiters (i.e. spaces) are inserted in column labels:
![image](https://user-images.githubusercontent.com/6494122/49761971-41cf0d00-fc7d-11e8-8672-a602738ed14e.png)

- results in error during IK:
`InverseKinematicsTool Failed: Error reading column Labels in file 'F:\Users\aseth\Development\OpenSimIMU\S03_Mocap\transformed_LHJC_Final.trc'. Unexpected number of column labels. Expected = 47. Recieved = 45.
	Thrown at trcfileadapter.cpp:125 in extendRead().`

### Environment and GUI version
- OpenSim 4.0 Windows

GUI should not have another mechanism for reading and writing TRC files. All reading and writing of data files should go through FileAdapters.

**Comment by jimmyDunne** [comment]
@aymanhab. [Seen in the wild](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=10755&p=0&start=0&view=&sid=ea5bcebac660287e646017fd77f41d05)

**Comment by jimmyDunne** [comment]
Test #1113

**Comment by aymanhab** [comment]
I believe this has been fixed already, just need to verify.

**Comment by jenhicks** [comment]
This is fixed for me.
