### ISSUE TITLE
GUI is adding offset to experimental data  (it shouldn't be)

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#1105]
### Steps to reproduce
(1) Preview experimental marker data in GUI. 
(2) Preview corresponding force data in GUi. 
(3) Sync motions. 

### Expected result
Marker and force data are displayed in the exact, global, location that they are defined in the experimental data files.

![image](https://user-images.githubusercontent.com/5296507/53247177-b57b9600-3680-11e9-8523-835ca9d27294.png)

### Actual result
The GUI adds an offset to the view frame of the force data and so it appears as if there is a real offset between the marker and force data. 

![image](https://user-images.githubusercontent.com/5296507/53247153-a399f300-3680-11e9-88e7-d96c83c15414.png)

I would guess that this behavior occurs because the the Experimental Data Previewer is sharing some of the same functions as the Model Opener, but this particular behavior is incorrect. Experimental data should never have offsets automatically injected into the visualization since this makes it difficult for the user to know what is exactly wrong. Case in point is this [forum post](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=10075&p=0&start=0&view=&sid=f5699923b82824de2e6dbe358e0e8ae6). 

### Environment and GUI version
Mac and Windows

**Comment by jenhicks** [comment]
This has come up a couple times on the forum (two users).

**Comment by jimmyDunne** [comment]
Fixed in #1118
