### ISSUE TITLE
Marker shading is inconsistent with the shading of all other geometry in the 3D view

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#1107]
### Steps to reproduce
Load any model with markers and look at it.

### Expected result
Spheres are shaded with light source in common with all other objects.

### Actual result
Spheres appear to be magically illuminated from below (that is from the floor up).

![image](https://user-images.githubusercontent.com/6494122/53605727-4a90fa00-3b6d-11e9-824a-a9d51459dad6.png)

### Environment and GUI version
OpenSim 4.0 on Mac and Windows

**Comment by tkuchida** [comment]
There was an old issue about this. IIRC, the issue was that the back faces were being drawn rather than the front faces. It looks like an open hemisphere is being drawn, and the light from above the model is reflecting off the inside of the hollow bottom.
