### ISSUE TITLE
Defend against users making changes after using getCurrentModel() (without cloning)

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-gui#1109]
### Steps to reproduce
1. Load gait2354 (or any model with `femur_r`)
2. Run GUI script `ModelBuildingFunctions.py`
3. Run the following short script:
```
model = getCurrentModel()
ball = addBodyToModel(model, 'ball')
sphere = modeling.Sphere(0.2)
attachGeometryWithOffset(ball,modeling.Sphere(0.2))
j1_in_ball = addOffsetToFrame(ball, 'j1_in_ball')
femur_r_body= model.getComponent('/bodyset/femur_r')
j1_in_femur_r= addOffsetToFrame(femur_r_body, 'j1_in_femur_r')
j1 = connectBodyWithJoint(model, j1_in_femur_r, j1_in_ball, 'j1', 'PinJoint')
j1.getCoordinate().setName('theta1')
state = model.initSystem()
loadModel(model)
```

### Expected result
Two models are seen in the GUI, one of the two models is denoted as the Current Model.

### Actual result
GUI does not show the new model. Also, both models in the Navigator pane are the "Current Model".

However, you can right-click and "Save As" on the new model, and upon closing all models and loading the new model from file, the model shows as expected.

### Environment and GUI version
Windows 10, OpenSim 4.0

**Comment by aymanhab** [comment]
@carmichaelong The main problem here is that you didn't clone the model first, which means the model with and without the additional body have the same handle and thus are both current 🚑 🚒

**Comment by carmichaelong** [comment]
Ah, that makes sense. Adding `.clone()` on the end of the first line works. Should we be defending against this type of user input?

**Comment by aymanhab** [comment]
@carmichaelong you know where the "bodies" are buried. 
Yes we should defend against it. I can make getCurrentModel() in GUI return a subclass of Model where all non const methods throw exceptions but this deviates the GUI from API documentation. I'm open to ideas though..
