### ISSUE TITLE
Muscle wrapping visualization is incorrect when muscle loses contact with WrapCylinder

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#1111]
### Steps to reproduce
- open Rajagopal2015 model
- change knee_angle_r to 30 degrees

### Expected result
Gastroc path looks reasonable.

### Actual result
![](https://user-images.githubusercontent.com/4203505/57107787-f5a16980-6cfe-11e9-984e-f3ce0921e1c2.png)

Path seems to be computed correctly:
![](https://user-images.githubusercontent.com/4203505/57107802-0651df80-6cff-11e9-96d2-fd8f2831ee3b.png)

### Environment and GUI version
Public release of 4.0

**Comment by jenhicks** [comment]
@aymanhab will investigate, given recent discussion on forum.

**Comment by aymanhab** [comment]
I'm working on a fix now,

**Comment by aymanhab** [comment]
Let me clarify the scope of the issue:
- This has no effect whatsoever on computation or correctness of results, pure visualization issue.
- All models display correctly on loading regardless of wrapping. If wrong display happens save the model in this bad configuration and load it and it will be fine.
- Only models/muscles that could be affected are those with multiple wrap objects when an object switches from engaged to disengaged while some other objects are engaged either during a motion playback or while moving a coordinate slider.

**Comment by jenhicks** [comment]
@jimmyDunne Can you test this one?

**Comment by jimmyDunne** [comment]
Placing the model in the affected pose, saving, and reloading;

![image](https://user-images.githubusercontent.com/5296507/66132578-46c1cc00-e5c3-11e9-84f0-0651e4ace733.png)

**Comment by aymanhab** [comment]
The behavior you described is exactly how it was before the fix, that's not
what I see using the branch with the PR that has not been merged into
master yet. Can you report what environment did you use? Thank you

**Comment by jimmyDunne** [comment]
I am on Mac. I used the OpenSim-fix_visualization_multiple_wraps artifact
