### ISSUE TITLE
TRC file written by GUI cannot be read by TRCFileAdapter

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#1112]
### Steps to reproduce
- File > Preview Experimental Data…
- Open walking2_markers.trc (extracted from [walking2.c3d](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Tests/shared/walking2.c3d)) and attached in this .zip file: [walking2_markers.zip](https://github.com/opensim-org/opensim-gui/files/3226010/walking2_markers.zip)
- In Navigator, expand "ExperimentalData_0", right-click on "walking2_markers.trc", and select "Transform"
- Rotate by 90 degrees about X (arbitrary) and save as "transformed_walking2_markers.trc"
- Preview new "transformed_walking2_markers.trc" file in GUI --> works
- Attempt to read file in Python using TRCFileAdapter:
```
import opensim as osim
markers = osim.TRCFileAdapter.read('transformed_walking2_markers.trc')
```

### Expected result
File can be read in the GUI and in Python

### Actual result
Either both should work or both should fail. The GUI can read the file, which suggests to the user that the file has been correctly written. However, the file cannot be read from Python because the whitespace in the header is incorrect. Error message:
<pre>
RuntimeError: std::exception in 'OpenSim::TimeSeriesTableVec3 OpenSim::TRCFileAdapter::read(std::string const &)': Error reading column Labels in file 'transformed_walking2_markers.trc'. Unexpected number of column labels. Expected = 46. Recieved = 44.
	Thrown at trcfileadapter.cpp:125 in extendRead().
</pre>

### Environment and GUI version
Public release of 4.0

**Comment by tkuchida** [comment]
@aymanhab See [L409 and L410 here](https://github.com/opensim-org/opensim-gui/blob/ca20f56c3e3216a857b22a111e67a5390f8f9510/Gui/opensim/view/src/org/opensim/view/experimentaldata/AnnotatedMotion.java#L409): spaces should be `\t` as elsewhere.

**Comment by aymanhab** [comment]
Perfect, now that you did the hard part and found it @tkuchida do you mind submitting a PR ;) or I can do it later. Thanks 👍

**Comment by tkuchida** [comment]
Unfortunately, I've never been able to build the GUI 😢 so I have no way of testing.

**Comment by aymanhab** [comment]
A build/artifact inluding the fix successfully opened the trc file from the scripting shell.

**Comment by aymanhab** [comment]
If somebody can verify fix in artifact that would be great. Use scripting shell easier than python environment

**Comment by jimmyDunne** [comment]
I downloaded and installed the latest GUI artifact on a Windows VM, performed the transform in the GUI, and use Python to read the transformed trc. It seemed to work without issue-- no exceptions or oddities. I think we should still test again when before doing the next minor release.

**Comment by aymanhab** [comment]
Any reason this is not closed @jimmyDunne
