### ISSUE TITLE
Geometry Path has default appended upon launch despite what user had set

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#1115]
Likely related to #745 

### Steps to reproduce
1. launch OpenSim4.0 GUI and  set `Paths: Geometry Search Path` to something, say <My_Prefered_Path>
2. Open a model that uses geometry in said path. All good.
3. Quit and relaunch OpenSim4.0 GUI and reload your model
4. Model looks janky because it is reading default geometry that it finds in the default path for Geometry 

### Expected result
![image](https://user-images.githubusercontent.com/6494122/59139787-6a914000-894a-11e9-8b2d-cc6dff0aeda3.png)

### Actual result
Default OpenSim Geometry is magically appended and takes precedence over the path I set last time GUI was running and all was well and now my model looks awful.

![image](https://user-images.githubusercontent.com/6494122/59139837-f7d49480-894a-11e9-903b-b5afdf1aa103.png)

### Environment and GUI version
OpenSim 4.0 Win64

**Comment by aymanhab** [comment]
Good find @aseth1 👍

**Comment by aseth1** [comment]
closed by #1119?

**Comment by aymanhab** [comment]
Thanks @aseth1 and @jimmyDunne
