### ISSUE TITLE
Disabled muscles show in red when playing back SO results

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#1123]
### Steps to reproduce
Load Arm26 and static optimization default setup, run analysis, disabled muscles show in red

### Expected result
disabled muscles show a different color outside the blue--to-red spectrum
### Actual result

(include screen grabs where appropriate)

### Environment and GUI version
4.0

**Comment by aymanhab** [comment]
Some confounding factors worth discussion before a solution is implemented:
- GUI has 2 modes: mode 1 does not color based on state at all as in load/edit, mode 2 muscle color is based on state as in motion playback.
- SO uses a mechanism that overrides the color from state to color by activation from a file/storage (due to the fact that SO produces no consistent state to use).

**Comment by tkuchida** [comment]
@aymanhab Perhaps "user stories" would be helpful here. There are countably many scenarios in which muscles are drawn, and presumably one could determine what the user would want to see in each case. IIRC there are several GUI "modes" (model building vs. simulating vs. playback of results). Perhaps these modes should be communicated to the user (e.g., by changing the color/look of the interface)?

**Comment by aymanhab** [comment]
@tkuchida Good point. I thought about that during 4.0 but decided against it because there were only 2 modes (simulation and playback are intended to produce the same visuals). When we introduce model building it could help make it clear when a model is under-construction vs. ready vs. simulating at that point, but I'd like to hear your rationale for doing it now as well.

**Comment by tkuchida** [comment]
> I'd like to hear your rationale for doing it now as well

![](https://user-images.githubusercontent.com/4203505/60750677-442ae880-9f7a-11e9-85c0-aafe71be27a4.png)

Perhaps the GUI should be communicating some sort of "metadata" (mode/condition/state) to the user. For example, how would a user visually distinguish between an IK solution (all muscles always red) vs. a dynamic simulation with maximally activated muscles (all muscles always red)?

**Comment by aymanhab** [comment]
@tkuchida I agree we should communicate more info to the user, the trick is to do it without overwhelming the user with unnecessary or repeated details. ColorBy can be displayed in the status bar or messages window when it changes, but some are implicit as when you run FD or playback. IK is a bit more difficult since we use formStateStorage which treats all motions the same regardless of contents.

**Comment by aymanhab** [comment]
I made a change so that if we color by activation from file (as in SO) then muscles that are not found (e.g. disabled) are colored Yellow (a color outside the spectrum of blue-red). Some hanging issues to discuss though:

1. FD doesn't use this pathway so we can't tell if muscles were activated minimally or disabled.
2. Many examples produce arbitrarily large (i.e. small :smiley) negative activation (e.g. tug-of-war)!



-

**Comment by jenhicks** [comment]
@aymanhab Will make muscle gray instead of yellow

**Comment by aymanhab** [comment]
Done, and tested by @jimmyDunne and myself, Changelog updated.
