### ISSUE TITLE
Deal with Nans in force (.mot) files when visualizing

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#1126]
Related to opensim-org/opensim-core#2505 & opensim-org/opensim-core#2256

We need to check to see what happens to visualize force vectors in the GUI if there is a NaN in the file. We suspect that the visualization only goes up to the point of the (first) NaN in a file.

**Comment by aymanhab** [comment]
@jimmyDunne I can fake up a file with NaNs but if you have one around that would be useful since these are not randomly generated files. Thank you

**Comment by jimmyDunne** [comment]
Attached is a force file with numerous nan's for each of three force plates. I did a quick check of viewing the forces in the GUI and it seems like the forces play all the way to the end without any observable issue. 

[Running_GRF_cop_nans.mot.zip](https://github.com/opensim-org/opensim-gui/files/3493426/Running_GRF_cop_nans.mot.zip)

**Comment by jenhicks** [comment]
@jimmyDunne Well look into whether plotting leads to issues.

**Comment by jimmyDunne** [comment]
Seems like the Plotter deals with NaNs as missing values, as hoped. Below is zoomed in section of a COP plot-- the Plotter plots the entire length of the trial and, when there are nans, it skips those values. 👍 

![image](https://user-images.githubusercontent.com/5296507/63055695-794d2380-beb4-11e9-9605-e480c74a3e51.png)

**Comment by jenhicks** [comment]
Based on the discussion, I am closing this issue, but please re-open if I am missing something.
