### ISSUE TITLE
Set Default simulation time to 5-10 seconds

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#1127]
The Default end time for the simulation tool in the toolbar is 1000 seconds, which is probably a bit much 🤣 
![Screen Shot 2019-07-22 at 11 25 37 AM](https://user-images.githubusercontent.com/5296507/61644863-82f7b880-ac73-11e9-8bdf-bdfca3bb7779.png)

Could we change this to 5 seconds? 10 second? 

My guess is the default value is set [here](https://github.com/opensim-org/opensim-gui/blob/9c84113658939e42e734c9c3aab3649de38002c2/Gui/opensim/tracking/src/org/opensim/tracking/tools/Bundle.properties), so it seems like an easy change that I am more than happy to make.

**Comment by aymanhab** [comment]
Great,  please do.

**Comment by aymanhab** [comment]
@jimmyDunne this can be closed I think.
