### ISSUE TITLE
Install fails due to the case mismatch: Leg39.osim vs leg39.osim

### ISSUE THREAD

**Issue by yurivict** [opensim-org/opensim-gui#1130]
```
CMake Error at cmake_install.cmake:145 (file):
  file INSTALL cannot find
  "/usr/ports/science/opensim-gui/work/opensim-gui-4.0-16-gc1464a0a/opensim-models/Models/Leg39/Leg39.osim".
```

**Comment by aymanhab** [comment]
Good find, please submit PR to fix. Thank you.

**Comment by yurivict** [comment]
I don't know which case there should be.

**Comment by yurivict** [comment]
Case mismatch is due to the development done on Windows.

**Comment by aymanhab** [comment]
We build and distribute on osx as well, so it's surprising this slipped. Typically model file names are all lowercase, while folders are CamelCase.

**Comment by yurivict** [comment]
You need to set up CI builds on various systems, including linux.
It's free for open source projects, just requires some efforts to set up.
Or alternatively you can use Jenkins server in-house, which is also free but requires efforts to set up.

**Comment by aymanhab** [comment]
This has been fixed so the issue can be closed.
