### ISSUE TITLE
Visualizer perspective buttons do nothing

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#1147]
### Steps to reproduce

1. Open GUI.
2. Open any model.
2. Click one of the cube buttons to change perspective.

### Expected result

perspective changes

### Actual result

nothing

### Environment and GUI version

OpenSim 4.1-2019-10-17-7704209

**Comment by aymanhab** [comment]
@carmichaelong or @jimmyDunne can you verify in the PR build of the GUI? Thanks
