### ISSUE TITLE
Previewed experimental markers disappear when model pose is changed

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#1168]
### Steps to reproduce
- open arm26.osim
- File -> Preview Experimental Data…; select `Resources\Models\Arm26\InverseKinematics\arm26_elbow_flex.trc`
- in Navigator panel, double-click "arm26" to re-select model
- in Coordinates panel, click Poses -> Default

### Expected result
Nothing should change in the visualizer.

### Actual result
Experimental markers disappear.

### Environment and GUI version
Windows 10, OpenSim 4.0 public release

**Comment by jenhicks** [comment]
@aymanhab will take a look.

**Comment by aymanhab** [comment]
Proposed fix in PR
