### ISSUE TITLE
Cannot see Model in OpenSim

### ISSUE THREAD

**Issue by SphenopalatineGanglioneuralgia** [opensim-org/opensim-gui#1176]
### Steps to reproduce
Open OpenSim, open model 'gait2392_simbody.osim' 
### Expected result
I'm a brand new user, just downloaded OpenSim (using Mac) But from the tutorial, it says the model should load, and it suggests you should be able to see the model in the viewer. 
### Actual result
The parameters load, but I cannot see the model in the viewer. Haven't found anything that I've tried to click that makes it visible, yet.
(include screen grabs where appropriate)
![image](https://user-images.githubusercontent.com/61436630/75194875-ed4f6a80-5726-11ea-8b69-ab2b9b79079c.png)

### Environment and GUI version
OpenSim 4.1-2020-01-13-ed8d009
Mac OS, High Sierra, V10.13.6

**Comment by jenhicks** [comment]
@aymanhab Did you see this issue?

**Comment by aymanhab** [comment]
No, and I don't think it belongs here since this is very much unique to machine/OS/Card/...

**Comment by jenhicks** [comment]
Where would you put it? @aymanhab

**Comment by aymanhab** [comment]
This belongs to a forum post where we can help troubleshoot, others may pitch in if ran into similar issue.

**Comment by jenhicks** [comment]
@SphenopalatineGanglioneuralgia Thanks for reporting and sorry you ran into this issue. As @aymanhab mentioned, if you are still experiencing this issue, could you create a post on our user forum. We can help you and others troubleshoot there.

https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91&pluginname=phpBB
