### ISSUE TITLE
Scaling a model loses custom geometry/meshes

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#1182]
@aymanhab commented on [Thu Feb 20 2020](https://github.com/opensim-org/opensim-core/issues/2681)

Reported on forum and by many local users in the past
https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=11542&p=32299&start=0&view=

---

@aymanhab commented on [Fri Feb 21 2020](https://github.com/opensim-org/opensim-core/issues/2681#issuecomment-589772167)

One easy fix that works is to create the model, give it a file/path at the same folder as the starting model. The downside is that if the user saves the model in a different folder the problem will re-occur.  but that's the same as any model with custom geometry

---

@aymanhab commented on [Fri Feb 21 2020](https://github.com/opensim-org/opensim-core/issues/2681#issuecomment-589773213)

@jenhicks @tkuchida @carmichaelong @chrisdembia what are your thoughts? Do you typically save the model manually? Specify a destination model file name in the setup file?

---

@aymanhab commented on [Fri Feb 21 2020](https://github.com/opensim-org/opensim-core/issues/2681#issuecomment-589773808)

Anybody else using Scaling workflow that would be interested in this discussion?

---

@aymanhab commented on [Thu Mar 26 2020](https://github.com/opensim-org/opensim-core/issues/2681#issuecomment-604658386)

This came up a couple more times during the Match 20 workshop, so higher priority. Thoughts @jenhicks 

---

@jenhicks commented on [Thu Mar 26 2020](https://github.com/opensim-org/opensim-core/issues/2681#issuecomment-604726718)

I will put it in the sprint backlog for now so we can discuss how to prioritize.

**Comment by jenhicks** [comment]
@aymanhab Can you make sure there is an update in the changelog?

**Comment by aymanhab** [comment]
@jenhicks Yes, changelog has been updated. Feel free to close.
