### ISSUE TITLE
Use opensim-core master build (cache) for Github Actions of this repo

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#1191]
### Actual result

(include screen grabs where appropriate)

**Comment by aymanhab** [comment]
As of now we use a cached version of opensim-core (on myosin) dating back to 1/2020, need to update opensim-core action to upload the latest build of master instead.

**Comment by aymanhab** [comment]
@chrisdembia Do you know what's involved on the opensim-core side? Is there a better way to do it without using myosin to upload? Thanks

**Comment by chrisdembia** [comment]
I suggest that this repo does what Moco does in GitHub Actions, which is build opensim-core without using Sourceforge/Myosin, and cache the opensim-core build using GitHub Actions.

https://github.com/opensim-org/opensim-moco/blob/4f25baf0096fee0c1288747e8f17abe866f8ef05/.github/workflows/continuous_integration.yml#L39-L67

**Comment by aymanhab** [comment]
close via #1211
