### ISSUE TITLE
ConditionalPathPoint visualization issue

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-gui#1195]
Email from a user:

> in the OpenSim GUI (4.1), when a model is loaded with the default value of a coordinate that's within the range when a <ConditionalPathPoint> is active, then the conditional point is always active, it does not visually deactivate even if you move the coordinate value outside of the specified range of the conditional point.  If the default coordinate value is outside the conditional point's range, then the point behaves as expected, it visually activates and deactivates as the coordinate's value moves in and out of the specified range.  This appears to just be a graphical thing in the Vizualizer Window; the Plot Tool looks like it's calculating muscle kinematics with conditional points activating and deactivating as expected.

I can plan to test and confirm if this is true on multiple models.

**Comment by aymanhab** [comment]
@carmichaelong this may have been fixed by the fix to #1331, either  provide a model to test or close. Thank you

**Comment by carmichaelong** [comment]
Given the description from the user, the model in #1331 should cover this case, so I'm closing this issue
