### ISSUE TITLE
Mac: GUI does not start

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#1204]
### Steps to reproduce

Launch the GUI

### Expected result

GUI launches

### Actual result

<img width="532" alt="image" src="https://user-images.githubusercontent.com/846001/83821928-8c6bf280-a684-11ea-954f-fc0e7c4a509b.png">

I think the issue is that an exception is thrown if the logging file `opensim.log` can't opened, because Macs use `/` as the working directory for applications.

### Environment and GUI version

Mac 4.2-2020-06-02-7baafaf

**Comment by aymanhab** [comment]
@chrisdembia if you sudo launch do you get the file and no exception?  How do you think that worked in the past with out.log or err.log?

**Comment by chrisdembia** [comment]
I'm not willing to try that on my machine; I could try it in a virtual machine. I imagine we just were more lenient about logging to a file. 

Maybe, if we cannot log to the current directory, we should log to a file like `~/.opensim/opensim.log`.

**Comment by aymanhab** [comment]
I understand @chrisdembia but where do the err.log and out.log file get written in the curren GUI that you locally build, or the published 4.1? I can try that myself as well but thought you have this info already. Let me know either way to proceed. Thank you

**Comment by chrisdembia** [comment]
As far as I know, they are not written (because we try to write them to `/` and we can't).

**Comment by aymanhab** [comment]
@chrisdembia when I try to launch the GUI on osx by browsing to the bin folder it actually launches without an issue, is that consistent with your conjecture? Do you know where the messages.log file are typically stored on osx as I couldn't locate them. Thank you

**Comment by chrisdembia** [comment]
The `opensim.log` file is written to your current working directory.

>  is that consistent with your conjecture? 

If you installed the GUI in a user-writable directory, then yes. If not, then no.

**Comment by aymanhab** [comment]
Installing for all users, the error comes from permissions of the file etc/OpenSim.conf which used to be -rw-r--r-- and instead are now -rw-------. Were we doing something special to this file when building installer on travis?

**Comment by chrisdembia** [comment]
Woah how did you figure that out? On my machine, I have the same permissions issue. 

When I build the GUI locally, the permissions are `-rw-r--r--`.

**Comment by chrisdembia** [comment]
Fixing the permissions of `OpenSim.conf` did not allow the GUI to start for me.

**Comment by aymanhab** [comment]
@chrisdembia I found this by trying to lunch from a shell rather than the finder. After I changed permissions, the next error was due to opensim.log. If I launch from a different folder then it works fine the file is written to whatever current working directory. I think we should handle the case of permissions not allowing creation of the file more gracefully. Thakns for your help.

**Comment by chrisdembia** [comment]
Yes, I think we should wrap the creation of the file sink in a try-catch.

**Comment by aymanhab** [comment]
The latest GUI on osx fails to launch because of permissions on opensim.conf, changing the permissions allows the GUI to launch successfully. Another issue observed is that the shortcut is not created, likely due to permissions as well. Just to keep the status of this issue current.

**Comment by aymanhab** [comment]
Info.plist also had wrong permissions, changing this manually fixes the icon and launch.

**Comment by aymanhab** [comment]
This can be closed if somebody on a mac tries the build from github Actions (@jenhicks or @chrisdembia ) and it functions properly (top pick on https://github.com/opensim-org/opensim-gui/actions/), mac artifact.

**Comment by chrisdembia** [comment]
The GUI launches just fine for me on Mac now.

**Comment by chrisdembia** [comment]
I would prefer to not close this issue, because we should find a better fix.

**Comment by aymanhab** [comment]
@chrisdembia I'm trying your conjecture regarding sudo in PR #1210, if that doesn't work not sure what better fixes you have in mind. Also I will open a separate issue for caching so these experiments aren't expensive since we don't know if/why the commented out caching didn't work
