### ISSUE TITLE
Directional views do not work in visualizer window

### ISSUE THREAD

**Issue by antoinefalisse** [opensim-org/opensim-gui#1216]
@aymanhab Since installing OpenSim 4.2-2020-07-14-92d0686 to test #1145, the icons on the visualizer window to view the model from different directions do not work anymore. Clicking on them has no effect.

I mean those icons:

![Picture1](https://user-images.githubusercontent.com/19328993/90907258-09308200-e3d3-11ea-82aa-5a86edeea9bc.png)

Is that expected?

**Comment by aymanhab** [comment]
This has been fixed in the build for PR https://github.com/opensim-org/opensim-gui/pull/1228

**Comment by jenhicks** [comment]
This seems to be fixed for me, but would be great to get your verification as well, @antoinefalisse (when you have a chance).

**Comment by antoinefalisse** [comment]
Working fine with the latest version I have. I close the issue.
