### ISSUE TITLE
test examples/tutorials that exercise ExternalLoads with latest code base/GUI

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#1221]
### Actual result

(include screen grabs where appropriate)

**Comment by aymanhab** [comment]
@jenhicks This is what we discussed in the meeting with @aseth1

**Comment by jenhicks** [comment]
@carmichaelong Started looking at this.

**Comment by carmichaelong** [comment]
Searching "external_loads_model_kinematics_file" in XML files in all 3 repos:

opensim-core
- [ ] Applications/Analyze/test/subject01_Setup_InverseDynamics.xml
- [ ] Applications/Forward/test/pendulum_external_load_point_in_ground.xml
- [ ] Applications/Analyze/test/subject01_Setup_StaticOptimization.xml
- [ ] Applications/ID/test/subject01_walk1_grf.xml
- [ ] Applications/Analyze/test/subject02_grf_HiFreq.xml
- [ ] Applications/CMC/test/subject01_externalForces.xml
- [ ] Applications/RRA/test/subject01_externalForces.xml

opensim-models
- [ ] Tutorials/Strength_of_Simulation/Stance/Reference/leg69_right_grf.xml
- [ ] Tutorials/Estimating_Joint_Reaction_Loads/foot_floor_loads.xml

opensim-gui (none)
