### ISSUE TITLE
Update distributed example setup files to correct paths

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-gui#1229]
### Steps to reproduce 
Tested on `master` branch, `ik_with_imus` branch, and OpenSim 4.1 download)

**RRA "Run" button does not light up**
1. Get Strength_of_Simulation folder either from 1) opensim-models/Tutorials or 2) leg6dof9 folder distributed with GUI
2. Open leg6dof9musc_added_mass.osim (from Strength_of_Simulation/Stance/Reference)
3. Load leg69_Setup_RRA.xml
4. Expect Run button to un-grey, but it does not.

**CMC desired kinematics box is red even though file exists**
1. Get Strength_of_Simulation folder either from 1) opensim-models/Tutorials or 2) leg6dof9 folder distributed with GUI
2. Open leg6dof9musc_added_mass.osim (from Strength_of_Simulation/Stance/Reference)
3. Load leg69_Setup_CMC.xml
4. All boxes should be filled and white, but desired kinematics is red even though file exists

@aymanhab Let me know if there is any other testing I can do to help pinpoint the issue

**Comment by aymanhab** [comment]
Thanks for reporting @carmichaelong I can confirm the following:
CMC: Actually the file doesn't exist though the name is very long but the actual file name specified does not exist, either we need to add the file or rename existing one or the tutorial describes how to generate it.

**Comment by aymanhab** [comment]
RRA validation has a bug where it's checking for control constraints file that's specified and doesn't exist, do you know if these are supposed to be available for RRA? Thank you

**Comment by carmichaelong** [comment]
> CMC: Actually the file doesn't exist though the name is very long but the actual file name specified does not exist, either we need to add the file or rename existing one or the tutorial describes how to generate it.

Oh whoops, good catch. That'll be easy enough to update. I'm also wondering if now is the right time to update the setup file to 4.0 format if this is supposed to be a reference for a user going through the example.

> RRA validation has a bug where it's checking for control constraints file that's specified and doesn't exist, do you know if these are supposed to be available for RRA? Thank you

Thanks again... apparently I can't read file names properly ☹️, I see the difference now (seems like a mash up between the two current control limit file names). I checked some other RRA example files, and it looks like it's in there (and in the confluence documentation), so I guess we should keep it around. Usually you just want these limits to be pretty high to generate any needed torque. For this case it'll at least be easy enough to update.

**Comment by aymanhab** [comment]
Thanks @carmichaelong I agree we should update the example, the tricky part is that we don't expose the constraints file in the GUI (some legacy rationale that it's rarely used), so I'll just disable the check for it and the users will see it upon trying to run if needed rather than getting stuck with the run button disabled.

**Comment by jenhicks** [comment]
What needs to be tested here?

**Comment by carmichaelong** [comment]
I forgot to link the issue that should address this: https://github.com/opensim-org/opensim-models/pull/140

This could be tested by making sure that using the reference setup files in the folder `Strength_of_Simulation/Stance/Reference` for RRA and CMC work out of box
