### ISSUE TITLE
Add confluence pages for IMU based tools

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#1238]
Help links from dialogs of IMU based tools have no place to land.
### Actual result

(include screen grabs where appropriate)

**Comment by aymanhab** [comment]
https://simtk-confluence.stanford.edu/display/OpenSim/IMU+Inverse+Kinematics
I also added 
https://simtk-confluence.stanford.edu/display/OpenSim/How+to+use+the+IMU+Placer but that ended at the top level, do you know how to move it under IMU+Placer page? @carmichaelong or @jenhicks

**Comment by carmichaelong** [comment]
I don't see the "IMU+Placer" page to move the "How To use the IMU Placer" under that one. If you make the "IMU+Placer" page I think I figured out how to move it under there

**Comment by aymanhab** [comment]
Thanks @carmichaelong I think I did it, but another pair of 👀 to confirm would help

**Comment by carmichaelong** [comment]
Looking good to me! I now see both pages with the How To nested in the tree
