### ISSUE TITLE
Blank Visualizer Window

### ISSUE THREAD

**Issue by deyvidpi** [opensim-org/opensim-gui#1254]
### Steps to reproduce
Installing Opensim 4.1 or 4.0 and launching it.

### Expected result
Displaying background + model in the visualizer window.

### Actual result
**Visualizer window is totally black at launch, and becomes white after loading a model, a motion, etc.**

No error message.
Restarting doesn't change anything.
Reinstalling idem.
Works fine with Opensim 3.3

### Environment and GUI version
Win 10 Pro, build 10.0.18363, x64
Lenovo model 4282A82
i7-2720QM CPU @ 2.20GHz, 4 cores, 8 logical cores
RAM 16 Go

**Comment by aymanhab** [comment]
Considering how long these releases have been out, this is specific to your environment, likely related to gfx card issues. There should be a red stop sign error indicator on status bar to help give more info. Try install as admin. This doesn't belong here but on user forum. Thank you
