### ISSUE TITLE
Random exception while editing scale tool setup 

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#1268]
Reported by user testing and by  Antoine during testing 4.2 Beta

### Actual result

(include screen grabs where appropriate)

**Comment by aymanhab** [comment]
Should be fixed by PR #1268

**Comment by aymanhab** [comment]
Waiting for verification!

**Comment by jenhicks** [comment]
@aymanhab I could test this, but can't find specific details about what to test.

**Comment by aymanhab** [comment]
Tested by Antoine, and he gave the thumbs up, so no need to worry about it.
