### ISSUE TITLE
Unable to avoid heading correction in the GUI

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#1272]
In IMU Placer, unable to omit heading correction unless a saved setup file omitting the correction is loaded (can't simply deselect name/axis from default IMU Placer Tool settings or from a loaded setup file with a correction). Error: Invalid specification of heading aixs ' ' found.

### Actual result

(include screen grabs where appropriate)

**Comment by aymanhab** [comment]
The error message was due to passing space ' '  instead of empty string '' to the tool.

**Comment by jenhicks** [comment]
So can this be closed?

**Comment by aymanhab** [comment]
If we merge the branch and the build on master works as expected (which should be the case) then yes.
