### ISSUE TITLE
Crash during saving external load file (v. 4.2 Beta)

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-gui#1280]
### Steps to reproduce
In "External Loads" tabs, when I delete the second forces and save a new file, OpenSim suddenly terminates.
Test data: Gait2392_Simbody files

### Actual result

https://user-images.githubusercontent.com/38867713/110256846-58758300-7fb0-11eb-83c4-33760ff07252.mp4

### Environment and GUI version
Windows 10
6 G RAM

**Comment by aymanhab** [comment]
This crash is due to the deletion from the list of ExternalForces while the tree of Components is not adjusted accordingly. There's no other context in which objects are deleted. Investigating fix.

**Comment by aymanhab** [comment]
Please check fixed in latest master build

**Comment by aymanhab** [comment]
@mrrezaie you can test the fix in latest build artifact (steps here https://github.com/opensim-org/opensim-gui/wiki). Thanks for reporting.

**Comment by mrrezaie** [comment]
Thank you for your endeavours. It is fixed.
