### ISSUE TITLE
CMC GUI does not have Analyses tab

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-gui#1300]
@aymanhab said he'd need to first check why this was removed before (seems like this has been the case for 4.0+).

Note that analyses can still be added in the setup file, and when loading the setup file the Analyses are still applied.

**Comment by aymanhab** [comment]
Version 3.2 didn't have this either, going back to 2014 or earlier. It may have never been exposed as such, and considering that CMC is not under active development and that no users asked for it I'd lean to leave this as is.
