### ISSUE TITLE
Add documentation page for Preview Sensor Data

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#1308]
### Actual result

(include screen grabs where appropriate)

**Comment by aymanhab** [comment]
@jenhicks @carmichaelong Just found out that I didn't add a page to the user guide describing the Preview Sensor Data menu-item/dialog. Can you suggest a place for it under confluence? Thank you

**Comment by aymanhab** [comment]
@carmichaelong can you help me create a blank page on confluence to populate with the documentation. Thank you

**Comment by carmichaelong** [comment]
@aymanhab I started a page here (as a child of User's Guide): https://simtk-confluence.stanford.edu/display/OpenSim/Preview+Sensor+Data

Not sure if this will end of being the best place for it, but figured we could start here and move it later if needed. I've also limited it to the dev team for now, so we'll have to change permissions once it's ready to go

**Comment by aymanhab** [comment]
Thank you
