### ISSUE TITLE
No Visualizer Window in the gui on linux Ubuntu

### ISSUE THREAD

**Issue by SietseAchterop** [opensim-org/opensim-gui#1318]
Hello,

I almost succesfully installed opensim-gui on linux, both on Debian 11.1 and Ubuntu 20.04.
Please find below the complete recipe for the installs. It is almost a script, but not complete.
I think I did exactly what is described in the continuous-integration.yml file.

On Debian it works perfectly! Cool!
On Ubuntu the build went fine, and everything seems to work, only the Visualizer Window is not visible at all.
I can do simulations, use the CMC tool, but nothing is visible.

Apart from a few details the issue is that on Ubuntu the visualizer window is NOT shown.
Don't know if this is relevant, but sdk/Simbody/libexec/simbody/simbody-visualizer works just fine.
Note that on Debian it works. There is no warning at all, or maybe in messages.log, see below.
Maybe I need to build it for Debug, but there is no such option in the opensim-gui makefile. How could I debug this problem?

The other remarks I have are the following:
1. The main executables, notably bin/opensim, do not have execution permission.
2. There are no symbolic links used in sdk/lib and sdk/Simbody/lib where apropriate.
    E.g. libcasadi.so is a copy of libcasadi.so.3.6 instead of a symbolic link to it. A wast of 9 MB.
    In the build_deps all the links are there.
3. The libadolc.so.2 is missing. Also present in the build_deps. Repaired by hand:
       ln -s libadolc.so.2.1.0 libadkolc.so.2
4. In .opensim/var/log/messages.log on ubuntu (not on debian) there is an error (IPC process exited) from line 160.
    See   [varlogmessages.log](https://github.com/opensim-org/opensim-gui/files/7395576/varlogmessages.log). Something about jxBrowser.
5.  In the actual build only a single make is going on, so no "make -j8" or similar.

Here the mentioned part of the messages.log file:
`++++++++++++++
INFO [org.netbeans.core.windows.persistence]: [PersistenceManager.getTopComponentForID]

Problem when deserializing TopComponent for tcID:'jxBrowserTopComponent'. Reason: null

Caused: com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: IPC process exited. Exit code: 127

        at com.teamdev.jxbrowser.chromium.internal.ipc.d.run(SourceFile:198)
++++++++++++++
`

Thanks in advance, Sietse.

Here the recipe: [build.txt](https://github.com/opensim-org/opensim-gui/files/7380428/build.txt)

Update 1: Still having some trouble with using python with opensim.
              On one debian machine importing opensim yields:
       ImportError: /home/sietse/Software/OpenSim/opensim/sdk/lib/libtropter.so: undefined symbol: _ZN8badoublecvRKdEv

Update 2: Added some items to the remarks above. Maybe item 4 has to do with the visualizer.

**Comment by aymanhab** [comment]
This issue is specific to Ubuntu 20.04 as the ci build using 18.04 opens a visualizer window/browser without an issue. The likely reason is that jxbrowser (the third party library we use) relies on some version of low level linux libraries that changed moving from 18.04 to 20.04. Still trying to narrow this down but wanted to point out the status of the investigation.

**Comment by SietseAchterop** [comment]
Thanks. You could well be right.
I build/installed opensim om 2 different debian 11 installations.
One started life as debian 10 ( from before ubuntu 20.04) and is upgraded. Here it works fine.
The other is a fresh install of debian 11 and also has the problem.
Maybe the first one still has a few older libraries.

**Comment by SietseAchterop** [comment]
I reinstalled my linux machines recently and opensim now claims to be version 4.4.  Visualization is now working on all my machines! 
I saw something in the recent patches about this problem, so I guess that solved it, thanks.
Probably this issue can be closed.

**Comment by aymanhab** [comment]
Awesome, thank you so much. I assume 4.4 means master branch which has an upgraded jxBrowser version and would explain the  resolution. All the best.
