### ISSUE TITLE
Visualization bugs with undo support

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#1319]
"Undo" doesn't work for "Show Mass Center" and "Show Axes"

### Actual result

(include screen grabs where appropriate)

**Comment by aymanhab** [comment]
This appears to have been fixed already. Just need another pair of eyes to verify. @carmichaelong or @jenhicks

**Comment by carmichaelong** [comment]
Agreed, looks like this has been fixed, closing
