### ISSUE TITLE
Show, Show Only, and Hide for Muscles do not work

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-gui#1327]
On 4.4-2021-11-30-058542d with Windows 10, options for Show, Show Only, and Hide do not work. Behavior happens whether it's for an individual muscle, group of muscles (chosen by ctrl-click), or all muscles.

**Comment by aymanhab** [comment]
Fixed on visualizer side, fix merged, can test on a future PR

**Comment by aymanhab** [comment]
Fixed in latest master build, please verify

**Comment by carmichaelong** [comment]
Tested OpenSim 4.4-2022-04-12-13e8480 on Windows 10, LGTM
