### ISSUE TITLE
ConditionalPathPoint's sometimes don't visualize correctly

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-gui#1331]
Using this model: [model_vas_conditionalpathpoints.zip](https://github.com/opensim-org/opensim-gui/files/7981450/model_vas_conditionalpathpoints.zip)

1. (to see issues more easily): Show only `knee_ext_r` muscle group, hide body `patella_r`
2. At default pose, 3 vasti muscles have a kink in them, but ConditionalPathPoint should not be engaged until deep knee flexion
![knee1](https://user-images.githubusercontent.com/7455790/152038645-4d11394d-a057-48bd-a53d-2eaf171f226e.png)

3. Change knee flexion coordinate to >90 deg. One of the path points sticks out very far
![knee2](https://user-images.githubusercontent.com/7455790/152039036-fadfcbc6-eb80-4127-9170-6a73546f31b3.png)

4. Returning the knee flexion to < 90 deg (either by using the slider or setting the coordinates back to Default state) does not undo the stray path point
![knee3](https://user-images.githubusercontent.com/7455790/152039147-9ec02911-33c1-447b-bc40-089b57939b0d.png)

Note: Another gait model with ConditionalPathPoints in vas, rec_fem, and iliopsoas seems to visualize OK (see `OpenSim/Examples/Moco/example2DWalking/2D_gait.osim`)

@aymanhab

**Comment by nathantpickle** [comment]
I am seeing a different but potentially related issue where consecutive ConditionalPathPoints do not visualize correctly when some of them are inactive.

This issue can be reproduced in OpenSim 4.3 using the model BothLegs.osim from Applications\Analyze\test in OpenSim Core. 

Here the right knee is flexed to -108 degrees, with only the right VASLAT shown for clarity. In this screenshot, the ConditionalPathPoint VASLAT-P3 is activated but VASLAT-P4 is not, and two separate lines are being drawn for the muscle.

![image](https://user-images.githubusercontent.com/39502679/157509892-539e25e1-e0b8-490d-a98b-6c428924b351.png)

Increasing flexion to -110 degrees activates VASLAT-P4 and the muscle is drawn correctly.

![image](https://user-images.githubusercontent.com/39502679/157510026-51a4230a-8a80-498c-a586-70310eecde80.png)

**Comment by aymanhab** [comment]
For the record, this is not an issue with conditional path points but interaction between conditionalpathpoints and wrapping. In fact if you delete the wrapping on the wrapping tab, the conditional path points acts exactly as expected. Not to justify the bug but for testing when a fix is ready.

**Comment by aymanhab** [comment]
@nathantpickle Once the build artifact is ready you can give it a spin and let me know if you encounter other issues

**Comment by aymanhab** [comment]
@carmichaelong maybe you can test this as another pair of 👀 if @nathantpickle didn't get to it

**Comment by nathantpickle** [comment]
Apologies for the delay, @aymanhab - I just tested this and it looks good to me. Thanks!
