### ISSUE TITLE
StateReporter problem with unit

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-gui#1343]
### Steps to reproduce
1. in GUI, Tools>Analyze
2. Adjust and add StateReporter in the Analyze Set
3. Save the setup file and run the tool
### Expected result
In default StateReporter, <in_degrees> is true (checked) and I would expect to get the results in degrees.
### Actual result
The results are not in degrees anymore.
(inDegrees=no)

### Environment and GUI version
v. 4.3

**Comment by aymanhab** [comment]
Thanks for reporting @mrrezaie The headers indicates correctly that the states are reported in radians. Typically we use this StateReporter for recreating states obtained during integration and as such would avoid converting to/from degrees. As such I don't see this issue as a bug. I agree it's a bit misleading to show a checkbox in the GUI implying that you can control the units but this seems more of a documentation issue than an actual bug. As such I'll close this issue, however if you can think of a better way to document the behavior, feel free to describe and reopen.

**Comment by mrrezaie** [comment]
Hi, Thanks for your reply. 
At least I suggest changing the default "in_degrees" property to "false":
`<StatesReporter name="default">`
`<on>true</on>`
`<start_time>-Inf</start_time>`
`<end_time>Inf</end_time>`
`<step_interval>1</step_interval>`
`<in_degrees>true</in_degrees>`
`</StatesReporter>`
This would be less confusing.
