### ISSUE TITLE
Model get disappeared after running the simulation

### ISSUE THREAD

**Issue by Arish2022** [opensim-org/opensim-gui#1356]
### Actual result

(include screen grabs where appropriate)

### Environment and GUI version
Hello, I'm new to opensim and using version 4.3. When I run the simulated model, the model gets disappeared. Do you have any thoughts on that?
Thanks, Arish

**Comment by tkuchida** [comment]
The [OpenSim User's Forum](https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91) is the best place to ask these types of questions (and to search for answers to similar questions). Three possibilities are that the model has moved outside the region that is visible by the camera, the model has dropped below the floor, or an error has occurred (check for a red circle in the bottom-right corner of the GUI).

**Comment by Arish2022** [comment]
Thank you for your help. I will check with them.
