### ISSUE TITLE
Toolbar displaced and non visible after resizing window

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [opensim-org/opensim-gui#1357]
### Steps to reproduce

Resize the window horizontally to make it smaller until the toolbar does not fit the window, or press Windows + right arrow to split screen.

### Expected result

The toolbar is visible and you can use the animation controls.

### Actual result

Since the toolbar does not fit the window horizontally, all of the elements of the toolbar are displaced below the redo/undo buttons.

![image](https://user-images.githubusercontent.com/15672785/170470259-4648aa00-8a64-47f7-a863-3ca0f51491b2.png)

### Environment and GUI version

 - **Opensim version:** 4.4-2022-05-13-e68ccae *and* 4.4-2022-05-17-cc0a2cf
 - **OS:** Windows 10 Pro 64 bits
 - **Display:** 15.6” 1920x1080

**Comment by aymanhab** [comment]
Once you have a build of the GUI, this would be a rather self-contained issue to tackle @AlbertoCasasOrtiz Let me know if you get there.

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz This looks good, just need to check the mac build to make sure there are no side effects. One other possible improvement is to make the  motion slider anchor to both sides of the application's toolbar so it stretches with resizing rather than anchor only to the left, would you consider taking on this toolbar issue as well? Thank you

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab Sure, I will take care of it!

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz Can you update with the latest status? Thank you

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab The issue is solved in https://github.com/opensim-org/opensim-gui/pull/1377.

However, I was not able to anchor the motion slider to both sides of the toolbar as you requested.

**Comment by aymanhab** [comment]
Thanks, can you verify it works as expected on osx?

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab I have just tested the artifact on Mac 11 and it is working properly,

**Comment by aymanhab** [comment]
Great, thank you 👍
