### ISSUE TITLE
Camera perspective icons not working properly after manually changing camera position and orientation.

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [opensim-org/opensim-gui#1358]
### Steps to reproduce

- Use camera perspective icons, it works normally.

![image](https://user-images.githubusercontent.com/15672785/170472763-0bec22b8-8f67-44a4-a3af-fcf8cc80fb44.png)

- Manually change camera orientation, position, and zoom using the mouse's right and left buttons and the wheel in the visualizer window.

- Use camera perspective icons again and click on them multiple times.

(I've tried with different models, and the error can be reproduced in all of them)

### Expected result

After manually changing the camera position and orientation, the buttons should work exactly as before manually changing them.

### Actual result

After manually changing camera position and orientation, if you click on the perspective icons, the model is not positioned as expected.

For example, if I manually position the camera as in the next screenshot:

![image](https://user-images.githubusercontent.com/15672785/170473196-0712fd67-3de4-4bd6-b4c7-ca2e4daf0bf6.png)

And then, I click the perspective button to see the model from above, this is what I get:

![image](https://user-images.githubusercontent.com/15672785/170473398-7dd55ef4-393e-42bc-97e3-e4b328fb97d4.png)

If I click the button multiple times, or I try clicking any of the other buttons, the camera changes its position and orientation weirdly until the model disappears.

![image](https://user-images.githubusercontent.com/15672785/170473632-17170ea8-bdf2-4c4d-90e3-145b09bcfeaf.png)

### Environment and GUI version

 - **Opensim version:** 4.4-2022-05-17-cc0a2cf
 - **OS:** Windows 10 Pro 64 bits
 - **Display:** 15.6” 1920x1080

**Comment by aymanhab** [comment]
This was verified fixed in later beta builds
