### ISSUE TITLE
Blank Visualizer Window while loading a model

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [opensim-org/opensim-gui#1359]
### Steps to reproduce

Load a first model after running the GUI on an old computer.

**Note:** I had the browser and some more programs opened consuming RAM and CPU, so this may have contributed to this problem

### Expected result

The model loads and is shown in the visualizer window.
If the model takes time to load, the GUI should show a message or progress bar indicating it is loading the model).

### Actual result

The visualizer window keeps blank for a few seconds (10 in my case). In the messages tab, there is a message indicating that the model has already been loaded, but the visualizer window is still blank.

The GUI is not frozen and you can use it while it is loading, so I guess it has already loaded the model, but it is taking time to draw everything in the visualizer window.

```
Updating Model file from 20303 to latest format...
Loaded model 3DGaitModel2392 from file C:\Users\<user>\Documents\OpenSim\4.4-2022-05-13-e68ccae\Models\Gait2392_Simbody\gait2392_simbody.osim
ControllerSet 'Controllers' was renamed and is being reset to 'controllerset'.
ComponentSet 'MiscComponents' was renamed and is being reset to 'componentset'.
```

![image](https://user-images.githubusercontent.com/15672785/170475271-6f76898b-11f7-4328-9f54-b945ea5935ed.png)

### Environment and GUI version

 - **Opensim version:** 4.4-2022-05-13-e68ccae *and* 4.4-2022-05-17-cc0a2cf
 - **OS:** Windows 10 Pro 64 bits
 - **Display:** 15.6” 1920x1080
 - **Processor:** Intel Core i7-4710HQ 2.5GHz
 - **GPU:** NVIDIA GeForce GTX 850M
 - **RAM:** 8GB

**Comment by aymanhab** [comment]
Thanks for reporting @AlbertoCasasOrtiz can you clarify if this is on first launch of an installation (ever) or first model on subsequent launches. The first scenario is expected because the platform and third-party tools we use build a cache and copy a ton of large files to it, some outside our control, but would be good to know. Also the browser/graphics window is launched as a separate process so what resources are available on the machine come into play.

**Comment by AlbertoCasasOrtiz** [comment]
This happened on the first launch after installing the application. It took around 10 seconds to show the model in the visualizer. In subsequent launches, it takes 1-3 seconds. Normally, I have the browser and some more applications opened, which could have contributed to this.
