### ISSUE TITLE
Green arrows representing ground reaction forces are not fully visible during the gait

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [opensim-org/opensim-gui#1361]
### Steps to reproduce

Follow [tutorial 3.V](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Tutorial+3+-+Scaling%2C+Inverse+Kinematics%2C+and+Inverse+Dynamics#Tutorial3Scaling,InverseKinematics,andInverseDynamics-V.InverseDynamics) to show ground reaction force vectors as green arrows.

### Expected result

It is easy to visualize the arrows.

### Actual result

From some angles, it is difficult to visualize the green arrows because the model is in front of them. I think there should be an option that makes the green arrows always visible independently of the elements in front of them

![image](https://user-images.githubusercontent.com/15672785/170481347-2e062d23-0198-403f-9937-061c6f4c65da.png)

### Environment and GUI version

 - **Opensim version:** 4.4-2022-05-13-e68ccae *and* 4.4-2022-05-17-cc0a2cf
 - **OS:** Windows 10 Pro 64 bits
 - **Display:** 15.6” 1920x1080

**Comment by aymanhab** [comment]
This is not a bug AFAICT, if you have multiple objects in 3D they will occlude each other but feel free to add suggestions @AlbertoCasasOrtiz
