### ISSUE TITLE
Building on Linux: Netbeans 8.2 no longer available

### ISSUE THREAD

**Issue by mjhmilla** [opensim-org/opensim-gui#1364]
### Steps to reproduce

wget https://download.netbeans.org/netbeans/8.2/final/bundles/netbeans-8.2-javase-linux.sh

### Expected result

netbeans-8.2-javase-linux.sh is downloaded

### Actual result

An html file is downloaded instead. I found out why by:

1. Using a browser to look at: https://download.netbeans.org/netbeans
2. This redirected me to: https://netbeans.apache.org/download/archive/index.html
3. If you click on '[JDK 8u111 with NetBeans 8.2] under "Pre Apache versions" it goes to a dead link.

(include screen grabs where appropriate)

### Environment and GUI version

Ubuntu 20.04 GUI 4.3. I realize the GUI hasn't been tested on Ubuntu 20.04 but I thought I'd try in case the GUI functions.

**Comment by mjhmilla** [comment]
Good to hear from you @aymanhab :)

I'll try NetBeans 12.3 later today. I guess then the issue will probably change: the linux installation instructions say to use netbeans 8.2 and must be out of date. In any case, thanks for the quick response.

**Comment by mjhmilla** [comment]
Hello @aymanhab, 

I'm making progress installing opensim & opensim-gui on ubuntu 20.04. I'm going to describe where I'm getting tripped up below. However, before I do that: is this the correct place to be asking these questions and working through installation difficulties? If not, close this issue and move this conversation over to the correct spot.

On with the update ...

I'm getting further, which is good. Right now I'm having problems at line 271 of the [ci](https://github.com/opensim-org/opensim-gui/blob/master/.github/workflows/continuous-integration.yml) file you sent which has:

make CopyOpenSimCore

The error message I get is below. There are three things to keep in mind:

1. When I run ctest on OpenSim I get failures on tests related to python (2 tests), java (3 tests), and Matlab (15 tests). I find this strange because cmake happily found my installations of 

- python3 (v 3.8.10), 
- java ( a bit newer than specified: openjdk 17.0.3 2022-04-19, OpenJDK Runtime Environment (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1), OpenJDK 64-Bit Server VM (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)
- matlab 2021b

2. I put my build and install directories for opensim, and for the opensim-gui in locations that differ from the default.
3. I had to install ant (sudo apt install ant)

Finally, calling
  make CopyOpenSimCore
produces the following list of errors:


**Error message**
make CopyOpenSimCore
-- Build VERSION: 4.4-2022-05-23-5aa1e9b7
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mmillard/opensim-gui-build
[100%] Copy opensim-core Java Bindings to GUI.
Buildfile: /home/mmillard/opensim-gui/Gui/opensim/build.xml

BUILD FAILED
/home/mmillard/opensim-gui/Gui/opensim/build.xml:50: The following error occurred while executing this line:
/home/mmillard/opensim-gui/Gui/opensim/nbproject/build-impl.xml:41: Cannot find NetBeans build harness. 
Check that nbplatform.default.netbeans.dest.dir and nbplatform.default.harness.dir are defined. 
On a developer machine these are normally defined in ${user.properties.file}=${netbeans.user}/build.properties 
but for automated builds you should pass these properties to Ant explicitly.

Total time: 0 seconds
make[3]: *** [Gui/opensim/CMakeFiles/CopyOpenSimCore.dir/build.make:58: Gui/opensim/CMakeFiles/CopyOpenSimCore] Error 1
make[2]: *** [CMakeFiles/Makefile2:210: Gui/opensim/CMakeFiles/CopyOpenSimCore.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:217: Gui/opensim/CMakeFiles/CopyOpenSimCore.dir/rule] Error 2
make: *** [Makefile:170: CopyOpenSimCore] Error 2

**Comment by mjhmilla** [comment]
Hello @aymanhab, 

I'm making progress installing opensim & opensim-gui on ubuntu 20.04. I'm going to describe where I'm getting tripped up below. However, before I do that: is this the correct place to be asking these questions and working through installation difficulties? If not, close this issue and move this conversation over to the correct spot.

On with the update ...

I'm getting further, which is good. Right now I'm having problems at line 271 of the [ci](https://github.com/opensim-org/opensim-gui/blob/master/.github/workflows/continuous-integration.yml) file you sent which has:

make CopyOpenSimCore

The error message I get is below. There are three things to keep in mind:

1. When I run ctest on OpenSim I get failures on tests related to python (2 tests), java (3 tests), and Matlab (15 tests). I find this strange because cmake happily found my installations of 

- python3 (v 3.8.10), 
- java ( a bit newer than specified: openjdk 17.0.3 2022-04-19, OpenJDK Runtime Environment (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1), OpenJDK 64-Bit Server VM (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)
- matlab 2021b

2. I put my build and install directories for opensim, and for the opensim-gui in locations that differ from the default.
3. I had to install ant (sudo apt install ant)

Finally, calling
  make CopyOpenSimCore
produces the following list of errors:


**Error message**
make CopyOpenSimCore
-- Build VERSION: 4.4-2022-05-23-5aa1e9b7
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mmillard/opensim-gui-build
[100%] Copy opensim-core Java Bindings to GUI.
Buildfile: /home/mmillard/opensim-gui/Gui/opensim/build.xml

BUILD FAILED
/home/mmillard/opensim-gui/Gui/opensim/build.xml:50: The following error occurred while executing this line:
/home/mmillard/opensim-gui/Gui/opensim/nbproject/build-impl.xml:41: Cannot find NetBeans build harness. 
Check that nbplatform.default.netbeans.dest.dir and nbplatform.default.harness.dir are defined. 
On a developer machine these are normally defined in ${user.properties.file}=${netbeans.user}/build.properties 
but for automated builds you should pass these properties to Ant explicitly.

Total time: 0 seconds
make[3]: *** [Gui/opensim/CMakeFiles/CopyOpenSimCore.dir/build.make:58: Gui/opensim/CMakeFiles/CopyOpenSimCore] Error 1
make[2]: *** [CMakeFiles/Makefile2:210: Gui/opensim/CMakeFiles/CopyOpenSimCore.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:217: Gui/opensim/CMakeFiles/CopyOpenSimCore.dir/rule] Error 2
make: *** [Makefile:170: CopyOpenSimCore] Error 2

**Comment by mjhmilla** [comment]
As a note for others:

I was able to get OpenSim to build under Ubuntu 20.04 with python wrapping by:

- Following the build instructions on [continuous_integration.yml](https://github.com/opensim-org/opensim-core/blob/master/.github/workflows/continuous_integration.yml) 
- Disabled Tropter
- Disabled Adolc
- Disabled Java
- Followed the [python setup instructions](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Scripting+in+Python#ScriptinginPython-Ubuntu) on confluence

This builds fine and all tests pass on Ubuntu 20.04. However, OpenSim needs to be build with java wrapping so that the OpenSim-gui can function. This is a bit of a problem on Ubuntu 20.04: the oldest supported version of java is openjdk-8-jdk, but OpenSim requires openjdk-7-jdk. 

I've installed openjdk-8-jdk and have made it the default java package using `sudo update-java-alternatives -s java-1.8.0-openjdk-amd64`. Calling `java -version' shows that the default has been updated (which naturally has broken a few things, including a Firefox plugin).

**Comment by mjhmilla** [comment]
Actually, it is possible to install java-1.7.0-openjdk on Ubuntu 20.04 as documented here: https://askubuntu.com/questions/1053764/how-to-install-openjdk-7-on-ubuntu-18-04

In summary:

1. Download it from Oracle's archives (this requires that you make an account and login)
  https://www.oracle.com/java/technologies/javase/javase7-archive-downloads.html
  
2. Follow the instructions here:
  https://askubuntu.com/questions/1034387/how-can-i-install-jdk7-on-ubuntu-18-04-lts-64bit

**Comment by rutuja1409** [comment]
> As a note for others:
> 
> I was able to get OpenSim to build under Ubuntu 20.04 with python wrapping by:
> 
> * Following the build instructions on [continuous_integration.yml](https://github.com/opensim-org/opensim-core/blob/master/.github/workflows/continuous_integration.yml)
> * Disabled Tropter
> * Disabled Adolc
> * Disabled Java
> * Followed the [python setup instructions](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Scripting+in+Python#ScriptinginPython-Ubuntu) on confluence
> 
> This builds fine and all tests pass on Ubuntu 20.04. However, OpenSim needs to be build with java wrapping so that the OpenSim-gui can function. This is a bit of a problem on Ubuntu 20.04: the oldest supported version of java is openjdk-8-jdk, but OpenSim requires openjdk-7-jdk.
> 
> I've installed openjdk-8-jdk and have made it the default java package using `sudo update-java-alternatives -s java-1.8.0-openjdk-amd64`. Calling `java -version' shows that the default has been updated (which naturally has broken a few things, including a Firefox plugin). After re-building OpenSim with java wrapping turned on all of the tests related to java-wrapping failed.
> 
> Luckily I have another computer that is running ubuntu 18.04. Hopefully I can get openjdk-7-jdk installed on it.

Hello @mjhmilla ,
The last step (bash INSTALL - https://github.com/opensim-org/opensim-gui#:~:text=Building%20on%20Linux%20(beta)) is giving me the error. because the install file has if condition for 18.04 if I change that to 20.04 then I'm getting the error - chown: invalid group: ‘lahoti:lahoti’. Can anybody help me in this ?
