### ISSUE TITLE
GUI crashes when running IK tool right after Scale tool with gait2392

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-gui#1369]
@aymanhab Saw this while trying to test the gait2392 pipeline with the posted beta build

### Steps to reproduce
1. open gait2392_simbody.osim
2. open the Scale Tool, load the provided setup file subject01_Setup_Scale.xml, and run
3. open the IK tool, load the provided setup file subject01_Setup_IK.xml, and run

### Expected result
IK tool runs without crashing

### Actual result
IK tool runs to the end and then the GUI quits immediately.

Possible relevant part of trace (full crash log attached): 
[ik_crash.txt](https://github.com/opensim-org/opensim-gui/files/8882583/ik_crash.txt)

```
Thread 110 Crashed:: Java: Thread-21
0   ???                           	    0x7ff8a5dd2940 ???
1   libsystem_kernel.dylib        	    0x7ff81582300e __pthread_kill + 10
2   libsystem_pthread.dylib       	    0x7ff8158591ff pthread_kill + 263
3   libsystem_c.dylib             	    0x7ff8157a4d24 abort + 123
4   libjvm.dylib                  	       0x10bfa426e os::abort(bool) + 22
5   libjvm.dylib                  	       0x10c0b2f2a VMError::report_and_die() + 2236
6   libjvm.dylib                  	       0x10bfa88e3 JVM_handle_bsd_signal + 526
7   libjvm.dylib                  	       0x10bfa6238 signalHandler(int, __siginfo*, void*) + 45
8   libsystem_platform.dylib      	    0x7ff81586edfd _sigtramp + 29
9   ???                           	               0x0 ???
10  libosimTools.dylib            	       0x19fa7b8d8 OpenSim::InverseKinematicsTool::run() + 6680
11  libosimJavaJNI.dylib          	       0x19db52936 Java_org_opensim_modeling_opensimActuatorsAnalysesToolsJNI_InverseKinematicsTool_1run + 22
12  ???                           	       0x10d98ae47 ???
13  ???                           	       0x10d97a7d0 ???
14  ???                           	       0x10d97a7d0 ???
15  ???                           	       0x10d97ad80 ???
16  ???                           	       0x10d97b042 ???
17  ???                           	       0x10d9734e7 ???
18  libjvm.dylib                  	       0x10bde0ee1 JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*) + 1719
19  libjvm.dylib                  	       0x10bddfced JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*) + 345
20  libjvm.dylib                  	       0x10bddfec9 JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*) + 87
21  libjvm.dylib                  	       0x10be57bd3 thread_entry(JavaThread*, Thread*) + 120
22  libjvm.dylib                  	       0x10c075e9c JavaThread::thread_main_inner() + 130
23  libjvm.dylib                  	       0x10c075d61 JavaThread::run() + 361
24  libjvm.dylib                  	       0x10bfa3d9f java_start(Thread*) + 250
25  libsystem_pthread.dylib       	    0x7ff8158594e1 _pthread_start + 125
26  libsystem_pthread.dylib       	    0x7ff815854f6b thread_start + 15
```

### Environment and GUI version
MacBook Pro M1 Max, 4.4 beta build (4.4-2022-06-10-c2ce8a0)

### Other notes
- This does workflow does not crash in 4.3
- This workflow did not crash when only doing the IK step:
1) load subject01_simbody.osim
2) run IK using the setup file subject01_Setup_IK.xml

**Comment by aymanhab** [comment]
Good find @carmichaelong Interestingly, running IK only shows no issues, can you confirm to help pinpoint the culprit? Thank you

**Comment by carmichaelong** [comment]
That's correct. It's sort of buried at the bottom of the post (I probably should have had these notes above the crash dump), but I tried the workflow in 4.3 (did work) and tried IK only with the beta (did work).

**Comment by aymanhab** [comment]
Fixed and integrated in this artifact as tested on windows
https://github.com/opensim-org/opensim-gui/actions/runs/2481628737
If you can verify on Mac @carmichaelong that would be awesome. Thank you
