### ISSUE TITLE
GUI draws a left-handed reference frame (Y axis pointed in opposite direction)

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#1371]
### Steps to reproduce
- open arm26.osim
- in the Navigator, double-click "r_acromion" under "Markers"

### Expected result
Red, green, and blue arrows form a right-handed reference frame.

### Actual result
Green line extends from the origin in the wrong direction. Arrowhead cone is oriented correctly (upwards), but the lines of the frame define a left-handed reference frame. This is potentially confusing, particularly for students who are new to mechanics. Left-handed reference frames are rarely used.
![image](https://user-images.githubusercontent.com/4203505/175811973-0bc60fd3-09bf-434c-b80f-4c0504c61260.png)

### Environment and GUI version
OpenSim 4.4-2022-04-22-788d079 from #1347

**Comment by aymanhab** [comment]
In essence we do not create/draw these triads, we use the conventions built into the underlying threejs.  Based on reasons unclear to me they use this triad sometimes, I guess the rationale was to indicate you can move in either direction. I can investigate further but would prefer not to hijack the built-in selection mechanism.
