### ISSUE TITLE
Linux build instructions want unavailable netbeans version

### ISSUE THREAD

**Issue by zupatisc** [opensim-org/opensim-gui#1375]
Hello,
I am currently trying to package OpenSim and for that trying to follow the instructions in the README.
It appears that the netbeans-8.2 release can no longer be downloaded or at least both wget or curl pull in a html response instead of the intended script and the section on Apache's website for netbeans releases pre-Apache seems to be broken/missing.
I will try netbeans 9.0 but the README should probably be updated with either the newer version or some way to still obtain 8.2

**Comment by aymanhab** [comment]
Hi, the instructions on github are stale, we're updating them and will be updated shortly by @AlbertoCasasOrtiz However you can use the continuous integration script 
https://github.com/opensim-org/opensim-gui/blob/master/.github/workflows/continuous-integration.yml
for the latest script used for continuous integration (now uses netbeans 12)

**Comment by zupatisc** [comment]
Thanks I have now set it up far enough that opensim-core gets compiled and installed to the custom directory but I do have a question. I did look at [opensim-build](https://github.com/marnunez/opensim-build) to see how the whole thing gets installed in the end but I don't really understand what the copyX targets in the Makefile do.

**Comment by AlbertoCasasOrtiz** [comment]
Hi, I have just created a pull request with a new script to build opensim-gui in Ubuntu 18.04. Until the pull request is approved, you can find it here:
[https://github.com/AlbertoCasasOrtiz/opensim-gui/tree/update-linux-build-script#building-on-linux-beta](https://github.com/AlbertoCasasOrtiz/opensim-gui/tree/update-linux-build-script#building-on-linux-beta)

**Comment by zupatisc** [comment]
Cool I will check that out and use that to get my packaging going fully. I uploaded the WIP PKGBUILD here [opensim-PKGBUILD](https://github.com/zupatisc/opensim-PKGBUILD)

**Comment by zupatisc** [comment]
I realize that this veers a bit from the original issue but I hope it's relevant enough to the Linux build topic.
I have adapted my package to use your new build instructions, currently I get this error:
```
-do-compile:
    [mkdir] Created dir: /home/xxx/Githubs/opensim-PKGBUILD/src/opensim-gui-source/Gui/opensim/jfreechart/build/classes
 [nb-javac] Compiling 497 source files to /home/xxx/Githubs/opensim-PKGBUILD/src/opensim-gui-source/Gui/opensim/jfreechart/build/classes
 [nb-javac] warning: [options] bootstrap class path not set in conjunction with -source 6
 [nb-javac] error: Source option 6 is no longer supported. Use 7 or later.
 [nb-javac] error: Target option 6 is no longer supported. Use 7 or later.

BUILD FAILED
/usr/share/apache-netbeans/harness/suite.xml:163: The following error occurred while executing this line:
/usr/share/apache-netbeans/harness/common.xml:206: Compile failed; see the compiler error output for details.

Total time: 1 second
make[3]: *** [Gui/opensim/CMakeFiles/PrepareInstaller.dir/build.make:71: Gui/opensim/CMakeFiles/PrepareInstaller] Error 1
make[2]: *** [CMakeFiles/Makefile2:210: Gui/opensim/CMakeFiles/PrepareInstaller.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:217: Gui/opensim/CMakeFiles/PrepareInstaller.dir/rule] Error 2
make: *** [Makefile:176: PrepareInstaller] Error 2
```
apache-netbeans is Netbeans 12.3 installed through the packagemanager so it should be the correct version. I am not really sure where the `-source 6` is set or if this comes from the netbeans install or opensim.
