### ISSUE TITLE
Path edit broken for muscles with wrapping

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#1379]
### Steps to reproduce
Reported by @tkuchida in beta testing

### Actual result

(include screen grabs where appropriate)

### Environment and GUI version
4.4 Beta

**Comment by tkuchida** [comment]
Possibly related: [User's Forum Topic 14880](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=14880)

**Comment by aymanhab** [comment]
Description from testing doc. to verify fixed in artifact builds
Muscle GeometryPath editor: "java.lang.IndexOutOfBoundsException: Index: 4, Size: 4". To reproduce: (1) Open arm26 model. (2) In Navigator, select Muscles > TRIlong. (3) Click "…" beside "GeometryPath" in Properties window. (4) Click Add > before 1. (5) On row 1, change X = -0.055 to, e.g., X = 0.1 and press <Enter>. Expected: muscle point updates. Actual: red circle appears in bottom-right corner of GUI.

**Comment by aymanhab** [comment]
Fixed in artifact of this PR. Thanks for testing and reporting @tkuchida 
@carmichaelong if you can doublecheck the fix in the artifacts I'd appreciate it, then we can merge and backport to 4.4 branch before posting.

**Comment by tkuchida** [comment]
Potentially related [issue posted to the Forum (topic 15006)](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=15006).

**Comment by carmichaelong** [comment]
@aymanhab @tkuchida I tried the Forum issue posted most recently in this thread. I was able to replicate in the 4.4 GUI, and also saw that this issue occurred with a muscle with wrapping objects, but not with a muscle that had no wrapping objects associated.
