### ISSUE TITLE
Marker selection in Navigator is not synced with Properties

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#1395]
### Steps to reproduce
- open arm26 model
- in Navigator, expand "Markers"
- double-click "r_acromion" in Navigator
- double-click "r_humerus_epicondyle" in Navigator

### Expected result
The "r_humerus_epicondyle" marker is highlighted in the Navigator and selected in the Visualizer, and the Properties window displays its properties.

### Actual result
The "r_humerus_epicondyle" marker is highlighted in the Navigator and selected in the Visualizer, but the Properties window is showing the properties for "r_acromion". This should not be possible.

![](https://user-images.githubusercontent.com/4203505/197648732-38785b25-1600-42ad-8df9-565579fc1008.png)

### Environment and GUI version
Public release of 4.4

**Comment by aymanhab** [comment]
Thanks for reporting @tkuchida Indeed I reproduced it on Windows. Single click however works as expected but I'm investigating further. Can you confirm what platform was that reported on? Thanks

**Comment by aymanhab** [comment]
Notes from investigation so-far: 
Selecting visually in 3D view (1 click) results in all the correct updates in navigator, properties
Single select in navigator, updates properties window but doesn't select in 3D view
Double-click in navigator highlights in 3D view correctly but fails/incorrect in Properties window

**Comment by tkuchida** [comment]
> Can you confirm what platform was that reported on?

Windows 10 Pro; installed via the "official release" Windows installer on simtk 🐴
