### ISSUE TITLE
Offset added to experimental data visualization

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#1416]
### Steps to reproduce
https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=15325&p=0&start=0&view=&sid=8e4e5488bee1c29f376989601835f1e6
### Actual result

(include screen grabs where appropriate)

**Comment by tkuchida** [comment]
(Link above should be to topic 15335: https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=15335 🦓)
