### ISSUE TITLE
Hidden objects are selectable

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-gui#1435]
### Steps to reproduce
Open Rajagopal model
Double click on the tfl_r insertion on the knee.
### Expected result
The insertion point should be selected. 
(Generally it would be great if you make the hidden objects unselectable)
### Actual result
A hidden object (wrapping geometry) is selected instead.

https://user-images.githubusercontent.com/38867713/226384034-7d48a406-394b-4a1c-abc1-ce844ad4d92d.mp4

### Environment and GUI version
Windows 10, OpenSim 4.4

**Comment by mrrezaie** [comment]
Hi @aymanhab, I just tested OpenSim 4.5-2023-02-15-b7a0f04 and it was fixed. Thank you.

**Comment by aymanhab** [comment]
Great, thank you @mrrezaie
