### ISSUE TITLE
Adding a marker to a model does not persist after saving and opening the model

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-gui#1437]
### Steps to reproduce
- Open a model
- Expand the model tree in the navigator
- Right click Markers and add a new marker
- Save the model to a new file
- Open the new model file

### Expected result
Model has the new marker added

### Actual result
Model does not have the added marker

### Environment and GUI version
OpenSim 4.4, macOS

**Comment by aymanhab** [comment]
@carmichaelong Not sure if this is model or platform specific but it works as expected in dev builds on windows. Please detail steps in case there're multiple workflows that lead to different results. Thanks

**Comment by carmichaelong** [comment]
Closing this issue for now. I tried again on both Mac and Windows with 3 different models (arm26, gait10dof18, and laiarnold) and could not replicate this.
