### ISSUE TITLE
Cyan ellipsoid drawn to visualize EllipsoidJoint cannot be hidden

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#1440]
### Steps to reproduce
Open a model containing an EllipsoidJoint (e.g., [this one](https://github.com/opensim-org/opensim-gui/files/4295775/arm26_withEllipsoidJoint.txt))

### Expected result
Cyan ellipsoid [drawn by EllipsoidJoint::generateDecorations()](https://github.com/opensim-org/opensim-core/blob/0a138219a7cc95942a91235227c40d43fb1acf42/OpenSim/Simulation/SimbodyEngine/EllipsoidJoint.cpp#L167) can be hidden somehow

### Actual result
Unclear how to hide the cyan ellipsoid

### Environment and GUI version
OpenSim 4.4 release version

**Comment by tkuchida** [comment]
@aseth1

**Comment by aymanhab** [comment]
@tkuchida Generally components can do visualization either by including a Geometry subclass component (e.g. Sphere, Ellipsoid, ...) or implement a generateDecorations method and take visualization in their hands (as done for Markers for example).
The first approach serializes Appearance property tp XML that users rely on to persist and modify visibility. color etc.
The second approach has no built in Appearance control and mostly rely on ModelDisplayHints for global control (show_markers, show_contact_geometry, ....) these are then queried in generateDecorations to decide whether to show/hide.
A third option, if a component knows it has visuals and still prefers to use generateDecorations as is the case with GeometryPath, is to include an Appearance property and use that to serialize/control visualization), and then have the generateDecorations method query/use the Appearance property. This latter option seems the most appropriate for the Ellipsoid joint. If you follow the pattern of GeometryPath you should be good to go and the GUI will be able to leverage it without any extra work. Please let me know what you think.

**Comment by tkuchida** [comment]
@aymanhab Thanks- that's super helpful. I agree: given the options, creating an Appearance property seems like a good strategy.
