### ISSUE TITLE
[Suggestion] visualize body's axis in body's COM location

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-gui#1441]
Hi, OpenSim visualizes body's reference frame in the same location as joint's frame which is actually misleading and not consistent with Biomechanics textbooks, e.g., [Biomechanics of Human Movement](https://biomech.stanford.edu/):

![image](https://user-images.githubusercontent.com/38867713/233128432-d0178518-0467-4f38-9c70-313923b307f8.png) ![image](https://user-images.githubusercontent.com/38867713/233125175-0659779f-c4eb-4fec-babe-bc7f81958133.png)

I suggest body's COM location would be a better place for visualizing the origin of the body's axis.

Thank you,
Mohammadreza

**Comment by tkuchida** [comment]
The model developer decides where the joint frames on each body segment are located with respect to the body segment's origin. This is not an error in the OpenSim GUI. I believe this Issue is a request to redefine the gait2392 model so that each body segment origin is coincident with the COM.

**Comment by mrrezaie** [comment]
@tkuchida, you are right, I can define the position and orientation of joint's frame. But I have no idea how to relocate the body's frame to be coincident with its COM. Also, this is the case for Rajagopal model as well. Could you please show me how? 
(In the gait2392 model, the position of femur's COM in femur's frame is [0, -0.17, 0]). Thank you.

**Comment by tkuchida** [comment]
All body-fixed frames are defined with respect to the origin of the body, not the other way around. In your example, to "move the origin" of the femur body to be coincident with its COM, you would add 0.17 to the y-coordinate of the COM location (making its location [0, 0, 0] relative to the origin), add 0.17 to the y-coordinate of the locations of all markers attached to the femur, add 0.17 to the y-coordinate of all PhysicalFrames whose parent is the femur, move the geometry, etc. (If you move the knee joint's frame on the femur, note that you will also need to modify the function that defines the translation of the knee relative to the femur.)

**Comment by mrrezaie** [comment]
Thanks @tkuchida, it makes sense to me. The following changes must be applied, please correct me:

- modify the geometry file (femur_r.vtp): transform the geometry by [0, 0.17, 0] so that the zero coordinates would relocate to mass center

![2023-04-20-10-15-26](https://user-images.githubusercontent.com/38867713/233283179-4ba9904e-ebcd-4a52-9cfc-9108ae6fa353.png) ![2023-04-20-10-16-00](https://user-images.githubusercontent.com/38867713/233283207-5e9bc211-d356-4034-8ad7-e33f8c94ce65.png)

- modify the location of femur's mass center: [0, 0, 0]
- modify the hip joint's child frame location: [0, 0.17, 0]
- modify the knee joint's parent frame location: in case of gait2392 model, add 0.17 to the joint's vertical translation coordinate:
```
<x> -2.0944 -1.22173 -0.523599 -0.349066 -0.174533 0.159149 2.0944</x>
<y> -0.2526 -0.2382 -0.229 -0.2276 -0.2266 -0.225264 -0.226</y>
```
- modify muscles' attachments on femur body
- modify markers' attachments on femur body

And this is the output:

https://user-images.githubusercontent.com/38867713/233292361-a106e5b4-426a-48f3-ab6a-152388922426.mp4

However, it requires lots of work, all geometry files must be modified and stored for every model, otherwise, it doesn't work in case of two models with same geometry files but different mass center parameters. Furthermore, the femoral head center is actually a better location for geometry's zero coordinates.

My suggestion is that you add an option [Edit > Preferences] to whether visualize the body's frame in body's origin (i.e., zero coordinates in the geometry file; the current OpenSim behavior) or in body's mass center. In this case, there is no need for such modifications for any model.

Thank you,
Mohammadreza

**Comment by tkuchida** [comment]
> modify the geometry file (femur_r.vtp): transform the geometry by [0, 0.17, 0] so that the zero coordinates would relocate to mass center

You shouldn't need to modify the geometry file itself, just the location at which the geometry is attached to the body. If it was originally attached at the origin, you would need to create a PhysicalOffsetFrame to attach it somewhere other than the origin (after redefining the origin location).

> My suggestion is that you add an option [Edit > Preferences] to whether visualize the body's frame in body's origin (i.e., zero coordinates in the geometry file; the current OpenSim behavior) or in body's mass center. In this case, there is no need for such modifications for any model.

It shouldn't matter where the origin is defined. It is often convenient to define it at the COM, but in that case, moving the COM would also move the origin and therefore would require editing all the other points on the body (frames, markers, muscle paths, etc.).

**Comment by tkuchida** [comment]
@mrrezaie If you haven't seen it already, you might want to check out [OpenSim Creator](https://opensimcreator.com/) as it has many nice features for model building.

**Comment by mrrezaie** [comment]
@tkuchida Thank you, the above femur images were captured in OpenSim Creator. 

My suggestion was merely for visualization's sake, nothing will be changed, just visualization. An alternative suggestion would be to add this option when right click on a body: 

- Show Axes at Origin
- Show Axes at Mass Center

![image](https://user-images.githubusercontent.com/38867713/233442296-ceef91aa-7456-4427-bd8d-1dc1bbda885d.png)


This is not uncommon, for instance, Visual3D:
![image](https://user-images.githubusercontent.com/38867713/233441113-99f40a38-bfb6-4af6-89a8-5e7b20134044.png)

**Comment by aymanhab** [comment]
Seems potentially useful to some users but confusing to others who may not know then what x,y,z of com, path-points, frames are relative to, so will leave as is for now.
