### ISSUE TITLE
How to develop opensim-gui?

### ISSUE THREAD

**Issue by iverson1github** [opensim-org/opensim-gui#1457]
How to develop opensim-gui project?

**Comment by aymanhab** [comment]
The project is open-source and you can clone the repo and follow the instructions on the readme and the ci build script to build latest version of the application. At this point you have a full replica of the source. The GUI is written in Java using the netbeans platform, so it allows for plugins to add functionality. If you have specific needs or ideas for development we'd be happy to collaborate. Some context would be useful. This doesn't seem to be an "issue" but we can leave it open for further discussion and in case better documentation is identified.

**Comment by iverson1github** [comment]
Thank you for your help. But I cannot be used to netbeans IDE. Can I develop the project by using IntelliJ IDEA IDE?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "opensim-org/opensim-gui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月18日(星期五) 凌晨3:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [opensim-org/opensim-gui] How to develop opensim-gui? (Issue #1457)





 
The project is open-source and you can clone the repo and follow the instructions on the readme and the ci build script to build latest version of the application. At this point you have a full replica of the source. The GUI is written in Java using the netbeans platform, so it allows for plugins to add functionality. If you have specific needs or ideas for development we'd be happy to collaborate. Some context would be useful. This doesn't seem to be an "issue" but we can leave it open for further discussion and in case better documentation is identified.

**Comment by nickbianco** [comment]
Hi @iverson1github, what application are you trying to create with the GUI? This topic seems better suited for the OpenSim forum: https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91&pluginname=phpBB.

Please post your question there and we can help you.
