### ISSUE TITLE
Can I develop the opensim-gui by using IntelliJ IDEA IDE?

### ISSUE THREAD

**Issue by iverson1github** [opensim-org/opensim-gui#1458]
Can I develop the opensim-gui by using IntelliJ IDEA IDE? If you can, how to build the enviroment with IntelliJ IDEA?

**Comment by aymanhab** [comment]
While the gui uses components from netbeans so you need to have it installed, the build mechanism is ant based so you can use any ide.

**Comment by aymanhab** [comment]
This doesn't seem to be an issue in fact as such will close. Please reopen if a specific issue arises thank you
