### ISSUE TITLE
Fix build in sync with opensim-core changes

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#1460]
### Steps to reproduce
ci fails to build on all platforms  starting 20230903

### Actual result

(include screen grabs where appropriate)

**Comment by aymanhab** [comment]
@nickbianco GUI builds started failing on all platforms last week which is expected due to some Path changes. Should I try to update/fix now or is there a major change in the pipe before the function-based PR? Thanks

**Comment by nickbianco** [comment]
@aymanhab, yes I think you can start fixing these errors now. There are a few changes to `AbstractPath` in the upcoming PR, but they are minor (e.g., `getColor()` and `setColor()` now have default implementations),

**Comment by aymanhab** [comment]
Should be fixed by PR #1461
