### ISSUE TITLE
visualizer window cuts the above motion bar

### ISSUE THREAD

**Issue by nehaphd** [opensim-org/opensim-gui#1470]
### Actual result

(include screen grabs where appropriate)

**Comment by nehaphd** [comment]
![image](https://github.com/opensim-org/opensim-gui/assets/119163314/149d79e0-ab89-48fe-b53b-15de92d4175c)

**Comment by nehaphd** [comment]
please help me resolve this

**Comment by AlbertoCasasOrtiz** [comment]
Hello @nehaphd, thank you for reporting this issue.

What OS and what version of the GUI are you using?

This is a bug we identified an solved in https://github.com/opensim-org/opensim-gui/pull/1377 at some point. Is it possible you are using an older version of the GUI?

**Comment by AlbertoCasasOrtiz** [comment]
Hi @nehaphd. I just tested and this was solved in OpenSim 4.5 ([see Changelog](https://github.com/opensim-org/opensim-gui/blob/cfbf426585be7310e7f4a8168a96a8ff747415f0/CHANGELOG.md?plain=1#L11)). You can download the 4.5 version [here](https://simtk.org/frs/?group_id=91).
