### ISSUE TITLE
Hiding markers for non-current model throws exception

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-gui#1487]
### Steps to reproduce
- Open two models
- Select one model
- Try to hide markers on the other model

### Expected result
- Markers on the "other" model are hidden

### Actual result
- Exception thrown, markers are not hidden

(include screen grabs where appropriate)

### Environment and GUI version
Windows 11, 4.5 (also issue with previous versions)

**Comment by jenniferMaier** [comment]
I experienced the same problem when showing/hiding bodies of a non-current model.

**Comment by aymanhab** [comment]
Fix verified and merged
