### ISSUE TITLE
BUILD FAILED - javac "source option 6 is no longer supported. Use 7 or later."

### ISSUE THREAD

**Issue by ksomml** [opensim-org/opensim-gui#1489]
Everything seems to build properly until i receive this error almost at the very end:

```
-do-compile:
 [nb-javac] Compiling 497 source files to /home/somml/opensim-workspace/opensim-gui-source/Gui/opensim/jfreechart/build/classes
 [nb-javac] warning: [options] bootstrap class path not set in conjunction with -source 6
 [nb-javac] error: Source option 6 is no longer supported. Use 7 or later.
 [nb-javac] error: Target option 6 is no longer supported. Use 7 or later.

BUILD FAILED
/home/somml/netbeans-12.3/netbeans/harness/suite.xml:163: The following error occurred while executing this line:
/home/somml/netbeans-12.3/netbeans/harness/common.xml:206: Compile failed; see the compiler error output for details.

Total time: 1 second
make[3]: *** [Gui/opensim/CMakeFiles/PrepareInstaller.dir/build.make:71: Gui/opensim/CMakeFiles/PrepareInstaller] Error 1
make[2]: *** [CMakeFiles/Makefile2:210: Gui/opensim/CMakeFiles/PrepareInstaller.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:217: Gui/opensim/CMakeFiles/PrepareInstaller.dir/rule] Error 2
make: *** [Makefile:176: PrepareInstaller] Error 2
```

Found a solution on the internet for it:
https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html

But can't find where I should change it in the opensim-gui files besides all the project.properties files which I already tried but didn't seem to be the fix.

I also found an older comment with the same issue:
https://github.com/opensim-org/opensim-gui/issues/1375#issuecomment-1186541796

but i could neither find any troubleshooting solutions for this inside the readme nor the building instructions.

Any ideas?

**Comment by aymanhab** [comment]
Every submodule of the opensim-gui has a project.properties file that contains source level (now set to 1.6). Try changing to 1.7 or 1.8. Could you be using a more recent jdk that has deprecated the 1.6 source option? Let us know what you find out.

**Comment by ksomml** [comment]
You were right, thanks!
The jdk I had installed was "too recent" it seemed. I've removed everything java related and used the jdk which gets installed when building. Then it built successfully!

Last question, I could not find a separate executable for the gui. Is it built in into opensim-cmd? The time I had to check it, I could not find any way to access the gui quickly.

**Comment by aymanhab** [comment]
The installer builds an executable, on windows it's bin/OpenSim64.exe  on pther platforms it's a launcher with name opensim, it's not built into opensim-cmd which is a utility to execute tools at the API/command-line level.

**Comment by ksomml** [comment]
I found that one in the application list on Ubuntu, but it does not open. Wasn't able to find the original executable to check its console logs yet.

Will close this particular issue now, because that one seems fixed because the build itself was successfull.
