### ISSUE TITLE
CoordinateActuator: Invalid coordinate (r_handle_rot) specified in Actuator handle_motor

### ISSUE THREAD

**Issue by PamSanHer** [opensim-org/opensim-gui#1491]
### Steps to reproduce
I've added this to a copy of the arm26 xml file 

			<Body name="bucket">
					<mass>1.0</mass>  
					<mass_center>0.0 -0.1 0.0</mass_center> 
					<inertia_xx>0.0024</inertia_xx> 
					<inertia_yy>0.0028</inertia_yy>
					<inertia_zz>0.0224</inertia_zz>	
					<inertia_xy>0.0</inertia_xy>
					<inertia_xz>0.0</inertia_xz>
					<inertia_yz>0.0</inertia_yz>
					<Joint>
						<PinJoint name="r_handle">
							<parent_body> r_ulna_radius_hand </parent_body>
							<location_in_parent> 0.031    -0.31    0.07    </location_in_parent>
							<orientation_in_parent>    0.0    0.0    0.0    </orientation_in_parent>
							<location> 0.0    0.0    0.0    </location>
							<orientation> 0.0    0.0    0.0    </orientation>
							<CoordinateSet name="">
								<objects>
									<Coordinate name="r_handle_rot">
										
										<motion_type> rotational </motion_type>
										<default_value> 0.0 </default_value>
										<default_speed_value> 0.0 </default_speed_value>
										<initial_value> 0.0 </initial_value>
										<range> -3.14159265 3.14159265 </range>
										<clamped> false </clamped>
										<locked> false </locked>
										<prescribed_function/>
									</Coordinate>						
								</objects>
								<groups/>
							</CoordinateSet>
						</PinJoint>
					</Joint>
					<VisibleObject name="">
						
						<GeometrySet>
							<objects>
								<DisplayGeometry>
									
									<geometry_file>bucket.vtp</geometry_file>
									
									<color>1 1 1</color>
									
									<texture_file></texture_file>
									
									<transform>0 0 0 0 0 0</transform>
									
									<scale_factors>1 1 1</scale_factors>
									
									<display_preference>4</display_preference>
									
									<opacity>1</opacity>
								</DisplayGeometry>
							</objects>
							<groups/>
						</GeometrySet>
					</VisibleObject>
					<WrapObjectSet/>
				</Body>
			</objects>
			<groups />

I've also changed the part in ForceSet tag like this:

      <CoordinateActuator name="handle_motor">
					<isDisabled>false</isDisabled>
					
					<min_control>-infinity</min_control>
					
					<max_control>infinity</max_control>
					<coordinate>r_handle_rot</coordinate>
					<optimal_force>1000</optimal_force>
				</CoordinateActuator>

### Expected result
Seeing the model with the bucket 

### Actual result
I'm getting this message
![image](https://github.com/opensim-org/opensim-gui/assets/42455161/493825c0-0ab7-4ce2-8ca2-28eef3a7380c)

(include screen grabs where appropriate)

### Environment and GUI version
OpenSim 4.5-2024-01-10-3b63585 , Windows 10

I can't see where I went wrong, can you please help me?

**Comment by aymanhab** [comment]
Please indicate where you got the instructions and the model file arm26-copia2 as the osim file format has changed over time and the additional xml blocks may not work with the latest format/version.

**Comment by aymanhab** [comment]
Closing due to missing details, please reopen with details if still an  issue.
