### ISSUE TITLE
Error when plotting MOT/STO files

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-gui#1496]
### Steps to reproduce
1. open Plotter
2. load an MOT or STO file (IK or SO output in my case)
3. choose Y and X quantities
4. hit Add
### Expected result
I should see the curve.
### Actual result
Raises this error:
```
java.lang.RuntimeException: Array index out of bounds
	Thrown at Array.h:391 in get().
	at org.opensim.modeling.opensimCommonJNI.ArrayDouble_getitem(Native Method)
	at org.opensim.modeling.ArrayDouble.getitem(ArrayDouble.java:238)
	...
```

### Environment and GUI version
Windows 10, OpenSim 4.5-2024-03-11-765d625

**Comment by aymanhab** [comment]
@mrrezaie Thanks for reporting, but please provide the specific file that caused the crash as it was not possible to reproduce with a generic .mot file locally.  Thank you

**Comment by mrrezaie** [comment]
Hi, sorry, I was testing with this artifact https://github.com/opensim-org/opensim-gui/actions/runs/8228001907

**Comment by mrrezaie** [comment]
@aymanhab is it because that build (artifact) has not been merged to the main branch yet?

**Comment by mrrezaie** [comment]
@aymanhab, I tested the corresponding artifact and the Plotter worked well. Thanks for the fix. There is also another similar issue, so I'm posting it here:

In that [artifact](https://github.com/opensim-org/opensim-gui/actions/runs/8331332107), when saving and re-loading a setup file in Analyze tool, this happens to the actuators files box:
![image](https://github.com/opensim-org/opensim-gui/assets/38867713/90ed7e0f-4646-4f40-9175-e4eaa1f13863)
as well as this pop-up error:
`Object: Cannot construct from empty filename. No filename specified.
	Thrown at Object.cpp:98 in Object().`
This works correctly in the official 4.5. Thank you.
