### ISSUE TITLE
Abrupt exit when trying to edit CMC task file

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-gui#1506]
### Steps to reproduce
1. Load any model
2. Open CMC tool
3. select any of these tracking task files:

- https://github.com/opensim-org/opensim-models/blob/master/Pipelines/Gait2392_Simbody/gait2392_CMC_Tasks.xml
- https://github.com/opensim-org/opensim-models/blob/master/Pipelines/Rajagopal/CMC/walk/cmc_tasks.xml

4.  Click on "Edit file contents"

![image](https://github.com/opensim-org/opensim-gui/assets/38867713/01282eef-dde6-4d09-a257-27e06ba97d7a)

### Expected result
A new window that shows the contents

### Actual result
Abrupt exit with this error file:
[hs_err_pid3280.log](https://github.com/opensim-org/opensim-gui/files/15083473/hs_err_pid3280.log)

(Also, `CMC_TaskSet` does not exist in "XML Browser")
### Environment and GUI version
Windows 10, official OpenSim 4.5

**Comment by aymanhab** [comment]
Fix is ready, artifact builds here https://github.com/opensim-org/opensim-gui/actions/runs/9214347497#artifacts once tested will merge the changes to opensim-core

**Comment by mrrezaie** [comment]
Works well, thanks @aymanhab
