### ISSUE TITLE
Saving Movies from visualizer

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#164]
If possible, would be ideal for ISB

**Comment by aymanhab** [comment]
For now moved the capture text to the bottom so it's readable

**Comment by aymanhab** [comment]
The specific issues I'm addressing under this generic title:

- [ ] Visualizer hangs after first movie save
- [ ] Better feedback that we're recording.
- [ ] Possible control of recording frequency

**Comment by aymanhab** [comment]
Since we switched from continuous rendering (runs battery down) to render on demand (fewer frames, very fast/short movies), reducing the number of frames per sec. helps. Now investigating the display not refreshing while recording.

**Comment by aymanhab** [comment]
With the latest fixes, we can close this general one and open specific ones if needed so we can decide on priorities.

**Comment by jenhicks** [comment]
Has anyone made a movie from a Windows build? @jimmyDunne @aseth1

**Comment by tkuchida** [comment]
> 1. When I click the camera icon, I get no indication that movie recording has begun

Not fixed if background is gray. Reported in [Forum Topic 9389](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=9389).
