### ISSUE TITLE
Cannot find AppState.xml if launching from app from Finder, etc.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#198]
If you launch OpenSIm.app from the Finder, I think the "working directory" is root, `/`. In this case, I am unable to find AppState.xml, and I don't know if it is actually written anywhere. It would be good to make sure that AppState.xml is written to a known directory in the cache dir or the application support dir, rather than in the working dir.

**Comment by jenhicks** [comment]
I am able to launch OpenSim from the finder.
