### ISSUE TITLE
ISB dry run: loading scale setup (gait1018 model) and clicking tabs causes crash

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#205]
[scale_crash.txt](https://github.com/opensim-org/opensim-gui/files/1106882/scale_crash.txt)

**Comment by aseth1** [comment]
With OpenSim 2112110-2018-01-31 ScaleTool Tabs and measurement set editing worked for me on Mac. @chrisdembia @carmichaelong please confirm and then close if successful.

**Comment by chrisdembia** [comment]
I'm confused by my title for this issue; I don't see any scale setup file for gait10dof18musc

**Comment by chrisdembia** [comment]
Instead of using gait10dof18musc, I tried loading gait2354 and loading its scale setup and clicking around the scale tool window (different tabs) and did not get a crash.
