### ISSUE TITLE
ModelLight does not create shadows

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#219]
Using opensim_devWin64_060217.zip (AFAIK, the last release with Expert Mode). ModelLight (of type SpotLight) doesn't create shadows despite setting the "Shadow/cast" property to true. Also tested in https://threejs.org/editor/ (by loading .json file) and found the same issue.

**Comment by aymanhab** [comment]
ModelLight is not creating shadows and is internal (not exposed and not a spotlight anymore), so this specific issue is rather obsolete.
