### ISSUE TITLE
THREE.Matrix3.getInverse(): can't invert matrix

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#221]
Opening the arm26.osim model, lifting the arm in the coordinates pane, and clicking Simulate causes the arm to disappear for parts of the motion, and the following error is printed:

```
OnConsoleMessage{type=OnConsoleMessage, uid=17017, level=1, message='THREE.Matrix3.getInverse(): can't invert matrix, determinant is 0', lineNumber=4646, sourceId='http://localhost:8002/threejs/build/three.js'}, SocketInfo{cid=0, bid=0, channelType=Browser}
```

Maybe threejs needs to use quaternions!

**Comment by aymanhab** [comment]
Exact same behavior observed in 3.3, due to transforms being garbage. This is NOT visualization or GUI issue at all.

**Comment by tkuchida** [comment]
Would it be possible to provide a more meaningful user-facing error message than "THREE.Matrix3.getInverse(): can't invert matrix, determinant is 0"? Perhaps move to opensim-core repo to catch and throw an OpenSim Exception?

**Comment by aymanhab** [comment]
@tkuchida The error was seen by @chrisdembia in the browser, there are no errors seen or reported to users AFAIK.

**Comment by tkuchida** [comment]
> The error was seen by @chrisdembia in the browser, there are no errors seen or reported to users AFAIK.

Oh, that's even worse. Is it possible to communicate to the user why the model disappears for parts of the motion? If this scenario would be caught at the API level, then perhaps move the Issue to opensim-core?

**Comment by aymanhab** [comment]
Agreed @tkuchida, can you move or close and open a core issue @jenhicks? Thanks

**Comment by tkuchida** [comment]
Issue moved to [opensim-org/opensim-core #2141](https://github.com/opensim-org/opensim-core/issues/2141) via [**ZenHub**](https://www.zenhub.com/)
