### ISSUE TITLE
New OpenSim logo is hard to see in Windows 10 toolbar

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#238]
I updated the GUI's OpenSim logo to the more recent OpenSim logo, but this logo is hard to see on the Windows 10 toolbar:

![image](https://user-images.githubusercontent.com/846001/27820161-4f20f5c2-6052-11e7-82e4-b5641d85ad55.png)

Here's what it looks like when the app is selected:
![image](https://user-images.githubusercontent.com/846001/27820175-5cc5ea34-6052-11e7-8706-db066ab0c435.png)

**Comment by jenhicks** [comment]
Here's a 64x64 gif. What formats do you need exactly?
![opensimlogooutline64](https://user-images.githubusercontent.com/4510959/32467838-ca62bc1e-c300-11e7-8e96-3b002967e08d.gif)

**Comment by aymanhab** [comment]
I believe Application icons come in 3 sizes 16x16, 32x32 and 48x48 both png and gif are supported AFAIK

**Comment by jenhicks** [comment]
Here you go. These seem pretty low res. Has the resolution not changed at all even as monitor quality has improved over time?
![opensimlogooutline48](https://user-images.githubusercontent.com/4510959/32468164-fd6387d2-c301-11e7-90db-d0fa297795fe.png)
![opensimlogooutline32](https://user-images.githubusercontent.com/4510959/32468167-001939b8-c302-11e7-8c23-62d3396609a5.png)
![opensimlogooutline16](https://user-images.githubusercontent.com/4510959/32468169-015ecd60-c302-11e7-8901-1b3bff9ad286.png)

**Comment by jenhicks** [comment]
The source psd file is in the OpenSim Documentation dropbox folder
resources->Logos->OpenSimLogoOutline.psd

**Comment by aymanhab** [comment]
Thanks @jenhicks , I'll try these. In general Icons on windows don't show up big so they can get away with that low res, not on osx.

**Comment by aymanhab** [comment]
![captureicon](https://user-images.githubusercontent.com/3972208/32470081-b01854cc-c30a-11e7-9239-2bd88a33d39c.PNG)

**Comment by aymanhab** [comment]
Since it's better than the previous one on Windows I'll merge. Thanks @jenhicks 
![captureappiconminimized](https://user-images.githubusercontent.com/3972208/32509028-0694ab2a-c3a1-11e7-92e8-268025c6c1ef.PNG)
![captureappicon](https://user-images.githubusercontent.com/3972208/32509029-06b0b266-c3a1-11e7-8bef-d8cef00306d8.PNG)

**Comment by aseth1** [comment]
Better than it was, but still blurry and not so great in Windows, IMHO. Can we generate lower resolution with fewer details?

**Comment by jimmyDunne** [comment]
W10, opensim-04-16-2018.zip

How the 3.3 (left) and 4.0 (right) logo's compare in the toolbar;

![logo_in_toolbar](https://user-images.githubusercontent.com/5296507/38884375-4652f9fe-4224-11e8-812f-b629fd742ca6.png)

I think the man is too dark. I can only see the blue O.

The logo in the window

![logo_in_window](https://user-images.githubusercontent.com/5296507/38884494-aadb2536-4224-11e8-8122-fa1f6923cd27.png)

**Comment by jenhicks** [comment]
@aymanhab Can you verify that you're using the new icons (where the many is gray) that I generated? It doesn't seem like they made it into the build.

**Comment by chrisdembia** [comment]
> @aymanhab Can you verify that you're using the new icons (where the many is gray) that I generated? It doesn't seem like they made it into the build.

It seems like @jenhicks's newer icon *is* used for the `opensim64.exe` file (in File Explorer): 
<img width="216" alt="screen shot 2018-04-17 at 10 42 39 am" src="https://user-images.githubusercontent.com/846001/38886859-115d5b2e-422c-11e8-83f0-7345180758bc.png">

**Comment by jimmyDunne** [comment]
This is what I am getting on W10. Is this an installation thing (I am using from zip)?

![icon_in_w10](https://user-images.githubusercontent.com/5296507/38887355-77db58fa-422d-11e8-8848-d800ef805569.png)

**Comment by aymanhab** [comment]
Yes @jimmyDunne it's installation thing that's done manually and not integrated into automated builds. The last installer I made was before the workshop. I don't remember when were the icons updated.

**Comment by aymanhab** [comment]
Looks fine now similar to last screen capture
