### ISSUE TITLE
Unable to display parent/child frames of joint

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#263]
**Steps to reproduce**
- open a model
- expand the *Joints* group in the *Navigator* panel
- right-click a joint

**Expected behavior**
"Toggle Parent Frame" and "Toggle Child Frame" are enabled and can be toggled. State is indicated by presence (true) or absence (false) of checkmark. If true, frame is shown in visualizer; if false, frame is not shown.

**Actual behavior**
"Toggle Parent Frame" and "Toggle Child Frame" are disabled and checked (see screencap). User is unable to toggle. Despite being checked, the frames are not shown in the visualizer.

![nav](https://user-images.githubusercontent.com/4203505/27989428-4600dcc0-63ed-11e7-88de-c7fb0c246fe2.png)

**Test conditions**
opensim_embeddedBrowser062717Win64.zip on Windows 7.

**Comment by aseth1** [comment]
Joint frame now appear, but they are indistinguishable from one another and other frames.

**Comment by tkuchida** [comment]
Original issue corrected (verified in OpenSim-2416f17a-2018-02-25.zip: "OpenSim 4.0 User Experience and Feedback Session" version). @aseth1: Please close and, if desired, create a new Issue about distinguishing among parent, child, and other frames.

**Comment by aseth1** [comment]
Closing issue since it is technically fixed and issue #550 was opened to to capture fact the frames are now indistinguishable.
