### ISSUE TITLE
Editing force expressed in and point expressed in does not change how force vector is visualized

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#27]
https://github.com/opensim-org/opensim32/issues/5

**Comment by jimmyDunne** [comment]
I was not able to change the visualization of the force vector by editing "force expressed in" or "point expressed in".  Perhaps I am doing this incorrectly, but I tried a bunch of different ways and was unable to change the force visualization. 


![external_loads_expressed_in](https://user-images.githubusercontent.com/5296507/38883171-06aa3a68-4221-11e8-8105-4b4ac3e7b3d3.gif)

**Comment by aseth1** [comment]
Changing the *force/point expressed in* frame does change how the force is visualized. I have to do generate some known data to verify that the visualization is correct.

**Comment by aseth1** [comment]
Verified using a pendulum model with known applied gravity vector that points and force vectors are re-expressed correctly. The visualization is correct also for the jumper model and its experimental ground reaction forces.

However I had several related issues about the task/process (#912). The main issue being what the user is supposed to do once they have correctly expressed their external forces in OpenSim and saved their settings in .xml file, given they can reuse (or load it) for visualization again.

The

**Comment by chrisdembia** [comment]
@aymanhab would like @aseth1 to provide the data set he used for verifying. Not ready to be closed.
