### ISSUE TITLE
Create Windows Installer (.exe)

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#277]
A shortcut in the `opensim` directory will avoid any confusion about how to run OpenSim. The `opensim` directory is also where out.log, err.log, and hs_err_pid*.log get written, so that seems like a good place for the shortcut.

**Comment by aymanhab** [comment]
I'll change this issue to be "create a Windows installer", an installer should create the shortcut(s) and also install/run the distributable.

**Comment by jenhicks** [comment]
@aymanhab For the location directory, can you capitalize "OpenSim" to be consistent with previous releases?

**Comment by aymanhab** [comment]
Capitalization done @jenhicks but still need to run redistributable, give option to update path and add entry point to application and installer from the start menu.
