### ISSUE TITLE
Hiding muscles with 54 muscles takes nearly a minute 

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#281]
It also hides one muscle at a time, each taking ~1s on a fast desktop.

**Comment by aseth1** [comment]
Hiding and showing seems to be fine on Mac. This was confirmed on OpenSim 2112110-2018-01-31 build.

@tkuchida can you confirm on Windows? Thanks!

**Comment by tkuchida** [comment]
Show/hide muscles and bodies is no longer slow on Windows (using AppVeyor artifact OpenSim-078b8daf-2018-01-26.zip); closing.
