### ISSUE TITLE
COM display is not updated when segment's mass center location is edited.

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#296]
Display of COM from Bodies Node (that worked in 3.3) is not supported by 4.0 GUI.

**Comment by aymanhab** [comment]
Fixed in PR #646 in the pipe

**Comment by jenhicks** [comment]
I can display the mass center of bodies on my Mac. Not sure how the new behavior compares to functionality in 3.3

**Comment by aymanhab** [comment]
Should be exactly the same except in the past we used a mesh file with part green part black, now just green sphere AFAIK

**Comment by jimmyDunne** [comment]
I can display the COM for each body, but when I change the location of the mass_center in the properties pane, the visualization of the COM does not change. If I save the model (with the new COM location), close the model, reopen, and display COM, the new COM is seen.

**Comment by jenhicks** [comment]
I moved this issue back to the to-do list and updated it's title to reflect the problem.

**Comment by jimmyDunne** [comment]
Working
W10. OpenSim-cedd8d22-2018-05-31-win64.exe
