### ISSUE TITLE
GUI linear interpolation and resampling of "Results" motions produces bad ID results and performance

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#3]
Running IDTool in the GUI (OpenSim 3.2) with a "Results" file from a previous run of the Tool, or any other Tool, results in wrong ID results. This is because the Results motion files are corrupted by linear interpolation and re-sampled at a high (1000Hz) frequency. This does 2 things that are awful. First, it introduces discontinuities in the velocities and acceleration because each original data point is a corner between lines, and second the files are huge so filtering and splining take forever - orders of magnitude longer than ID takes to solve. The corners result in the large (50,000+N) forces. For example, take a gait model, disable all Forces, and run the ForwardTool for 2s with no external loads. It free falls. The states file generates has 6 data rows and the Results file saved from the GUI has 2000. Running ID on the Results file produces spikes where at times reported in states file (i.e. 6 time points).

**Comment by jenhicks** [comment]
> For example, take a gait model, disable all Forces, and run the ForwardTool for 2s with no external loads. It free falls. The states file generates has 6 data rows and the Results file saved from the GUI has 2000.

I don't see this behavior in the latest build.

**Comment by jenhicks** [comment]
Results saved from the GUI and the Forward tool are also now the same on Mac.
