### ISSUE TITLE
Closing and Opening the visualizer puts it in the wrong spot

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#308]
The top of the visualizer is cut off. I was able to reproduce this.

Steps:
Open GUI 
Load Model
Close the embedded visualizer
Re-open the embedded visualizer

<img width="1176" alt="bugreport" src="https://user-images.githubusercontent.com/4510959/28326117-b87f0ea8-6b94-11e7-92b7-2cce09a1dd18.png">

**Comment by jimmyDunne** [comment]
Issue still exists on W10

**Comment by jenhicks** [comment]
I have moved this to the backlog since it is still in issue on Windows, but lower priority than other outstanding issues.
