### ISSUE TITLE
Holes and missing faces in muscle geometry

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#311]
I think similar issues have been closed, but it's still an issue on Windows at least (opensim4.0PreviewWin64_0717.zip). Here's a zoomed-in view of the ISB jumper:
![muscles](https://user-images.githubusercontent.com/4203505/28342404-ec24b748-6bcc-11e7-9d31-af6f6aa77667.png)

**Comment by jenhicks** [comment]
I am not able to produce the visualization issues that Tom noted in the latest build.

**Comment by aymanhab** [comment]
Yes, these were due to incorrect normals along the path of the muscle that were fixed. @tkuchida can verify if seen recently. Also at some point we had blending weights that didn't add up to 1 for perceived smoother display, but these caused other artifacts and were removed as well.

**Comment by tkuchida** [comment]
> Yes, these were due to incorrect normals along the path of the muscle that were fixed. @tkuchida can verify if seen recently. Also at some point we had blending weights that didn't add up to 1 for perceived smoother display, but these caused other artifacts and were removed as well.

Verified that muscle cylinders (1) no longer have holes, and (2) pass through all path points. I've opened a separate Issue about adding endcaps (#581). AppVeyor artifact OpenSim-e7831221-2018-03-06.zip

![](https://user-images.githubusercontent.com/4203505/37240804-23e678ce-2405-11e8-9113-78be3462379f.png)

![](https://user-images.githubusercontent.com/4203505/37240813-26ea9ae6-2405-11e8-91d1-32de7a2fbf91.png)
