### ISSUE TITLE
Lights go out in visualizer window

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#312]
- open ISB jumper model
- right-click Bodies in Navigator and select Display>Hide; wait until all Bodies are hidden
- right-click Bodies in Navigator and select Display>Show; wait until all Bodies are shown
- repeat a couple times

Visualizer window turns black. Can close and open models, but visualizer window remains black. Closing the visualizer window and selecting Window>Visualizer doesn't turn the light back on. Can't figure out how to change the light bulb 💡

**Comment by aseth1** [comment]
@tkuchida and I will verify this is no longer an issue.

**Comment by aseth1** [comment]
Good news, I was not able to get the screen to go dark when hiding and showing bodies repeatedly. Bad news is that it takes 10-15s to change the opacity of bodies even when they are hidden. This with Mac build OpenSim 2112110-2018-01-31. Changing the color of bones is almost snappy. Opacity "Apply" button white when it can be pressed and highlighted blue when it should be grayed out during processing (applying). Button is also inconsistent with the Color setting panel having a blue "OK" button.

**Comment by tkuchida** [comment]
Tested on Windows using "OpenSim-078b8daf-2018-01-26.zip" (artifact downloaded from AppVeyor) with ISB tutorial files [here](https://www.dropbox.com/s/1itz7kdo382vvbm/ISBTutorial2017.zip?dl=0). Results:
- Unable to reproduce original "blackout" Issue.
- Confirmed lag when modifying opacity of multiple bodies at once. Right-clicking *Bodies* -> *Display* -> *Opacity…* and clicking *Apply* results in 22-second lag. *Apply* button remains pushed down during lag; normal operation resumes when operation completes.

**Comment by tkuchida** [comment]
Still an issue on AppVeyor artifact OpenSim-2fd23ef3-2018-02-20.zip. I had opened and closed about 50 models during testing, and eventually this happened:
![](https://user-images.githubusercontent.com/4203505/36566150-7941cc86-17d7-11e8-97bf-156d963e4c51.png)

**Comment by jenhicks** [comment]
@aymanhab What do you want to do with this one?

**Comment by aymanhab** [comment]
This is basically jxbrowser crashing, unfortunately we can't restart it without closing the application, but users can still save their work. If there's a specific operation that caused this then it would be good to know otherwise it's less useful and can be closed. @tkuchida any specific function you were testing?

**Comment by tkuchida** [comment]
@aymanhab I was in the process of opening/editing/reopening the 44 models in the opensim-models repo for https://github.com/opensim-org/opensim-models/issues/51 and https://github.com/opensim-org/opensim-models/issues/56. According to my comment, the crash occurred after about 50 models.

**Comment by aymanhab** [comment]
I would close it and keep an eye if that ever happens again. I don't think we have a magic number of model opens that we can test against!
