### ISSUE TITLE
User can adjust location of "active model" spotlight

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#314]
Low-priority bug.
- Open ISB jumper model.
- Zoom in on dot (light source) above skeleton. Click dot to make frame appear. Can now move light around.
- Also: now click on floor. Dragging frame that appears changes height of floor but Floor>height value in Controls menu is not updated.

opensim4.0PreviewWin64_0717.zip

**Comment by aymanhab** [comment]
Made model light uneditable. If we can reproduce floor dragging, please describe steps otherwise I suggest closing

**Comment by tkuchida** [comment]
Unable to reproduce in AppVeyor artifact OpenSim-4077dd7b-2018-03-29.zip.

**Comment by jenhicks** [comment]
Should we verify the model light is uneditable?

**Comment by aymanhab** [comment]
Yes @jenhicks in the next build.
