### ISSUE TITLE
Windows aren't properly packed on maximize/restore

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#320]
- open the GUI
- double-click the Coordinates tab to maximize
- double-click the Coordinates tab again to restore

![windows](https://user-images.githubusercontent.com/4203505/28383987-e1cdb00a-6c77-11e7-94e4-a9f1ac03bd14.png)

opensim4.0PreviewWin64_0719.zip
Related: #308

**Comment by jimmyDunne** [comment]
Confirmed fixed on W10.
Build:04-27-2018
