### ISSUE TITLE
Model does not always visualize when opening

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#322]
To reproduce (on my mac):
- Launch OpenSim
- Load a Model
- Do something to create an error (like plot before IK) or play a motion back on loop 
- Close the GUI 
- Relaunch OpenSim

This also happens sporadically for other reasons. Sometimes closing the embedded visualizer window and reopening helps. Sometimes I need to launch the view in browser to get the model to show up.

**Comment by jenhicks** [comment]
@aymanhab Was this reported at all in the latest testing? If not, we could probably close unless it recurs.

**Comment by aymanhab** [comment]
Not that I know of. If neither Chris, Tom or Ajay saw it I would be very
comfortable closing. There was a separate issue with Experimental data that
was also fixed but not to be confused with this one.
