### ISSUE TITLE
arm26 and other models can take >20 seconds to load

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#329]
- open ISB jumper model
- use "running dude" to run a 1-second simulation
- close model
- open arm26.osim model; the floor reappears after ~3 seconds, the model appears ~21 seconds later

opensim4.0PreviewWin64_ISB4.zip

**Comment by aymanhab** [comment]
@jenhicks Can you clarify if this is application startup, opening first model ever in session, or generically. I haven't noticed much difference in startup time on my (relatively souped up but not very high-end machines) neither running native windows or native Mac, though @tkuchida has reported similar issue very early on, on Windows. Would be good to get an update from you @tkuchida @aseth1 @chrisdembia and @jimmyDunne

**Comment by jenhicks** [comment]
The first time I load a model it takes 10-15 seconds for the model to show up in both the navigator and visualizer window. For subsequent models it's about 5 seconds. I was just the jumper model from the ISB example on my Windows 10 VM

**Comment by tkuchida** [comment]
On antique Windows laptop with AppVeyor artifact OpenSim-0d41eef3-2018-03-14.zip:
- OpenSim starts in 11 seconds
- opening model: floor appears after 6 seconds, model appears 2 seconds later
- close
- opening model again: appears after 3 seconds

Tested with `Models\Gait2392_Simbody\subject01.osim` from the models repo.
