### ISSUE TITLE
Preview Experimental Data works for Markers OR Forces

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#339]
@aseth1 commented on [Wed Jul 19 2017](https://github.com/opensim-org/opensim-core/issues/1836)

As separate motion previews.  When attempting to sync motions, markers/forces disappear but the motion player time keeps advancing.

Additionally, making either data file current, afterwards, fails to display the current markers or forces data.

---

@aseth1 commented on [Wed Jul 19 2017](https://github.com/opensim-org/opensim-core/issues/1836#issuecomment-316573242)

Interestingly it just worked on Mac, but not on Windows 10.

---

@jimmyDunne commented on [Tue Jul 25 2017](https://github.com/opensim-org/opensim-core/issues/1836#issuecomment-317881235)

@jenhicks can you please move this to GUI. Three engineers and I couldn't figure it out.

**Comment by aseth1** [comment]
I was not able to preview both forces and markers at the same time. In the previous version, loading the second set of data would cause to first to disappear (which was not ideal) but synching the motions then made both visible. In OpenSim b435c8f-2018-07-06 on Mac this no longer works.

**Comment by aseth1** [comment]
Seems to work if I load forces first. The behavior is not consistent.

**Comment by aseth1** [comment]
I reproduce the issue if I have no model loaded, preview markers then forces and then after synching motions I only see forces.

**Comment by aseth1** [comment]
The issue sporadically occurs even if the model is open and it happened to me during the second demo at WCB.

**Comment by jenhicks** [comment]
Looking at the jumper from WCB
Test 1
Preview markers 
Preview forces (markers disappear)
Sync both, I see both

Test 2
Swap the order (forces loaded first, then markers)
Behavior is the same.

Test 3
Repeated Test 1, with a model loaded ... behavior is the same.

I can also toggle between making markers and forces visible by selecting which is the current "model".

**Comment by aseth1** [comment]
Repeated @jenhicks tests with running data from Apoorva's model analysis.
All worked including syncing with animated model (e.g. from CMC states).
