### ISSUE TITLE
The socket_<name>_connectee_name property should not be shown

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#344]
Because the `Socket`s are already being listed below the *Properties* (under *Sockets*) where a Socket's dependency can be satisfied by an existing Component in the Model via a pull-down list. For example, a `Joint`'s *parent_frame* `Socket<PhysicalFrame>` provides a pull-down of available `PhysicalFrames` in the model that enables the user to edit the dependency (that guarantees validity) so having the `socket_parent_frame_connectee_name`  property visible and editable (as a string) is redundant, confusing and more error prone.

The property in this case is required to save/serialize the Socket's setting.

**Comment by aymanhab** [comment]
Verified, no socket related entries under Properties and change of Frame dropdown causes proper effect of changing joint frames (on Windows)

**Comment by jenhicks** [comment]
Is this issue affected by current work on frames? I tried changing a frame in the property editor for the ankle joint in the Hamner 2010 model:
https://simtk.org/frs/?group_id=516

OpenSim crashed.
[hs_err_pid4616.log](https://github.com/opensim-org/opensim-gui/files/1794795/hs_err_pid4616.log)

**Comment by aseth1** [comment]
This issue has been fixed on Windows.

@jenhicks this was crashing prior to the Frame fixes. It still crashes because the GUI is failing to restore the state on the model. It cannot do that when the topology has changed. It shouldn't be treating Socket changes as ordinary property edits. Sockets are specifically used to change topology. This is another issue, I'll open one.

**Comment by jenhicks** [comment]
Sounds good. Thanks @aseth1
