### ISSUE TITLE
Some machines give error message that their graphics card does not support WebGL

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#355]
This seems to happen for both older PCs and Windows. 

- Need to determine and document which machines are supported. Ayman also suggested that we could create a test webpage for people to test their set-ups

- There are some cases where reconfiguring the graphics card set-up might fix the issue. I can reproduce on my husband's laptop, so could give it a try there.

- Currently the error message shows what I'd expect are clickable links, but the text has no actual hyperlinks.

**Comment by aymanhab** [comment]
@chrisdembia I have created a branch on the threejs module to upgrade to recent three.js r91 which is more tolerant to old hardware but debating whether I should merge the branch into master now to have a build for everybody to test cross platform or switch ci builds to use this branch temporarily (name of branch is update_threejs_r91).  Thoughts?

**Comment by chrisdembia** [comment]
@aymanhab it would be good if the master builds were treated as mostly tested and working. 

I've created a branch that attempts to create an AppVeyor build using the `update_threejs_r91` branch of `three.js`: https://github.com/opensim-org/opensim-gui/compare/appveyor_threejs_r91

**Comment by aymanhab** [comment]
Thanks @chrisdembia how do we get the build to @jenhicks and others to give it a spin before merging?

**Comment by chrisdembia** [comment]
The `appveyor_threejs_r91` branch is not meant to be merged. The artifact is available on AppVeyor: https://ci.appveyor.com/api/buildjobs/67ks3w3eyq4oto2u/artifacts/OpenSim-ba958aac-2018-04-30_threejs_r91.zip

**Comment by aymanhab** [comment]
Thanks Chris, I'll upload for others to try

**Comment by chrisdembia** [comment]
You shouldn't need to upload it; the ZIP should be accessible by anyone (we changed opensim-gui to a public appveyor project).

**Comment by jenhicks** [comment]
I'm working from home today ... let me know if you would like me to test anything on my husband's laptop.

**Comment by aymanhab** [comment]
Thanks @jenhicks Based on @jimmyDunne testing, animation playback is choppy likely because rendering is a bit slower though profiling is needed. We need to decide if gaining unknown number of machines would justify the slowdown, investing time on profiling or keep this open and make a separate build for those with legacy machines.

**Comment by modenaxe** [comment]
I don't know if this is useful, but I had the same issue the other day after installing OpenSim 4 (2018-08-27 executable) in a windows 7 (ultimate, sp1) virtual machine (VirtualBox) on my laptop running Ubuntu 18.04.
