### ISSUE TITLE
[Mac] Help users create symlink to OpenSim's bin dir

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#356]
Some users might like to have `OpenSim` (the GUI) or `opensim-cmd` on their path. We can help them do this with one of the following methods:

1. Add a step to the installer that creates a symlink in `/usr/local/bin`.
2. Add a menu option in the GUI (maybe under Edit or Help) for "Install command line tools." CMake does this, as do other developer-oriented apps.

I'm not sure (1) is actually possible.

**Comment by chrisdembia** [comment]
I prefer option (2) above.

**Comment by aymanhab** [comment]
I prefer option 2 but have some concerns:

- Will this be available on Mac/osx only?
- What permissions does the user running OpenSim have? This may open a can of worms if they can't  create the links and the uninstall becomes more involved.

**Comment by jimmyDunne** [comment]
Why can't Mac users add the bin folder to their bash/zshrc file? I have this setup for my local build 

```
# Export opensim path in .zshrc
path=('/Users/jimmy/repository/opensim-source/install-opensim/bin' $path)
```

**Comment by chrisdembia** [comment]
That is another option, though then the command-line tools are only available on the PATH when using the shell that's configured. Also, users may use different shells.

Mostly, I am just trying to follow the example of other software. CMake and the Jetbrains IDEs use symlinks.

The issue about permissions is valid; we can use `sudo` if the command fails without `sudo`, and the system will simply prompt the user to enter their password.

**Comment by chrisdembia** [comment]
Perhaps we should just add instructions to Confluence and not automate anything.

**Comment by aymanhab** [comment]
Prefer improving documentation for the few users needing command line access over making broad changes to application used by a lot more users.

**Comment by jenhicks** [comment]
Here's the page where we should improve documentation:
https://simtk-confluence.stanford.edu/display/OpenSim/Command+Line+Utilities

@aymanhab You might take a look at this if you have time. There is some material on this page that could be helpful:
https://simtk-confluence.stanford.edu/display/OpenSim/OpenSense+-+Kinematics+with+IMU+Data#OpenSense-KinematicswithIMUData-InstallingOpenSense

**Comment by aymanhab** [comment]
@jenhicks Updated here 
https://simtk-confluence.stanford.edu/display/OpenSim/Command+Line+Utilities
Let me know what you think. Thanks

**Comment by chrisdembia** [comment]
I made some changes. 

Note that macOS Catalina changes the default shell to `zsh`, not `bash`. I wonder if the instructions must be different for zsh. @jimmyDunne

**Comment by jenhicks** [comment]
Can you guys provide me with detailed instructions on how exactly I should test the new version? Thanks!

**Comment by jenhicks** [comment]
(In particular what I should delete from any previous set-ups and how I should run the script).

**Comment by aymanhab** [comment]
You should 
1. remove all references/links to opensim-cmd or opensense from /usr/local/bin, make sure opensim-install-dir/bin is not on your Path
2. Run the shell script from <opensim-install-dir>/bin 
3. Check that links are created in /usr/local/bin for opensense and opensim-cmd
4. Run opensense from any arbitrary directory on your machine

**Comment by jenhicks** [comment]
> make sure opensim-install-dir/bin is not on your Path

Can you remind me how to do this one?

**Comment by chrisdembia** [comment]
In a terminal, you could type `echo $PATH`, which lists the directories on your PATH.

**Comment by jenhicks** [comment]
Thanks. I can confirm that the new shell script worked for me. We need to add the directions back to the confluence page. I updated the instructions on confluence and would appreciate if someone gave them a quick review:
https://simtk-confluence.stanford.edu/display/OpenSim/Command+Line+Utilities

**Comment by chrisdembia** [comment]
Looks good to me! I made one minor change (fixed the file extension).
