### ISSUE TITLE
Where should models, geometry, and other assets be installed?

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#358]
This has come up because it's not clear that, on Macs, models, geometry, and example scripts belong inside the `/Applications/OpenSim...` folder. We have previously discussed potentially putting these resources/assets in `~/Documents`.

Some thoughts from #26:

> Geometry & Models now live in top level, could go into Assets folder or follow layout per James or ...
 We need to decide if assets are kept read only or hidden from users and they need to make a copy to modify Scripts, should they go with assets or into sdk folder along with API programs?

We should also consider consistency between Macs and Windows.

**Comment by aymanhab** [comment]
@chrisdembia Do you think this should be figured out before public Beta?

**Comment by chrisdembia** [comment]
Getting this right might require some user testing, so perhaps it would be ideal to include this in the beta but I feel like that would delay the beta too much. My sense is that this would take some time to implement, and I think there is still some discussion required to figure out the right way to do this.

**Comment by aymanhab** [comment]
Agreed. I think we should try the beta with what we have now until we find out the shortcomings so we have a good sense of the issues involved. I'll remove the Beta label but leave as 4.0 milestone if you agree.

**Comment by chrisdembia** [comment]
Sounds good.

**Comment by aseth1** [comment]
*\<users home\>/Documents/OpenSim 4.0*
- Models
- Scripts (Matlab, Python, GUI)
- API examples
- plugins (?)

*\<App folder\>*
- Python package
- SDK (include and libs) (symlink sdk/doc)
- Geometry

**Comment by aymanhab** [comment]
I'm making the change now so that:
1. The default directory is Documents/OpenSim/version (this will reduce clutter of the file system)
2. If the folder for the version exists then user is prompted to re-enter.
3. Not sure if layout needs to change as above (as of now it's Models, sdk/Scripts, sdk/APIExamples) Any thoughts? @chrisdembia @aseth1 @tkuchida

**Comment by tkuchida** [comment]
> Any thoughts?

I will want to specify a non-default location, so I'd be satisfied as long as #467 is fixed. Is there an install.log file listing the destination of each file that was copied? I didn't realize the sdk/Scripts and sdk/APIExamples were also redirected by the dialog on first launch.

**Comment by aymanhab** [comment]
That didn't happen in previous builds @tkuchida I'm making the fix now, and yes #467 fix is already included.

**Comment by chrisdembia** [comment]
I like the idea of `Documents/OpenSim/version`. I would prefer to not have `Scripts` and `APIExamples` in `sdk`.  Ideally the files will have the same organization on Mac and Windows.

**Comment by chrisdembia** [comment]
This might mean rearranging the organization of the `opensim-core` installation.

**Comment by aymanhab** [comment]
Since this is a cross repository issue that may take a while to propagate, I'll merge this change and address  feedback afterwards.

**Comment by aymanhab** [comment]
I agree we should rearrange these folders in opensim-core installation and make copying the resources work cross-platform (without changing the layout during copy to avoid confusion, complicated documentation)

**Comment by aymanhab** [comment]
Fixed by PR #504, verify and close on next Mac build

**Comment by jenhicks** [comment]
This is fixed on my mac ... closing
