### ISSUE TITLE
[macOS] Clean up mac packaging script (make_macOS_pkg.sh).

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#359]
I created a shell script that uses `pkgbuild` and `productbuild` to build a macOS installer (PKG file). Perhaps we should turn this script into a CMake custom target?

The current plain shell script is not great, because the version number is hardcoded, and because the resulting PKG is placed into the repository (making it easy to accidentally commit the file).

**Comment by jenhicks** [comment]
Or please close @chrisdembia if this is done.

**Comment by chrisdembia** [comment]
We can close this issue. However, there are currently two hacks in the mac installer script (https://github.com/opensim-org/opensim-gui/blob/master/Installer/macOS/scripts/postinstall). These hacks are to address the following issues:

-https://github.com/opensim-org/opensim-gui/issues/194
- https://github.com/opensim-org/opensim-gui/issues/251 (only closed b/c of the hack)
