### ISSUE TITLE
Add Geometry to a body within the GUI via scripting: share example

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#366]
@aymanhab just brought this up in the dev meeting today. This would be a way to ease into model building.

**Comment by aseth1** [comment]
Although this is marked as future release adding a Body via XML has become more challenging (@carmichaelong and others) so we need a way to add a Body, PhysicalOffestFrame, and Joint easily. One way to do that is via scripting.

I was able to use this to add to leg6fog9musc repeatedly without any issues or failures.
[AddPhysicalOffsetFrame.py.txt](https://github.com/opensim-org/opensim-gui/files/1795422/AddPhysicalOffsetFrame.py.txt)

@aymanhab you might want to use it in testing and @jimmyDunne please use this as a basis for updating the "model editing" tutorial and feel free to change it to make it more user friendly.

**Comment by jenhicks** [comment]
Moving this to the 4.0 example so we have a way to track the update to the example.

**Comment by aymanhab** [comment]
Based on workshop plans, should we include this script in the distribution? @jenhicks @jimmyDunne @aseth1

**Comment by jenhicks** [comment]
Issue moved to [opensim-org/opensim-core #2144](https://github.com/opensim-org/opensim-core/issues/2144) via [**ZenHub**](https://www.zenhub.com/)

**Comment by aseth1** [comment]
Since the script should live with the GUI Scripts, I think the issue should reside here.
