### ISSUE TITLE
Do we need to support 32 bit Windows?

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#375]
With OSX support, introduction, we have 2 platforms to test/ship, do we still need to create/test Windows 32 bit distributions? Opinions, thoughts are appreciated. Main likely scenario would be some users with 32 bit Matlab. Per Mathworks R2015b is the last version to ever support 32 bit on Windows
https://www.mathworks.com/matlabcentral/answers/271876-windows-32-bit-version-is-not-availble-for-2016a?

**Comment by aymanhab** [comment]
I think this can be closed as long as we document what we agreed upon.

**Comment by chrisdembia** [comment]
In the dev meeting last week, we agreed to have AppVeyor build and test "Visual Studio 14 2015 Win64" and "Visual Studio 15 2017 Win64," and to not test or distribute 32-bit binaries.

**Comment by tkuchida** [comment]
![](https://user-images.githubusercontent.com/4203505/35831080-6053cd26-0a7d-11e8-862f-521af1f47077.png)

**Comment by chrisdembia** [comment]
hahah
