### ISSUE TITLE
If path point is added, muscle geometry is not cleared when model is closed

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#379]
### Steps to reproduce
- open leg6dof9musc.osim
- in Navigator panel, select Forces > Muscles > soleus_r
- in Properties panel > Properties tab, click "…" beside GeometryPath
- click Add > between 1 and 2, then Close
- close model

### Expected result
Visualizer Window is cleared.

### Result
The muscle geometry remains in the Visualizer Window.
![lingeringmuscle](https://user-images.githubusercontent.com/4203505/30528454-1a7a9dd8-9be8-11e7-9e22-64f5e3965645.png)

Version "OpenSim-4.0.Beta_082917_Win64.zip"

**Comment by aseth1** [comment]
@tkuchida will verify

**Comment by tkuchida** [comment]
Verified fixed in AppVeyor artifact OpenSim-2fd23ef3-2018-02-20.zip :checkered_flag:
