### ISSUE TITLE
Need to update GUI license that appears in the installer.

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#394]

**Comment by aymanhab** [comment]
@chrisdembia Can this be closed or moved to Need verifying based on the auto generated builds? Also do we need to change again to include reference to JxBrowser? Thanks,

**Comment by chrisdembia** [comment]
This cannot be closed yet, as #412 is not yet merged.

> Also do we need to change again to include reference to JxBrowser? 

This is what we say in #412 for the mac installer:

> OpenSim includes a number of subcomponents with separate copyright notices and
license terms. Your use of these components is subject to the terms and
conditions of their respective licenses, which can be found in the LICENSE.txt
and NOTICE.txt files in the installation (<.app>/Contents/Resources/OpenSim).

I'm fine with adding the JxBrowser note here.

I'm not sure how to address this issue for the Windows build.

**Comment by aymanhab** [comment]
As of now the Windows build does not have an installer, just a zip file so the Notice file should be enough. If/when we create an installer we'll point it to the same file. Will leave open until we decide on windows installer.

**Comment by aymanhab** [comment]
@chrisdembia I think this can be closed since #412 has been merged.
