### ISSUE TITLE
Items under "Display" in context menu have no effect for experimental data

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#397]
### Steps to reproduce
- open Models\Gait10dof18musc\subject01.osim from 3.3 distribution
- File -> Preview Experimental Data…, select Models\Gait10dof18musc\ExperimentalData\subject01_walk.trc
- right-click ExperimentalData_0 in Navigator panel; Display->Show, etc. have no effect

opensim4.0PreviewWin64_0929.zip

**Comment by jimmyDunne** [comment]
For experimental data open in the navigator, the context menu for 'hide' and 'show' do not do anything. 'show only' works, and will make other models or data disappear. (The video capture method I am using doesn't show the context menus)

If I hide any markers individually, then go to the top level and select 'show', the hidden ones don't reappear. If, on the top level, you select 'show' or 'hide', it should have that effect on all markers. 

![markers_hide](https://user-images.githubusercontent.com/5296507/38648549-51fb3ed4-3de1-11e8-8f60-7b25bf907ed6.gif)

Windows 10
opensim-04-11-2018

**Comment by aymanhab** [comment]
showOnly on a model will hide other models
operations on top level model used to visualize data operate on the whole model without changing the user preferences/choices underneath it (that was the bug in issue #522 and #644)
Somewhere else there was a report that the functionality works for hide/show/showOnly. 😕 
Behavior is essentially the same as in 3.3 unless there's a specific unexpected behavior
