### ISSUE TITLE
The IDTool run in the GUI should not produce a motion file

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#4]
The inverse dynamics solver and the Tool in the API only consume motion/storage files so how and why does the GUI produce the "Results"? Also the file is an incorrect representation of the original and can lead to grossly different results if the file is used downstream for another Tool (see #3).

**Comment by alouiii** [comment]
> @jenhicks Indeed this is the "input" motion and not an output and it's loaded from file if motion file is specified. It's convenient 

Could you please then rename it to `IDInputMotion` or something similar? Because the current default name `IDResults` is very confusing. Thanks!
