### ISSUE TITLE
Editing joint parent frames throws exception

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#402]
Need to handle or disable editing option for 4.0

**Comment by aseth1** [comment]
@aymanhab in tracking issues and understanding how they are handled it would be very helpful if we adopted a standard of listing the PRs in progress and merged that fix the issue. It is strange to see an issue move from Backlog to needs verifying with not a single reference to a PR (when in progress) or the commit that fixed it so the issue can be closed,

**Comment by aseth1** [comment]
Editing the parent frame Socket still crashes the GUI see #587 and #529
