### ISSUE TITLE
Mouse features

### ISSUE THREAD

**Issue by bspineda** [opensim-org/opensim-gui#405]
Some of the Mouse controls do not work the same as described for OpenSim 3.3. For example, in the "Viewing & Animating a Model" section, it says that "OpenSim allows you to orient the model using your mouse".

Then it says: "To translate the view, click and hold the **center mouse button** and drag the mouse". This part is no longer correct, when you click and hold the **center mouse button**, nothing happens.

Another example:
"To zoom, click and hold the **right mouse button**.
 To zoom, drag the mouse down. To zoom out drag the mouse up." 
Now when you click the **right mouse button**, you cannot longer zoom in or out. When you click and hold the **right mouse button** and drag it up or down, you are just moving the model, not zooming in or out.
To zoom in or out now, you will need to click and hold the **center wheel button** (this is the type of mouse that I am using), and just roll the wheel up and down.

**Comment by aymanhab** [comment]
Thanks @bspineda Will need to update the tutorial/documentation accordingly. The follow up question is whether the current (undocumented controls) are satisfactory. Also note that up to 3.3 we din't have mac support (which can have a trackpad but no mouse wheel).

**Comment by jenhicks** [comment]
Here is some documentation we wrote for a tutorial we did at ISB. @bspineda Do these controls work for you? You could make corresponding edits to the documentation and tutorials for 4.0, where appropriate.


Rotate | To rotate the view, left-click and hold (PC or mouse) or single-finger click and hold (Mac trackpad) in the Visualizer window and drag the cursor.
-- | --
Translate | To translate the view, right-click and hold (PC or mouse) or two-finger click and hold (Mac trackpad) in the Visualizer window and drag the cursor.
Zoom | To zoom in or out, scroll up or down in the Visualizer window with the mouse or trackpad. Alternatively on a trackpad, pinch or expand.

**Comment by jimmyDunne** [comment]
Shouldn't the 4.0 GUI controls be the same as the ones in 3.3? I know most people won't be switching between GUI versions, but doing so at the moment is very confusing as the control layout is different.

**Comment by jenhicks** [comment]
Ah, so there are differences between mac 4.0 and windows 4.0, as well as differences between windows 4.0 and windows 3.3?

@aymanhab can you comment more on why there are differences between windows 4.0 and windows 3.3? 

People have said that the rotate/translate/zoom controls in previous versions of OpenSim weren't very intuitive ... scrolling up/down to zoom does seem like an improvement.

**Comment by aymanhab** [comment]
Generally speaking we don't do much customization of the controls because that's reinventing the wheel and we don't have the bandwidth in development or testing to develop our own. The controls in 3.3 have been less than ideal and were windows focused. Trying to reproduce in a new world that supports Mac (no mouse, possible one button trackpad, and touchscreen etc.) would be unnecessary step back in my opinion.  The new controls (out of three.js which caters to more graphics, modeling, gaming oriented crowd) are more intuitive, requested specifically by some users (e.g Thomas) and were never an issue since the first Alpha of 4.0 was published. I understand @jimmyDunne frustration with switching back and forth but that's an unlikely long term issue IMHO.

**Comment by aseth1** [comment]
I find the trackpad controls on a Mac to be a big improvement over 3.3 in Windows with a mouse. I can:
1. click-drag to rotate (tumble) the (horizontally to rotate about a vertical axis of my and up/down to rotate about a horizontal axis.
2. two-finger drag (pull) to zoom in and (push) to zoom out
3. two-finger click-drag to translate in the current plane-of-view

The main difficulty/issue, as we saw with Ashley, is achieving a precise rotation about a desired axis that isn't aligned closely to a world principal axis. Also the rotations seem to be artificially bounded, where you can only rotate to a fixed extent (i think 180 degs).
