### ISSUE TITLE
Model Display Issues: show/hide muscles for tutorials

### ISSUE THREAD

**Issue by bspineda** [opensim-org/opensim-gui#406]
For both MAC and PC
Mac build - OpenSim-4.0.Beta_0930_Mac.pkg
PC build - opensim4.0PreviewWin64_0929.zip

1) When you first load the model (from Tutorial 1) for both the MAC and PC, the loaded model is cut in half, only the upper body shows (see image example). This is different from 3.3 for when you load the model in 3.3, the whole body model shows. However, once you start clicking the six orienting icon, then the whole model shows.
![image](https://user-images.githubusercontent.com/32551585/31288259-fea58830-aa78-11e7-89bd-6a69e2439768.png)
This same issue happens when loading the wrist model from Tutorial 2, the model loads partially.

2) When you first load the motion **normal_gait** in the **GaitModel2392**, the upper body of the model goes out of view. You will need to click an orientation icon to bring the whole model back in view.

3) When you click **play** in the **Motion Slider**, the model does not move at all.

4) When displaying muscles in the "Muscles Path" section of Tutorial 1, these did not work well. On the PC, the visualizer window went black I tried to **Display > Show** or **Display > Hide** all the muscles. On the MAC, when I did **all, Display > Show**, the muscles showed, however, immediately  after my MAC started working hard in the background and everything went super slow (rainbow wheel). The visualizer also turned blank. I had to quit OpenSim.

5) Tutorial 2 
![image](https://user-images.githubusercontent.com/32551585/31289841-1b4dfe9e-aa7f-11e7-977a-f3e54eac0916.png)

**Comment by jenhicks** [comment]
Thank you @bspineda for the detailed report

Comment 1: Issue is filed here: https://github.com/opensim-org/opensim-models/issues/36 
Comment 2: I think that fixing Comment 1 will address Comment 2
Comment 3: I think this is related to Issue #283 (we're replaying old-style IK results)
Comments 4 and 5: @aymanhab do we have an issue for the display/show problems?

**Comment by aymanhab** [comment]
There are two issues (and I have a fix ) #233, #312 and another one related to performance #281 but feel free to add one more specific issue.

**Comment by jenhicks** [comment]
Thanks for clarifying. I edited the title of the issue and will leave open to make sure we test these parts of the tutorials again when the fixes are in.

**Comment by bspineda** [comment]
The models display correctly now. See issue 486 for Display > Show Only, now it is resolved as well.

**Comment by aymanhab** [comment]
Great, thanks @bspineda Feel free to close the issue then as well as any others on the Needs Verifying list to reduce the clutter. Much appreciated.
