### ISSUE TITLE
Model does not assume default pose as expected on mac

### ISSUE THREAD

**Issue by bspineda** [opensim-org/opensim-gui#407]
For both MAC and PC
Mac build - OpenSim-4.0.Beta_0930_Mac.pkg
PC build - opensim4.0PreviewWin64_0929.zip

1) For Tutorial 1, on the PC the plotter worked well following the instructions on the tutorial. But for the MAC when you click **Poses > Default**, the model goes to its default state. However, as soon as I soon as you make a click anywhere, the model automatically moves up and the right leg moves. So when you do the plots, the MAC and PC plots look different. See image explaining what I mean.
![image](https://user-images.githubusercontent.com/32551585/31289418-8a3a2b2c-aa7d-11e7-8cfc-f830d0d39548.png)

2) In Tutorial 2, there is an issue with the plotting when I come to section 6. Even though the exact same procedure was followed, the plots look different on the MAC and PC. See image below.
![image](https://user-images.githubusercontent.com/32551585/31289602-283adace-aa7e-11e7-86f0-4b1fc873fe6f.png)

**Comment by jenhicks** [comment]
Thanks @bspineda 

Comment 1: I was not able to reproduce this on my Mac. What are the specific steps in the tutorial you're following there?

Comment 2: I think this may be related to some confusion/lack of detail in the instructions at this line:
To clear the muscle selection list, click the deselect all shown check box.
Filter the ulnar deviators group and click the select all shown check box.

It looks like in one of the cases there were still some muscles selected from another muscle group when you selected the ulnar deviators. I believe you need to click the "Show all" button in the Muscle selection control panel, before you click to deselect all shown.

@aymanhab Is the behavior of the muscle selection panel different from 4.0 (vs 3.3) or different between mac and windows? As far as I can tell they are the same, so surprised this issue hasn't come up before.

**Comment by jenhicks** [comment]
On a separate note, on my mac, part of the controls in the mac are cut-off. Will file a separate issue for this.

**Comment by tkuchida** [comment]
> It looks like in one of the cases there were still some muscles selected from another muscle group when you selected the ulnar deviators. I believe you need to click the "Show all" button in the Muscle selection control panel, before you click to deselect all shown.

I think this is a user interface problem, not a problem with the instructions or documentation. In this context, I think a typical interface would display a list of all currently selected items, regardless of whether they pass through the current filter.

**Comment by bspineda** [comment]
@jenhicks replying to comment 1.
In the image below is what I did from Tutorial 1. Note that the motion is already loaded at this point. With the motion loaded is when the issue arises (as shown in the image I previously showed). If the motion is not loaded it works fine. But on the PC it works fine even if the motion is loaded.
These are the steps I followed.
![image](https://user-images.githubusercontent.com/32551585/31295547-cc7b598c-aa93-11e7-9e13-fc7b0d2f7e8e.png)

**Comment by jenhicks** [comment]
Thanks @bspineda when you saw this behavior on the Mac, had you previously tried to show/hide muscles? If you don't change the display of muscles at all and just do the following steps, does the model still move?

1) Load gait2392
2) Load normal.mot
3) Poses -> Default
4) Click anywhere

**Comment by bspineda** [comment]
Hi @jenhicks - yes, I had previously tried to show/hide muscles in my first try, then I quit OpenSim, and loaded the model and motion again without doing anything with the muscles. I still get the same issue when I do the steps you mention.
1. Load gait2392 model
2. Load normal.mot motion
3. Poses -> Default
4. Click outside the OpenSim window or when you click the Tools menu -- this is where the issue is. When I click outside the OpenSim window anywhere, or I click on the Tools menu and select the Plot or any of the other options under the Tools menu, the model automatically moves and is no longer at default. When I do the same thing on OpenSim4.0 for the PC, this does not happen, when I click outside OpenSim or click on Menu -> Plot, the model stays at default.

**Comment by jenhicks** [comment]
Thanks for testing again @bspineda 

@aymanhab Any ideas ... I still can't replicate this on my Mac.

**Comment by bspineda** [comment]
@jenhicks - for comment 2
I completed the plots again on both the MAC and PC. This time both plots are the same and I had no issues. As you mentioned, maybe it was an issue where I had selected extra muscles.

**Comment by jenhicks** [comment]
Thanks for clarifying @bspineda 

I agree with @tkuchida that the interface is confusing. But if behavior is the same as 3.3, I am hesitant to make changes until post-4.0, given our timeline and other to-do tasks for the release.

**Comment by aymanhab** [comment]
Agreed, in the mean time proposals for improvements/revamps can be maintained and discussed on a separate issue but not a top priority.

**Comment by jenhicks** [comment]
I've updated the title of the issue to reflect the problems with getting the model to assume the default pose. @aymanhab do you need any more info to troubleshoot this?

**Comment by aymanhab** [comment]
Thanks @jenhicks and @bspineda I didn't get around to test that but I have all the info I need to try. Will let you know if I need further details. Thank you.

**Comment by aymanhab** [comment]
The problem here boils down to inconsistency where the motion slider shows a motion (and associated state) and that stays intact even when you apply a pose which is usually inconsistent with the motion. I'm testing a fix where setting a pose causes the current motion to be unloaded. The user can go back and make the motion current if needed but that at least should take care of the issue at hand. 
The fix is done by introducing a "mode" (Modeling or Analysis)" and setting a pose transitions from "Modeling" (default) to "Analysis". Relevant discussion here #498 
Wanted to get feedback from a user before I finalize the implementation. Thanks
