### ISSUE TITLE
Custom info.plist and opensim.conf files per platform

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#41]
Default files created by Netbeans are less than perfect for branding purposes. The following changes needed as reported by @chrisdembia 
Info.plist to include case correct name of application (OpenSim) rather than opensim
Info.plist special flag to handle hires retina display 
opensim.conf file needs to specify dynamic library paths to open the app by double click
opensim.conf on windows need special flags (as in OpenSim 3.3 to handle memory management etc.)

**Comment by chrisdembia** [comment]
Verified.
