### ISSUE TITLE
[AppVeyor] Automatically set userdir to use commit hash and date.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#416]

**Comment by jenhicks** [comment]
Closing since @aymanhab believes this is done .. please feel free to re-open, if not

**Comment by chrisdembia** [comment]
This is done for Travis, but not yet for AppVeyor. See [here](https://github.com/opensim-org/opensim-gui/blob/master/appveyor.yml#L57).

**Comment by aymanhab** [comment]
Don't know if this works for windows

**Comment by jenhicks** [comment]
@aymanhab thinks this is fixed since we now automate the build. Please reopen if not.

**Comment by chrisdembia** [comment]
Yes this is fixed. Thanks for closing.
