### ISSUE TITLE
Remove extra windows/menus/options (Services, Module Manager)

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#420]
Not clear what that searches, and is an inconsistency between Mac. Windows.

**Comment by chrisdembia** [comment]
I like this search box. You get it with every mac app and it searches the menu bar drop downs.

**Comment by tkuchida** [comment]
@chrisdembia So you *find* it useful?

**Comment by aymanhab** [comment]
Thanks for the feedback @chrisdembia we have to balance what OSX users expect vs. the divergence of documentation/functionality. Would be good to get your input on other Mac specific items (will list these based on report by @bspineda).

**Comment by jenhicks** [comment]
Search - Leave this

Services -> Preferences - see if we can rewire to use the bring up the same menu as edit -> preferences. Otherwise leave it

Tools -> Plugins - remove this
