### ISSUE TITLE
[AppVeyor] Automatically set icon for exe using ResourceHacker.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#425]
http://www.angusj.com/resourcehacker/
http://wiki.netbeans.org/DevFaqExecutableIcon

**Comment by chrisdembia** [comment]
There's a choco package `resourcehacker.portable` but it gives an error about the md5 hash not being valid.

**Comment by chrisdembia** [comment]
I would definitely like to figure this out but I'm not sure this belongs in the 4.0 milestone, because @aymanhab will likely create the official release locally, not using AppVeyor.

**Comment by chrisdembia** [comment]
@aymanhab this is done, correct?

**Comment by aymanhab** [comment]
Yes

**Comment by chrisdembia** [comment]
Thanks for confirming.
