### ISSUE TITLE
Models with ExpressionBasedBushingForce don't display/render

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#427]
I'm working on a figure for the OpenSim 4.0 paper.

When I open Matt DeMers' drop jump model in 4.0 on Mac (version 0c9442d-2017-10-26), I get the following exception: 

```java.lang.NullPointerException
	at org.opensim.threejs.ModelVisualizationJson.createJSONObjectFormDisplayGeometry(ModelVisualizationJson.java:316)
	at org.opensim.threejs.ModelVisualizationJson.addtoFrameJsonObject(ModelVisualizationJson.java:303)
	at org.opensim.threejs.ModelVisualizationJson.processDecorativeGeometry(ModelVisualizationJson.java:271)
	at org.opensim.threejs.ModelVisualizationJson.processDecorationsForComponent(ModelVisualizationJson.java:184)
	at org.opensim.threejs.ModelVisualizationJson.createJsonForModel(ModelVisualizationJson.java:174)
	at org.opensim.threejs.ModelVisualizationJson.<init>(ModelVisualizationJson.java:137)
	at org.opensim.view.pub.ViewDB.getJsonForModel(ViewDB.java:1762)
	at org.opensim.view.pub.ViewDB.update(ViewDB.java:421)
	at java.util.Observable.notifyObservers(Observable.java:159)
	at org.opensim.view.pub.OpenSimDB.addModel(OpenSimDB.java:153)
	at org.opensim.view.pub.OpenSimDB.addModel(OpenSimDB.java:141)
	at org.opensim.view.FileOpenOsimModelAction$2.run(FileOpenOsimModelAction.java:98)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Seems to be this line:
```
 obj_json.put("material", uuid_mat.toString());
```

Note that the model appears in the Navigator, but does not visualize:

 
<img width="1108" alt="screen shot 2017-11-01 at 5 17 51 pm" src="https://user-images.githubusercontent.com/846001/32303869-9e770a3c-bf28-11e7-8025-20b39b4dbdb1.png">

Here's the model: 
[model_04-optimized_level_landing_with_no_controllers_smoothmesh_twosurfs_4.0.osim.zip](https://github.com/opensim-org/opensim-gui/files/1436084/model_04-optimized_level_landing_with_no_controllers_smoothmesh_twosurfs_4.0.osim.zip)

**Comment by chrisdembia** [comment]
I can avoid that ecxeption by removing all forces from the model.

**Comment by chrisdembia** [comment]
I then get an error about `hat_ribs_scap.vtp` not being ASCII. Do we have a replacement for this file yet?

**Comment by chrisdembia** [comment]
I'm pretty sure this has to do with ExpressionBasedBushingForces. If I take these EBBFs out of the model, it shows up in the GUI just fine (if I use non-binary vtp files). The issue seems to be on the GUI side, because the simbody-visualizer is able to visualize the EBBFs:

![visualizemodel_1](https://user-images.githubusercontent.com/846001/32584260-48d874ce-c4ac-11e7-9933-3bcd85f2570e.png)

(the bones don't show because I didn't set OPENSIM_HOME).

The EBBF attempts to draw two DecorativeFrames and two DecorativeCylinders.

**Comment by aymanhab** [comment]
I get missing mesh files, where did you get them, @chrisdembia ?

**Comment by chrisdembia** [comment]
[Archive.zip](https://github.com/opensim-org/opensim-gui/files/1456253/Archive.zip)

Oops. See attached.

**Comment by aseth1** [comment]
@aymanhab I am using the [latest build](https://www.dropbox.com/home/DevBuilds/frameEditBuild) with FrameEditing fix.

I am still unable to run.
![image](https://user-images.githubusercontent.com/6494122/37177310-e69b9e4a-22d3-11e8-9b4f-390b1f00f99b.png)

The inability to load the mesh seems wrong since you can see the mesh in the Visualizer with the correct filename in the Mesh's properties.

**Comment by aymanhab** [comment]
Agreed @aseth1 If you have a separate model with ExpressionBasedBushing then close this one and open issue related to Contact mesh files. My sense is that when we run FD we make a copy of the model, that copy has no sense of the directory where the model came from and so it fails to find the mesh file. Will need to try ideally with a simple model that has mesh file.

**Comment by jimmyDunne** [comment]
System W10
build: OpenSim-dbbbb0c5-2018-04-16.zip

Opening model in 4.0; 
![model_in_40](https://user-images.githubusercontent.com/5296507/38879088-5abc14aa-4217-11e8-97d8-b8d18c041bbb.png)

Opening the model in 3.3;
![model_in_33](https://user-images.githubusercontent.com/5296507/38879070-4f4adac0-4217-11e8-9496-478060fdaa8a.png)

**Comment by aymanhab** [comment]
Model now opens and shows as in 3.3. But bushing force doesn't show up, not a show stopper but worth investigation.

**Comment by jimmyDunne** [comment]
Nothing appears in the visualizer when opening the model. 

![expressionbasedbushingmodel](https://user-images.githubusercontent.com/5296507/40858334-dbd86162-6592-11e8-95bf-cdb564cd2f0e.png)

W10. OpenSim-cedd8d22-2018-05-31-win64.exe

**Comment by aymanhab** [comment]
ExpressionBasedBushing was using DecorativeFrame to visualize which doesn't fit the GUI workflow atm (vs FrameGeometry which works without issue). While this is detected and reported now, model visualization fails because ExpressionBasedBushing::generateDecorations requires realization to a higher stage, inconsistent with rest of model/components. This needs fixing on opensim-core side.

**Comment by aseth1** [comment]
Are you saying that we cannot visualize forces now or in the future? Your comment implies that we cannot realize to Dynamics. If we want to visualize reaction forces, we need to realized to Acceleration. I don't think the use of DecorativeFrame is the major issue, but rather that we are unable to realize the system to visualize quantities we are computing. 

I understand that during IK it does not make sense to realize to *Velocity*  or above, but during a forward simulation, the overhead of realizing to acceleration should be minimal since the integrator must do it anyways. Perhaps the motion player/displayer should have an argument for the stage it must realize the state to before drawing. For IK this could be set to *Position* and for forward dynamics this could be *Acceleration*?

**Comment by aymanhab** [comment]
This happens while trying to display the model not in simulation so realizing to Dynamics is not an option since many models are kinematics only, unless model maintains such info. In simulatiin the state passed is the same used for computation si this shouldn't be an issue.

**Comment by aseth1** [comment]
I agree that the model should not have to be realized to Dynamics to simply be opened. I can update `ExpressionBasedBushingForce::generateDecorations` to check what stage is expected before drawing forces. We could add that in the documentation for `generateDecorations` that any renderings of quantities requiring realization above `Position` should only be attempted if the passed in state has been sufficiently realized and it is up to the implementer to check.

**Comment by jenhicks** [comment]
I can load the model (from the Archive.zip link that Chris posted). It visualizes and I can use the green running dude to simulate.

Several items in the GUI have the option to display/show/hide, but the functionality is irrelevant (because the object doesn't visualize) or doesn't work:
ElasticFoundationForce
BushingForce
CoordinateLimitForce

@aymanhab Are there issues for this already or should I file?

**Comment by aymanhab** [comment]
@jenhicks There're no issues filed, we can't key on the fact that the objects doesn't have visualization to disable these options, it's just like Controllers etc. but please open issues as needed.

**Comment by chrisdembia** [comment]
I was going to try verifying this on Windows, but I was unable to first verify this on Mac. I tried opening the model I originally posted in this issue on Mac and the model did not visualize:

<img width="1173" alt="screen shot 2018-07-24 at 12 53 29 pm" src="https://user-images.githubusercontent.com/846001/43162780-f8b1bc98-8f40-11e8-9929-2b1e412deedb.png">

My original ZIP did not include necessary geometry files; you can use this ZIP for testing: 
[Archive.zip](https://github.com/opensim-org/opensim-gui/files/2225142/Archive.zip)

**Comment by jenhicks** [comment]
Peculiar. I just tried it again and was able to open the model without issue. Any ideas @aymanhab

**Comment by aymanhab** [comment]
I think the model and visualization are there just not centered. Did you try any of the default views @chrisdembia

**Comment by aymanhab** [comment]
Trying again with the latest archive I get the same blank window as @chrisdembia Please reassign to me, and move back to next up.

**Comment by chrisdembia** [comment]
> Did you try any of the default views @chrisdembia

Yes, I did.

**Comment by aymanhab** [comment]
As mentioned in Jun 4th comment above on this trail, ExpressionBasedBushingForce::generateDecorations assumes Forces are computed which is a bug that needs fixing on opensim-core side, by either realizing to desired stage or checking that stage >=Dynamics. Commenting out that block of code results in model loading without an issue.

**Comment by aymanhab** [comment]
opened https://github.com/opensim-org/opensim-core/issues/2230 to track

**Comment by aseth1** [comment]
@aymanhab which Appveyor artifact can we use to test this?

**Comment by aymanhab** [comment]
Since the fix was on opensim-core side, any artifact built after the merge should be fine. There's one that I forced today for PR 936 that should have the fix.

**Comment by nickbianco** [comment]
I tried the PR 936 build and the model didn't load, but I don't think @aseth1's change was propagated through. I looked at the API commit included on the branch for that build, and it's only dated July 11.

**Comment by chrisdembia** [comment]
Ah...[this build](https://ci.appveyor.com/project/opensim-org/opensim-core/build/7825/job/7i78ubavs7tjard9) needs to pass before the GUI will have @aseth1's fix.

**Comment by chrisdembia** [comment]
That aforementioned core build succeeded; now waiting for this GUI build to finish: https://ci.appveyor.com/project/opensim-org/opensim-gui

**Comment by chrisdembia** [comment]
The GUI build has succeeded.

**Comment by chrisdembia** [comment]
On Mac, the model visualizes in the GUI (but not the EBBFs):

<img width="284" alt="image" src="https://user-images.githubusercontent.com/846001/43671077-9b31faa0-9748-11e8-9621-3d287f2ea379.png">

Some bones are missing; that's because I didn't have the Rajagopal Geometry folder in place.

I am able to simulate the model in the GUI (green running dude) without issues. 

OpenSim 0bcf8b7-2018-08-03

**Comment by nickbianco** [comment]
![image.png](https://images.zenhubusercontent.com/5b5fce5a634ac264954e72c0/f492a82b-7114-4597-99af-04fb38d0ca46)

I'm also able to load and simulate the model with the green running dude without any issues (OpenSim  0bcf8b7-2018-08-03). My muscles are blue since I took the snapshot after simulating.
