### ISSUE TITLE
Trying to load old cmc result files do not color muscles

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#439]
Observed using Gait2392 and Chand simulation results. Fails even if the file is converted to a states file offline

**Comment by aymanhab** [comment]
This boils down to needing to call realizeDynamics to populate the color cache entry (per comments in GeometryPathy::generateDecorations), does that seem justified? @aseth1 @chrisdembia ?
Would that cause other side effects or excessively slowdown playback?

**Comment by chrisdembia** [comment]
Where would the call be?

It's weird that dynamics is necessary, because activation is a state and is available at stage Model. Perhaps generateDecorations is trying to use the activation stored in `MuscleDynamicsInfo`.

**Comment by aseth1** [comment]
Why would `realizeDynamics` cause issues on a model that was used to run CMC? If you ignore activation dynamics or use any other path type actuator, expecting dynamics to know what color it should be seems reasonable to me.

**Comment by jenhicks** [comment]
I can't tell from the discussion if this is ready to be verified or not. @aymanhab can you comment.

**Comment by aymanhab** [comment]
I have a build with a fix that I can share but I don't want to claim it's fixed and have testers spend time verifying until we have example files to test with. (e.g. any model with setup files to run CMC out of the box with activations that clearly color the muscles) to check live animation and playback from inside GUI and to load precomputed results from files). Let me know if you have these around.

**Comment by jenhicks** [comment]
If I load gait2354 and load the states file from CMC that is found in the Output reference, the muscles color as expected.

Is this what I'm supposed to be testing for this issue?

**Comment by aymanhab** [comment]
@jenhicks Becaus eof some ambiguities in issues descriptions, for each of the tools I check that:

- Runnning the tools colors the muscles as expected
- Playback of results colors the muscles.
- Load pre-made/saved results colors the muscles.

If all that works then we're golden.  I assume in this case results wee pre-made (Chand's simulations)
