### ISSUE TITLE
Changing opacity of multiple items is slow/lags

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#446]
{MAC} When geometry fails to load, the remaining pieces appear to have a low opacity. Trying to change the opacity makes the GUI hang and, after several minutes, the GUI will become responsive but nothing will have changed. 

![screen shot 2017-11-20 at 12 20 16 pm](https://user-images.githubusercontent.com/5296507/33039540-2e01cc3c-cded-11e7-90c3-4df628eb7809.png)

**Comment by aymanhab** [comment]
Check the model file to see what opacity values are stored. In general displaying one mesh has nothing to do with others since each has its own material. What do you see if the reference to binary vtp file was removed from the model altogether?

**Comment by jimmyDunne** [comment]
Yes, the opacity in the model file was set at 0.22. In the 3.3 GUI this must not be respected since the model opens with 1.0 opacity (fig 1, below). 
![Uploading Screen Shot 2017-11-20 at 1.01.21 PM.png…]()

**Comment by aymanhab** [comment]
True, thanks for confirming.  3.3 used opacity to indicate current model so it was not persistent, now it is.

**Comment by aymanhab** [comment]
Let me know if you're going to close or you think it deserves mention in release motes.

**Comment by jimmyDunne** [comment]
There are still open issues here;
(i) When I open the opacity slider it is set to 1 and not 0.22
(ii) When I select multiple bodies and adjust the opacity slider the application hangs for minutes and, when it stops hanging, the opacity is unchanged. 

I can make those into separate issues or change the name of this one?

**Comment by aymanhab** [comment]
item i is likely ok since slider has to assume one value. item ii needs more investigation as it hangs when selecting many objects.

**Comment by tkuchida** [comment]
Same issues in Dec 2017 beta:
(i) If one body is selected, opacity slider should be initialized to current opacity value. (Ideally, would also initialize to current value if multiple bodies are selected and they all have the same opacity.) Typical use case: a user is trying to fine-tune the opacity of bodies for generating an image and wants to adjust again after closing the window containing the slider. Would also be helpful to display numeric value as well, ideally in an editable textbox (e.g., if the user wants the same opacity among multiple models).
(ii) Worked when I modified the opacity of 2 bodies simultaneously, but the application hangs and eats up a CPU core when adjusting opacity of all bodies (Bodies > Display > Opacity). Opacity is unchanged when the operation is complete.

**Comment by nickbianco** [comment]
I've also experienced these issues on Windows while running the ToyDropLanding tutorial.

**Comment by jimmyDunne** [comment]
I am able to select multiple bodies and change their opacity with the same slider. There no longer is hanging. 

W10, OpenSim-cedd8d22-2018-05-31-win64.exe

**Comment by jenhicks** [comment]
> I am able to select multiple bodies and change their opacity with the same slider. There no longer is hanging.

Same for me on Mac

**Comment by jenhicks** [comment]
> (i) If one body is selected, opacity slider should be initialized to current opacity value. (Ideally, would also initialize to current value if multiple bodies are selected and they all have the same opacity.) Typical use case: a user is trying to fine-tune the opacity of bodies for generating an image and wants to adjust again after closing the window containing the slider. Would also be helpful to display numeric value as well, ideally in an editable textbox (e.g., if the user wants the same opacity among multiple models).

This is still not fixed, as far as I can tell ... I will create a separate issue.
