### ISSUE TITLE
Gait2392 Pipelines scale fails on OSX

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#448]
```
Exception:
  SimTK Exception thrown at Xml.cpp:115:
  Error detected by Simbody method Xml::writeToFile(): Failed to write to the
  Xml file 'subject01_scaledOnly.osim' with error ' (line=1, col=1)'.
  (Required condition 'saveOK' was not met.)

  In Object '<no-name>' of type ModelScaler.
  Thrown at ModelScaler.cpp:332 in processModel().
  line= 0
```
![screen shot 2017-11-20 at 12 41 29 pm](https://user-images.githubusercontent.com/5296507/33040579-5260ed30-cdf0-11e7-9a13-b50d0f41e478.png)

**Comment by aymanhab** [comment]
Can you please confirm that this is on osx? Also going over the code, it looks like the fix made earlier by @aseth1 would still try to write the files if valid names are provided in XML. Please remove these from the file and let us know if it fixes the problem. Thanks

**Comment by aymanhab** [comment]
@jimmyDunne will test if the scale works if files/models/setup are placed outside the installation folder

**Comment by aymanhab** [comment]
I did the test and got the same error even after copying the model and setup file outside the installation folder.

**Comment by aymanhab** [comment]
@aseth1 Can you please use the latest published osx build and tell us what's wrong?, probably by instrumenting some print statements on the API side? I manually copied the Models folder and changed permissions and that didn't help. Next release will copy Models and setup files to user folder so this copying will not be needed. This looks like the one of the last urgent issues that we need to address before we pass the Beta to users. Thanks.

**Comment by aymanhab** [comment]
Issue has been fixed by making all the files internally use Absolute Path so path concatenation (which leads to invalid paths if Absolute Path was specified) is avoided. Longer term we should use some built in File utilities to detect absolute/relative paths in cross platform manner.

**Comment by jenhicks** [comment]
I am able to run scale for gait2354 with the distributed setup file.

**Comment by jenhicks** [comment]
I misread the model name. I can run Scale for gait2392 as well.
