### ISSUE TITLE
Mac Navigation pop-up is non-standard

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#449]
{mac} In all mac applications, if a navigation pane is used to select or save files it looks like this (from Sublime text);

![screen shot 2017-11-20 at 1 18 08 pm](https://user-images.githubusercontent.com/5296507/33042168-bd814858-cdf5-11e7-8f5e-b1b2e6d3e68d.png)

The 4.0 GUI gives me a pane like this;

![screen shot 2017-11-20 at 1 22 25 pm](https://user-images.githubusercontent.com/5296507/33042216-db883f28-cdf5-11e7-9679-f0406a6fc14f.png)

I find this alternate selection pane a lot less useful than the standard version.

**Comment by aymanhab** [comment]
Duplicate #193

**Comment by jenhicks** [comment]
Closing as this is a duplicate issue.
