### ISSUE TITLE
Hiding geometry through showOnly make it permenantly hidden

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#463]
Reported by Beta testers

**Comment by aymanhab** [comment]
This is due to inconsistency between how showOnly interprets hide/show vs. other visualization commands.

**Comment by chrisdembia** [comment]
Jess had an issue at the UEFS where showOnly on a group of muscles works the first time, but clicking showOnly on a second group of muscles does not hide the first group of muscles for which she selected showOnly.

**Comment by aymanhab** [comment]
I should make this clear. ShowOnly is defined as hide all siblings, no intended interaction between different groups. If intention is showOnly in model then it should be done on the "all" group rather than in a specific group.

**Comment by aymanhab** [comment]
Pick 2 disjoint groups and do show only and all works perfectly fine for each one and when picked together (color each group with a different color so you can easily tell). I believe this is not a bug, an enhancement at best if a better alternative definition of showOnly is proposed. I can't reproduce the described behavior/bug generically.

**Comment by jenhicks** [comment]
@chrisdembia Do you know if this was something that came up when testing a specific example or tutorial?

**Comment by chrisdembia** [comment]
It was likely in the process of doing tutorial 3, but I don't know for sure.

**Comment by jenhicks** [comment]
Test in a model with groups.

**Comment by jenhicks** [comment]
Show/Hide behavior works as I would expect for groups of muscles. For disjoint muscles, it toggles between showing the groups correctly. If I am toggling between two groups and there is overlap, the muscle in the join of the two groups is still displayed (e.g., gastroc displays when toggling between display only for the plantarflexors and knee flexors)

**Comment by jimmyDunne** [comment]
Can confirm Jen's findings above.
