### ISSUE TITLE
Models and scripts are not put in the correct directory

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#467]
On starting OpenSim the first time, a dialog box asked where I wanted the models and scripts to reside. I copied and pasted the desired path into the textbox and then clicked "OK" but they were copied into `C:\Users\tkuchida\Documents\OpenSim40\Models` (the default location, I believe) anyway. If the contents of the textbox does not take precedence, then it should not be editable.

**Comment by aymanhab** [comment]
Fix submitted.

**Comment by tkuchida** [comment]
On a related note, should we put a README.txt in the root of the Models directory telling users that they need to modify Preferences in the GUI if they relocate the directory?

**Comment by aymanhab** [comment]
Why do they need to modify preferences?

**Comment by tkuchida** [comment]
> Why do they need to modify preferences?

I did not investigate thoroughly. The installer put the directory in the default location so I moved it to the location I had specified. I then assumed that would cause some sort of malfunction, so I went into Preferences and changed the two directories that were then pointing to a location that no longer existed.

**Comment by aymanhab** [comment]
I believe this has been fixed already. Please indicate if you find otherwise. Thanks

**Comment by tkuchida** [comment]
Fixed in AppVeyor artifact OpenSim-dd7dc47b-2018-02-11.zip.
