### ISSUE TITLE
Floor does not change texture until clicking in visualizer window

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#469]
The floor turns black when its texture is changed:
![](https://user-images.githubusercontent.com/4203505/34819438-9958627c-f672-11e7-8b88-869e2c50f088.png)

The new texture appears only after clicking in the visualizer window:
![](https://user-images.githubusercontent.com/4203505/34819444-9df0900c-f672-11e7-9b1d-65d4db1834e6.png)

Selecting from the "texture" drop-down box should force a re-render.

**Comment by aymanhab** [comment]
Will investigate

**Comment by tkuchida** [comment]
Floor no longer turns black, but selecting new texture still doesn't force re-render: texture changes only once user clicks in visualizer window (except when "nofloor" is selected, which is applied immediately). (AppVeyor artifact OpenSim-dd7dc47b-2018-02-11.zip)

**Comment by jenhicks** [comment]
This is not ready for testing in the 3-13 build.

**Comment by jimmyDunne** [comment]
The textures are re-rendered when switching. 

System:W10
Build:04-27-2018

**Comment by jenhicks** [comment]
Should this be moved to Verified on Windows and Mac then? @jimmyDunne

**Comment by jimmyDunne** [comment]
Yes, it can be moved to Verified on Windows and Mac
