### ISSUE TITLE
Experimental markers cannot be hidden

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#471]
Tested on leg6dof9musc.osim. Unable to hide all markers (right-click Markers in the Navigator window and select Display > Hide) and unable to hide individual marker (right-click a marker name in the Navigator window and select Display > Hide). No messages in the Message window and no red-circle errors. Marker does disappear if deleted (right-click a marker name in the Navigator window and select Delete).

**Comment by aymanhab** [comment]
@aseth1 will look into how markers are generating decorations

**Comment by aymanhab** [comment]
For the record,  in 3.3 the markers could be hidden in GUI but that was not persistent since there was no xml artifact. Adding Appearance to marker will allow the display to be persistent, and may allow changing the color, size of markers (functionality that didn't exist pre 4.0).

**Comment by aymanhab** [comment]
If the conclusion is to make non-persistent GUI changes then please reassign to me.

**Comment by aseth1** [comment]
Try to expose the Sphere geometry Appearance directly.

**Comment by aseth1** [comment]
YEs, OK for hidden to not be persistent.

**Comment by tkuchida** [comment]
Fixed in AppVeyor artifact OpenSim-dd7dc47b-2018-02-11.zip (tested Show/Show Only/Hide). @aseth1: Please close if verified (or if not necessary to verify) on :apple:.

**Comment by aseth1** [comment]
In Mac OpenSim 651d29f-2018-03-30, I am unable to hide a subset of experimental markers.

**Comment by aymanhab** [comment]
@aseth1 Experimental markers are totally different creatures since they are not Components that belong to the model. Please open a separate issue.

**Comment by jenhicks** [comment]
I cannot hide experimental markers. Should I move this back to next up @aymanhab ? Testing on the latest Mac build.

**Comment by jenhicks** [comment]
Ooops .. realized this isn't in my build yet.

**Comment by jimmyDunne** [comment]
Experimental markers can be hidden, shown, and shown only. 

![opensim_markers.gif](https://images.zenhubusercontent.com/544fc8297c6ccc6277a5b651/0ad5a4b3-0061-424b-85ff-b1fb2a13fe47)

Windows 10 
opensim-04-11-2018
