### ISSUE TITLE
Opacity dialog box has unpredictable size

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#473]
Right-click a body, select Display > Opacity, and close the dialog box; repeat. The box spawns with two sizes, one in which the "Apply" button is chopped:

![](https://user-images.githubusercontent.com/4203505/34823115-22454d56-f67e-11e7-9290-d7ced85158f4.png)
![](https://user-images.githubusercontent.com/4203505/34823118-270f287a-f67e-11e7-8078-a342ae06cc4c.png)

No red-circle error. Unclear why the box spawns with different sizes, as the user-facing application state appears to be identical in both cases. Did not investigate to determine whether this issue affects other dialog boxes.

**Comment by aymanhab** [comment]
This dialog was modified for 4.0 so I don't expect the sizing issue in other places. Fix submitted

**Comment by tkuchida** [comment]
Confirmed fixed in AppVeyor artifact OpenSim-2fd23ef3-2018-02-20.zip. Presumably fixed by #481.
