### ISSUE TITLE
"Force size" property field is editable but value returns to 1.0

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#474]
- File > Preview Experimental Data
- click *Forces*
- click box beside "force size" label, type "2", press Enter -> value returns to 1.0

**Comment by aymanhab** [comment]
SphereGeometry and Arrow size can't be changed after creation, even though scale factors are passed correctly they don't take effect. Need to recreate the Geometry.

**Comment by jenhicks** [comment]
@aymanhab Is it expected for both the size of the arrowhead and the length of the vector to be scaled? If so, this is working on Mac.

**Comment by aymanhab** [comment]
Yes @jenhicks it's a scale factor that's applied to the whole arrow which is a builtin primitive.

**Comment by jimmyDunne** [comment]
Changing 'force size' scales the length of the vector and the size of the arrow head.

System:W10
Build:04-27-2018
