### ISSUE TITLE
Experimental data visualization persists after closing

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#475]
Seems to be an issue only after opening the second time:
- File > Preview Experimental Data; select file -> appears in Navigator and Visualizer
- File > Close All -> closes as expected
- File > Preview Experimental Data; select file -> appears in Navigator and Visualizer
- File > Close All -> disappears from Navigator but arrow still shown in Visualizer

No red-circle error. Reproduced after closing and re-opening the application.

**Comment by aymanhab** [comment]
Boils down to adding motion graphics to scene rather than to a model, so they don't go away on closing. Investigating a fix

**Comment by jenhicks** [comment]
I'm not seeing the persisting arrows on Windows 10
