### ISSUE TITLE
[Mac] Mesh geometry does not show the first time the model is loaded

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#478]
On Mac, mesh geometry does not show the first time the GUI is loaded. This is present in the public beta 4.0.

**Comment by aymanhab** [comment]
The preference for "Geometry Path" actually looks correct even on first launch, it appears that it doesn't get used however on osx only.

**Comment by aymanhab** [comment]
Fixed in latest build of dev. environment

**Comment by chrisdembia** [comment]
Woohoo! What was the fix?

**Comment by aymanhab** [comment]
On OSX, the code that was pushing Preferences to API was executing before reading/deserializing preferences. Just added an explicit call to push Preferences to API after deserialization (pretty safe)

**Comment by aseth1** [comment]
@chrisdembia will verify

**Comment by chrisdembia** [comment]
Verified 🏁
