### ISSUE TITLE
Appearance of WrapObjects is not persistent

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#482]
Changes are not propagated to XML and so are not persistent after deserialization (Reported by Beta tester)

**Comment by aymanhab** [comment]
In 3.3, attempt to change color/appearance, throw exception but are respected on deserialization downstream.

**Comment by jenhicks** [comment]
@aymanhab What are the steps to test here?

**Comment by aymanhab** [comment]
- Get a model with wrap objects e.g. Arm26
- Open model in GUI and change color, visibility, opacity, ... of variety of wrap objects. Remember your choices.
- Save model
- Reload model to see if Appearance was persistent/applied.

**Comment by jenhicks** [comment]
Changes are now persistent on my windows 10 machine.

An issue I noted: 
- Use the slider to change the opacity of a wrap surface
- Close the Select Opacity window

If you try to change the opacity of the wrap surface again, it doesn't put the slider in the right place (it always shows 100% even if I changed opacity to 50%).

@aymanhab Is this a separate issue?

**Comment by tkuchida** [comment]
@jenhicks Also discussed on #446.
