### ISSUE TITLE
ShowOnly does not show the muscle group

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#484]
@bspineda can add details

**Comment by bspineda** [comment]
When you **Display/Show Only** on a muscle group, nothing happens. But when you click on **Display/Show** for the muscle group, the muscle group does show.

**Display/Show Only** does work on individual muscles.

**Comment by aymanhab** [comment]
The behavior of showOnly is a a bit ambiguous when objects appears more than once in the tree (for example in the case where a Muscle appears in multiple groups, or when there's an 'all' group). showOnly is interpreted as show descendants and hide all siblings. Fixing to make Muscle groups act more similar to earlier versions.

**Comment by bspineda** [comment]
Display > Show Only now works fine with the latest build from 1/26/18.
