### ISSUE TITLE
Tutorial 2 does not graphically update muscle points.

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#485]
Tendon transfer does not work

**Comment by aseth1** [comment]
@apoorvar to verify

**Comment by apoorvar** [comment]
Updating coordinates of a path point from the Properties/GeometryPath window updates location of muscle point in the visualizer. However, selecting a path point in the visualizer and dragging it somewhere else does not update its location in the GeometryPath window. (Tested on OpenSim 359db2e-2017-11-14)

**Comment by jenhicks** [comment]
Issue is that we need to decide when to show and when to hide path points ... too much communication to show them all the time.
