### ISSUE TITLE
Runnning FD on Arm26 pipeline from GUI fails

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#488]
Reported by Beta tester

**Comment by aymanhab** [comment]
Fix submitted

**Comment by aseth1** [comment]
@aymanhab What was broken and what was fixed?

**Comment by aseth1** [comment]
@nickbianco to verify

**Comment by aymanhab** [comment]
https://github.com/opensim-org/opensim-gui/pull/491 initSystem was called before tool.setModel which was wiping out the system, the PR moved the call to initSystem down

**Comment by nickbianco** [comment]
FD pipeline works for me. (Windows, 64-bit, artifact OpenSim-dd7dc47b-2018-02-11).
