### ISSUE TITLE
Floor is not properly lit after changing texture

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#490]
- after opening model:
![](https://user-images.githubusercontent.com/4203505/35171145-8c6468da-fd17-11e7-99fe-8bbe5ea62ace.png)

- after changing floor to different texture and then back to original texture:
![](https://user-images.githubusercontent.com/4203505/35171160-96dec382-fd17-11e7-840a-da9f12885ead.png)

**Comment by tkuchida** [comment]
I think the issue is in editor/js/OpenSimEditor.js:
- [on line 694](https://github.com/opensim-org/three.js/blob/master/editor/js/OpenSimEditor.js#L694), the ground mesh is created with color `0xffffff`
- [on line 802](https://github.com/opensim-org/three.js/blob/master/editor/js/OpenSimEditor.js#L802), the ground mesh is updated to a texture with color `0x888888`

**Comment by aymanhab** [comment]
fix submitted.

**Comment by tkuchida** [comment]
Verified fixed in OpenSim-078b8daf-2018-01-26.zip from AppVeyor/artifacts.
