### ISSUE TITLE
Handle change of Ground from Body to PhysicalFrame - GUI part

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#5]
Here's a list of places where we used to use Bodies (including ground) that will need to change to either use Frames, PhysicalFrames or continue to use Bodies:

Edited March 12, 2018

- [x] ground appears at top-level of model Navigator and not in Bodies list
- [x] GeometryPath editing: select Body to attach
- [ ] Definition of ExternalLoads (Point, Force expressed in ...)
~~- [ ] List of Bodies in Navigator~~
- [x] Tools-RRA: Body to apply residual
- [ ] Tools-Scale: Assign scale-factors to Bodies and/or use measurements.
- [x] Topological Viewer/Editor
- [ ] Visualization of Experimental Data.

**Comment by aseth1** [comment]
@aymanhab how should `Ground` appear in *Visualization of Experimental Data*? Does this just mean that preview works?

If you try to create/edit Motion Object (what is that supposed to be anyways?) You cannot select ground as *Apply to* or *Expressed in* frame.

![image](https://user-images.githubusercontent.com/6494122/37305737-b726e6c0-25f2-11e8-9fe6-ee04f02701a1.png)

**Comment by aseth1** [comment]
We can edit `GeometryPath` with `ground` as option for the *Frame* of the path point. But transforming neither preserves the values in the new Frame nor preserves its location with respect to ground.

**Comment by aymanhab** [comment]
@aseth1 The essence of this issue is that in the past we had Bodies and Ground was one of them and in multiple places across the GUI we were using the same list of Bodies for selection. Now we changed the API so that Ground is not a Body, there're multiple kinds of Frames ("Ground", Frame (generic), PhysicalFrame, PhysicalOffsetFrame, ..etc.) This issue is asking for a specification of what kind of Frames are valid for each scenario. Some defaults/guesses were taken earlier when the GUI was trying to catch up to the API but that needs review now that API is mostly frozen for 4.0. Please provide your recommendation. Thanks

**Comment by aseth1** [comment]
When needing a valid of list of Frames for attaching physical things likes forces (muscles) and their connection points your need a `PhysicalFrame`. In almost any case you were providing a list of Bodies you can replace with PhysicalFrames.

**Comment by aseth1** [comment]
Using just bodies for the pull-down list for RRA also seems correct since only a Body has inertia and mass properties.

**Comment by jenhicks** [comment]
@aseth1 will close this issue and make a new one for external loads

**Comment by aseth1** [comment]
Issue #591 created to handle remaining outstanding issue. Closing.
