### ISSUE TITLE
Marker location is not preserved after editing parent_frame 

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#506]
Socket, `parent_frame` is  editable. But Marker is not correctly mapped when changed. They are put onto the origin of the other frame (R.ASIS after changing pelvis to femur_r is at hip joint center). 

Not clear when the transfer happens. As soon as frame is selected from pull-down or when changing context (clicking on visualizer window or navigator) because visually the marker does not move (disappear) until I click outside of the Marker property editor.

Also, CPU begins to throttle on Mac build OpenSim 2112110-2018-01-31. Using >%130 CPU. Had to quit OpenSim to stop.

**Comment by tkuchida** [comment]
Still an issue in 75fdf108-2018-05-11. Marker location should be re-expressed in new frame, not moved to same local coordinates in that frame. Also, sphere in Visualizer doesn't update until drop-down box beside "PhysicalFrame:parent_frame" loses focus.

**Comment by jimmyDunne** [comment]
>  Marker location should be re-expressed in new frame

This behavior still exists and needs to be fixed. Re-expressing the location of the marker in a different frame is a great feature. We absolutely can't lose that.

**Comment by jimmyDunne** [comment]
Markers can be re-expressed based on the frame. Tested on Windows and Mac.
