### ISSUE TITLE
Previewing marker data with gait model opens zooms to the feet where experimental markers cannot be seen

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#508]
Load subject01.osim model from Gait10dof18musc example folder:

![image.png](https://images.zenhubusercontent.com/57bf7e8ee40e5714b16dd911/e6cb2570-9640-4c8b-82fa-be541a4ba835)

Now preview related static trc file from ExperimentalData folder:
![image.png](https://images.zenhubusercontent.com/57bf7e8ee40e5714b16dd911/943d8bce-3272-4e56-9916-eee43a1daf3b)

**Comment by aseth1** [comment]
Potentially related to #163

**Comment by jenhicks** [comment]
Even without a loaded model, when you load marker data (E.g., from gait2354 model folder, walking trial), the view is very zoomed in.

**Comment by aymanhab** [comment]
Fixed in PR #733 by not moving the camera or refitting on Preview (unless only model)

**Comment by jenhicks** [comment]
Same on my Mac (5-31 build)
