### ISSUE TITLE
Experimental and model marker displays have inconsistent shading and/or materials

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#509]
Experimental markers are displayed as much larger 3D spheres compared to the flat (2D) pink circles of model markers:
![image](https://user-images.githubusercontent.com/6494122/36048620-adc5a218-0d94-11e8-853d-4f98033ef9fa.png)

**Comment by tkuchida** [comment]
Why are the pink model markers rendered without shading? Perhaps the wrong `Material`?

**Comment by aseth1** [comment]
Related to #559.  Experimental and Model markers should be essentially the same (size, shape) except and differentiated by color.

**Comment by aymanhab** [comment]
fixed in PR #647

**Comment by jenhicks** [comment]
Size, shape and shading are now consistent on my Mac build

**Comment by jimmyDunne** [comment]
the markers seem to be the same size. They don't seem to be the same material or have the same shading. They seem like different objects. 

![pink_and_blue_markers.png](https://images.zenhubusercontent.com/544fc8297c6ccc6277a5b651/b9818e43-6d29-48c8-bade-d81a0b30ec50)

**Comment by jenhicks** [comment]
Thanks @jimmyDunne ... I updated the title and moved to backlog.

**Comment by tkuchida** [comment]
It would be nice if the spheres were drawn with the same number of faces as well (the model markers are much smoother). 75fdf108-2018-05-11

![](https://user-images.githubusercontent.com/4203505/40090918-9b583d28-5869-11e8-8579-9a6bfe1548cb.png)

**Comment by tkuchida** [comment]
![](https://user-images.githubusercontent.com/4203505/40893699-47d8a266-6758-11e8-8565-95519dee3d51.png)
