### ISSUE TITLE
The "running dude" button generates simulations of inconsistent duration

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#511]
**Steps to reproduce:**
1. Open a model and set the :running_man: *end time* to 5.0.
2. Click :running_man: and play the animation.
3. Repeat step 2.

**Results:**
Simulations are 4.993, 4.999, and 4.998 seconds long.

![](https://user-images.githubusercontent.com/4203505/36067523-726d655e-0e73-11e8-9085-e7784dab5505.png)
![](https://user-images.githubusercontent.com/4203505/36067524-7579b040-0e73-11e8-88c6-4e79aa1bd97e.png)
![](https://user-images.githubusercontent.com/4203505/36067527-7785601e-0e73-11e8-9c9d-410b34fa3f8f.png)

**Environment:**
*OpenSim-078b8daf-2018-01-26.zip* (obtained from AppVeyor artifacts) on Windows.

**Comment by chrisdembia** [comment]
This might be related to the state that the Manager returns, which may have been changed in the improvements to Manager.

**Comment by chrisdembia** [comment]
Jenny has this issue too with the Tug Of War model and the Forward Tool. The final time in the forward tool was 0.5 but the simulation only went to 0.48 seconds. So, this is not only an issue with the running dude.

UEFS

**Comment by aymanhab** [comment]
I believe this is fixed by PR #571 Please verify when it's merged

**Comment by aymanhab** [comment]
Since PR #571 has been merged, this should be fixed in latest build.

**Comment by jenhicks** [comment]
This is fixed for me Windows 10 OpenSim-e7831221-2018-03-06

**Comment by tkuchida** [comment]
Verified using :running_man: button and Forward Tool. AppVeyor artifact OpenSim-e7831221-2018-03-06.zip.

**Comment by tkuchida** [comment]
Reopening because @jenhicks tested using the same AppVeyor artifact and I presume wants this tested on mac also?
