### ISSUE TITLE
Undo button remains disabled following undo-able action

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#512]
**Steps to reproduce**
Open *arm26.osim* and select Bodies -> Display -> Hide. Bodies disappear but undo button remains disabled. Editing a property (e.g., mass of a body) enables the undo button, whereupon the property edit as well as the previous hide operation can be undone.

**Environment**
Windows, with *OpenSim-078b8daf-2018-01-26.zip* artifact from AppVeyor.

**Comment by carmichaelong** [comment]
Notes from #909 have been accounted for and placed into separate issues
