### ISSUE TITLE
Show/hide errors when model is not the current model (ToyLandingModel)

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-gui#522]
While running the ToyLandingModel tutorial, I found that showing and hiding the model behaved inconsistently for models not designated as the current model. (Windows, AppVeyor artifact OpenSim-dd7dc47b-2018-02-11).

To reproduce:
- Open the ToyLandingModel.osim and ToyLandingModel_AFO.osim models
- Set the ToyLandingModel.osim model as the current model
- Right click the ToyLandingModel_AFO.osim model in the Navigator and select Display --> Hide. The footplate geometry _will not_ be hidden. Trying to hide the r_AFO_footplate body directly will not hide the geometry either.
- Set the ToyLandingModel_AFO.osim as the current model. You can now hide the footplate geometry, either by hiding the entire model, or by hiding through the r_AFO_footplate body directly.
- Keep ToyLandingModel_AFO.osim hidden and set ToyLandingModel.osim as the current model.
- Now try to show ToyLandingModel_AFO.osim (right click --> Display --> Show). Depending on whether or not you previously hid the entire model or only hid the footplate to remove the footplate geometry, different errors will occur. The model will either not show at all (if you previously hid the entire model), or the model will show but without the footplate geometry (if you only hid the footplate).

**Comment by jenhicks** [comment]
Show/hide seems to be working as expected now on my Mac.
