### ISSUE TITLE
Visualizer becomes disconnected from playback after waking up PC from sleep

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-gui#523]
After generating forward simulations for the ToyLandingModel tutorial and succesfully generating playback, I put my computer to sleep. After waking up my computer, I tried to run the playback again. The playback slider and the sliders in the Coordinates pane seemed to change normally based on the playback, but no response was seen in the Visualizer Window. 

The Visualizer Window was still responsive (rotating, zooming, etc still worked fine), but seemed disconnected from the playback. In addition, the model would not disappear from the Visualizer after being closed in the Navigator pane.

**Comment by aymanhab** [comment]
This is expected because the GUI (server) times out the connection after long idle time. Possible workaround or solutions:

- Send heart-beat message every minutes to keep alive (may have side-effects if application wakes-up/open).
- Note the disconnect in messages and suggest open a new window (that should work)
Any thoughts, preferences?

**Comment by aseth1** [comment]
Still an issue as of OpenSim-43c1be65-2018-05-30
Also happens to me when I lock my computer and comeback after some time. It means I cannot leave OpenSim in a working state that I can resume the following day. OpenSim 3.3 could stay open for days with out issues.

**Comment by aymanhab** [comment]
Also reported by BJ Fregly

**Comment by aymanhab** [comment]
@jenhicks

**Comment by jenhicks** [comment]
I'm leaning towards waiting on this one, though welcome to hear what others think.

**Comment by chrisdembia** [comment]
I agree with waiting.

**Comment by aseth1** [comment]
> Note the disconnect in messages and suggest open a new window (that should work)
Any thoughts, preferences?

If you can note it to message the user could you not refresh the window at that time so it is not even noticeable to the user?

**Comment by aymanhab** [comment]
fixed by #1463
