### ISSUE TITLE
Can't "Cancel" the dialog for installing models and scripts

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#528]
### Steps to reproduce

1. Launch the GUI for the first time, but the resources directory in Documents should already exist (for example, the GUI was reinstalled).
2. The following pops up. I click OK.
<img width="750" alt="screen shot 2018-02-22 at 1 23 00 pm" src="https://user-images.githubusercontent.com/846001/36564839-83ed75c6-17d3-11e8-92d9-545dbc313eb4.png">
3. I get this window and click Cancel (or OK):

<img width="431" alt="screen shot 2018-02-22 at 1 23 24 pm" src="https://user-images.githubusercontent.com/846001/36564855-917b3f34-17d3-11e8-9e13-538a14d23b73.png">

4. I then get the same error window as in step 2. 

### Expected result

Clicking "Cancel" causes the GUI to stop trying to install the resources.

### Actual result

There is no way to get out of these dialogs except for deleting the resources directory.

An aside: the dialog from step 2 has an extra period. Ideally, this dialog would also show the actual "specified directory" that already exists.

### Environment and GUI version

Mac OpenSim 33f3da0-2018-02-21

**Comment by tkuchida** [comment]
Unable to cancel on Windows as well (AppVeyor artifact OpenSim-dd7dc47b-2018-02-11.zip).

Also, I'm forced to "install" (copy) the files again every time I switch between versions of the beta. I don't understand the logic for that, though it doesn't seem to happen if I switch between 4.0 beta and 3.3, which is fortunate.

**Comment by aymanhab** [comment]
I believe this has been fixed, maybe you can test @tkuchida from the latest build.

**Comment by tkuchida** [comment]
**Test log**
- downloaded and extracted AppVeyor artifact OpenSim-6826a797-2018-02-28.zip
- ran OpenSim\bin\OpenSim64.exe (2018-02-28) -> dialog for installing models and scripts did not appear
- opened and closed 3.3
- ran OpenSim\bin\OpenSim64.exe (2018-02-28) again -> dialog still did not appear
- ran OpenSim from an old AppVeyor artifact (OpenSim-078b8daf-2018-01-26.zip) -> dialog appeared
- ran OpenSim\bin\OpenSim64.exe (2018-02-28) again -> dialog appeared; clicking "Cancel" closed the dialog, as expected

**Comment by jenhicks** [comment]
Fixed on my Mac as well.
