### ISSUE TITLE
ScaleTool's preview of static pose, without scaling, fails

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#537]
### Steps to reproduce
1. Load subject01_simbody.osim Models/Gait2392_Simbody
2. Launch ScaleTool
3. Uncheck "Scale Model"
4. Check "Adjust Model Markers"
5. For "Marker data for static pose" use: subject01_static.trc 
6. Check "Preview static pose (no marker movement)"
7. Verify weights under "Static Pose Weights" tab are defined ( all 1.0)
8. Back to "Settings" tab and press Run.

### Expected result
The model posed to static trial specified with a preview of where the model markers are relative to experimental markers.

### Actual result
No preview of pose, just error message.
<img width="1380" alt="screen shot 2018-02-25 at 1 02 37 pm" src="https://user-images.githubusercontent.com/6494122/36646441-46a1d9ea-1a2c-11e8-83ce-5c2b237b74e5.png">

### Environment and GUI version
Mac build: OpenSim c596914-2018-02-24

**Comment by aymanhab** [comment]
May be in 3.3 as well. Ideally the iteration of scaling doesn't create a new model and is not based on the latest/current model

**Comment by jenhicks** [comment]
@jimmyDunne Do you know offhand if this is also a bug in 3.3?

**Comment by aymanhab** [comment]
Exact behavior occurs in 3.3, but instead of dialog showing exception, the red stop-sign shows in the lower right corner of the application window.

**Comment by jimmyDunne** [comment]
A second, posed, Model is generated, Red Circle of Death appears in the right-hand corner without much useful info on what went wrong (Below). @aymanhab, what is the definition of Done for this? Is it (i) pose is generated and no Red Circle of Death, or is it (ii) pose is generated with Red Circle and we will fix later? 

`
A java.lang.NullPointerException exception has occurred.
	Click Show Details or see the messages.log file located in your /Users/jimmy/Library/Application Support/OpenSim/cea85df-2018-07-18/var/log folder.
`

**Comment by aymanhab** [comment]
@jimmyDunne What's the stacktrace for the red-circle, and is it justified (pilot error). If the functionality works and there's a spurious exception then I'd consider it Done, if you're stuck or the user function didn't get accomplished then it's not Done.

**Comment by jimmyDunne** [comment]
I had spent a few hours doing other things in the GUI before testing this— trying to recreate in fresh GUI, I don't see the issue. I can perform the operations specified by Ajay and I don't get any errors (Mac)
