### ISSUE TITLE
Unexplained offset between experimental data and model motion

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#538]
### Steps to reproduce
1. Load *Models/Gait2392_Simbody/subject01_simbody.osim*
2. Launch IK Tool and load *subject01_Setup_IK.xml* and press run
3. Replay IK result
4. File->Preview Experimental Data ... select *subject01_walk1.trc* (markers load zoomed in at feet)
5. File->Preview Experimental Data ... select *subject01_walk1_grf.mot* (forces load with some other point of view)
6.  Verify that models offsets are all 0, 0, 0.
7. Synch IK and experimental motions

### Expected result
Model performing motion from IK with experimental markers and forces appearing on (applied to) the model.

### Actual result
Model with IK motion is offset from experimental data (~1m).
<img width="1174" alt="screen shot 2018-02-25 at 1 26 11 pm" src="https://user-images.githubusercontent.com/6494122/36646728-718104ca-1a30-11e8-8863-580b11007de8.png">

### Environment and GUI version
Mac build: OpenSim c596914-2018-02-24

**Comment by aymanhab** [comment]
This is the same as the issue that offset is relative rather than absolute #88

**Comment by aymanhab** [comment]
Model offset dialog and global frame display should explain now!

**Comment by jimmyDunne** [comment]
Experimental Data opens in the correct position, without offset. 
W10, OpenSim-32ef4769-2018-05-12-win64.exe

**Comment by jimmyDunne** [comment]
There are mystery offsets applied to the model after scaling. The below figure is a freshly scaled model and the model offset. This is not correct- an offset has been applied to the model that is not seen here. 

![offset](https://user-images.githubusercontent.com/5296507/40373000-c73ed54c-5d9a-11e8-9a0f-836cc250eab3.png)

When you open the models offset pane, the model will 'snap back' to a position of no offset. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5296507/40374365-c1689772-5d9d-11e8-85f1-653df1d14a74.gif)

Once scaled and registered, the model should either have (a) no offset- coincident with the experimental data used to run the markerplacer(), or (b) a generic offset-  model is moved to be coincident with the experimental data and an added offset. Option (b) is what occurred in 3.3. I would prefer (a).

W10, OpenSim-e0b1e1a2-2018-05-21-win64.exe

**Comment by aymanhab** [comment]
@jimmyDunne Please check latest build and report. Thanks

**Comment by jimmyDunne** [comment]
This was the latest build.

**Comment by aymanhab** [comment]
@jimmyDunne builds from 05-22 and later (on Windows) should have offsets all working without a hitch and you should be able to find out if there's offset added. Please update accordingly.

**Comment by jimmyDunne** [comment]
Initial (and follow up) issues have been confirmed fixed. 
W10. OpenSim-ffdf2f78-2018-05-29-win64.exe
