### ISSUE TITLE
Muscle Display Radius has no effect on muscle display in GUI

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#539]
### Steps to reproduce
Edit->Preferences...->Muscle Display Radius changed to 0.001 (from 0.05).

### Expected result
Expected muscles to appear thinner.

### Actual result
No effect.
(include screen grabs where appropriate)

### Environment and GUI version
Mac build: OpenSim c596914-2018-02-24

**Comment by bspineda** [comment]
Here is an image of the rat model. This will need to be fixed. 
![rat](https://user-images.githubusercontent.com/32551585/36701415-2cfde84e-1b08-11e8-8e37-033ea5ce9c7b.png)

**Comment by jimmyDunne** [comment]
Changing the Muscle Display radius does not change a models muscle radius. You have to close and re-open the model for the altered Muscle Display Radius to take effect. 

There are also two entries for Muscle Display Radius in the Preferences Pane. 

![muscle_radius_preferences](https://user-images.githubusercontent.com/5296507/39588705-28b042fa-4eb1-11e8-800c-86e36b9889be.png)

W10
OpenSim-ba958aac-2018-04-30_threejs_r91.zip

**Comment by aymanhab** [comment]
Some preferences take effect immediately and some upon loading a new model, considering that they persist I wouldn't consider this a bug. The duplicate Preference is a bug however that I will investigate. Thanks for testing @jimmyDunne

**Comment by aymanhab** [comment]
Actually the names are different by a typo "Display" vs. "Dsiplay"! fixed to unify and retired the misspelled one!

**Comment by jimmyDunne** [comment]
Based on Ajay's post, the desire would be for the muscles to change radius immediately- I would like to see the same behaviour. If a user is trying to make a figure and has to have to iterate by closing down the whole application, I don't think that is great.

**Comment by aymanhab** [comment]
@jimmyDunne Recreating the geometry for all muscles on the fly to change radius, while possible, seems like an overkill of a functionality to provide considering that users can load another instance of the model without closing the app to get the same effect. 
While creating a figure is very important, the more likely use case is either you always prefer the muscles to be thinner/thicker or you're using non-human model where this change is rather long term.

**Comment by jimmyDunne** [comment]
Thanks for the good perspective, Ayman. @aseth1, are you okay with me moving this to 'done'? The muscle display radius does change, just after a reboot. I will add a documentation tag so that this behaviour is known.

**Comment by aseth1** [comment]
I am sure the users could live with having to **reload** the model (not reboot app), which seems better than nothing and is at least consistent with 3.3 (should verify).  As a user I would prefer to modify the instance I am working with and would want to do that in the 3D or navigator (not through preferences).

@aymanhab As a rule can you say that settings in the Preferences require a model reload? Can we have model viewing preferences (requiring a reload of the model) separated from environment preferences (requiring a relaunch of the GUI)? The laundry list does not make it clear when changes take effect.

**Comment by tkuchida** [comment]
> As a rule can you say that settings in the Preferences require a model reload? Can we have model viewing preferences (requiring a reload of the model) separated from environment preferences (requiring a relaunch of the GUI)? The laundry list does not make it clear when changes take effect.

I agree- it would be very nice if the user were told when they need to reload the model or restart the GUI for the changes they made to take effect. Could be using labels in the Preferences window, or display a dialog box after clicking *OK* if a Preference has been changed that requires some user action before it takes effect.

**Comment by aymanhab** [comment]
Great feedback @jimmyDunne @aseth1 and @tkuchida I totally agree the uncategorized list we have now is not user friendly. In applications with long lists of preferences, they are shown on different tabs so they're grouped in a more intuitive way. We should keep this on the table.
Generally, the code that creates the visuals reads the preferences on entry (i.e. on model opening) so model reload would be sufficient rather than a reboot.
