### ISSUE TITLE
Clipping plane/Bounding box in 3D view can hide a model that is loaded

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#541]
### Steps to reproduce
Load the SoccerKickingModel.osim

### Expected result
The bounding box is adjusted so that model and all its graphical elements are in view.

### Actual result
The model is not in view. Randomly scrolling happens to get you to "bump" into the model.
<img width="985" alt="screen shot 2018-02-25 at 9 42 30 pm" src="https://user-images.githubusercontent.com/6494122/36654984-dda5bcd8-1a74-11e8-831b-fbe9f409fbe2.png">

Moving the view and zooming is still unable to get the complete model in view without cutting off details.
<img width="981" alt="screen shot 2018-02-25 at 9 45 08 pm" src="https://user-images.githubusercontent.com/6494122/36655049-33d06b44-1a75-11e8-96fb-22ea9e7054fe.png">

### Environment and GUI version
Mac OpenSim c596914-2018-02-24

**Comment by aymanhab** [comment]
Trying to load the model from latest master I get:

Loaded model SoccerBallKickingModel from file E:\src\opensim-gui\opensim-models\Models\SoccerKick\SoccerKickingModel.osim
Body 'tibia_r' not connected by a Joint.
A FreeJoint will be added to connect it to ground.

Where do I get the latest working version? Thanks

**Comment by tkuchida** [comment]
> Where do I get the latest working version? Thanks

"master" branch of https://github.com/opensim-org/opensim-models repo. I just tested using AppVeyor artifact OpenSim-be3c7698-2018-04-05.zip. Please ensure your local clone has been synced.

**Comment by aymanhab** [comment]
For this model I highly recommend though that:
1. We make grass floor, use "texture" for it.
2. Use Skybox that's all clouds or add another one that's track/field/outdoors
3. Remove sky, ground from model as they are not used other than visualization and they introduce edges/boundaries that are awkward to workaround/visualize while floor and skyboxes are better at that.

**Comment by jimmyDunne** [comment]
When opening soccer model, the whole model is in the clipping plane. There are some issues with the soccer model, but the clipping plane issue seems to be resolved. @aseth1 do you have any specific test or behaviour you expect?
W10, OpenSim-a0d644b3-2018-05-04.zip

**Comment by tkuchida** [comment]
> the whole model is in the clipping plane

Please see [this image](https://msdn.microsoft.com/dynimg/IC412710.png) for the terminology.

**Comment by chrisdembia** [comment]
Did fixing this cause Z-fighting (#826)?
