### ISSUE TITLE
Crash when adding and moving new marker

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#542]
### Steps to reproduce
- open a model
- in *Navigator*, right-click *Markers* and select *Add New*
- hold `<Ctrl>` and left-click marker circle in Visualizer window

### Expected result
Marker's axes appear, allowing user to drag Marker around visualizer.

### Actual result
Marker's axes automatically appear, disappear, appear, disappear, … (approx. 2 cycles/second), and a list of the text "Marker:NewMarker_2" fills the status bar.

![](https://user-images.githubusercontent.com/4203505/36660076-9a79f64c-1a8b-11e8-9aed-43b0a6f53ba3.png)

### Environment and GUI version
OpenSim-2416f17a-2018-02-25.zip ("OpenSim 4.0 User Experience and Feedback Session" version)

**Comment by tkuchida** [comment]
Also occurs just by clicking the marker (i.e., no `<Ctrl>`). Marker is selected after first click, but immediately becomes deselected. After clicking again, the GUI enters a loop of selecting and deselecting the marker.

**Comment by jenhicks** [comment]
This seems to be working, except for the first marker that I add is bigger than subsequent markers. 
Load gait2354
Add marker
Move it around (it gets bigger)
Add a second marker 
Move it around (it doesn't get bigger)

**Comment by chrisdembia** [comment]
At the UEFS, Hannah had an issue where the GUI autonomously toggled between two markers in the navigator at 1 or 2 cycles per second.

**Comment by aymanhab** [comment]
@chrisdembia indeed that was an issue due to circular notifications being sent between the navigator and visualizer but that was fixed (by utilizing a master list of selected objects as was done in 3.3 and earlier).

**Comment by jimmyDunne** [comment]
Markers can be added and selected without crashes. However, when you try to move it the marker gets scaled- I have opened a new issue for this at #695
