### ISSUE TITLE
Installer doesn't add path on Windows: document needed steps for Python and Matlab users

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#546]
### Steps to reproduce
Using a Windows VM, install the GUI. Opening OpenSim results in an error message saying that the libraries aren't able to load since OpenSim isn't on the path. 

### Fix
Add the OpenSim path manually.

**Comment by aymanhab** [comment]
There's an open issue to great Windows installer, please refer to it or add comments so they can be addressed together. Thanks

**Comment by aymanhab** [comment]
There's an open issue to great Windows installer, please refer to it or add comments so they can be addressed together. Thanks

**Comment by chrisdembia** [comment]
Related #277

**Comment by aymanhab** [comment]
Will not fix, GUI doesn't need it, Matlab also doesn't and it pollutes the user environment, causes more issues with multiple versions and uninstall.

**Comment by aymanhab** [comment]
@chrisdembia Based on your experience, should we abandon Path change and use text file to load dynamic libraries? We should package the redistributable on Windows and run it from bin folder post install. Would you have some cycles to try this? Thanks.

**Comment by chrisdembia** [comment]
> @chrisdembia Based on your experience, should we abandon Path change and use text file to load dynamic libraries?

Loading libraries from the text file isn't really working out (https://github.com/opensim-org/opensim-core/pull/2174). The issue comes in when using the simbody-visuailzer, maybe because the visualizer doesn't use the text file to load its dependencies.

> We should package the redistributable on Windows and run it from bin folder post install. Would you have some cycles to try this? 

This is tracked in https://github.com/opensim-org/opensim-gui/issues/744 and https://github.com/opensim-org/opensim-build-releases/issues/1. I'd like to spend time on this but I'm not sure when I'll get to it.

**Comment by aymanhab** [comment]
I have no plan to add path to the system path since it causes more harm than good and precludes having multiple versions of OpenSim on the same machine. I'd recommend closing this one and documenting for Matlab and Python users what they need to do manually.

**Comment by jenhicks** [comment]
Issue moved to [opensim-org/opensim-core #2226](https://github.com/opensim-org/opensim-core/issues/2226) via [**ZenHub**](https://www.zenhub.com/)
