### ISSUE TITLE
Excitation Editor: Cannot select nodes on Mac

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#547]
### Steps to reproduce
1. Open max-height jumping example model
2. Open ForwardTool and the corresponding setup file.
3. Click on excitation editor
4. select nodes

### Expected result
- nodes are selectable and moveable 

### Actual result
- nodes cannot be edited.

### Environment and GUI version
Mac 02-25

**Comment by aseth1** [comment]
Update:  selection requires `shift-control` on Mac

**Comment by jenhicks** [comment]
shift-control worked for me ... moving to documentation

**Comment by jenhicks** [comment]
Issue moved to [opensim-org/opensim-core #2196](https://github.com/opensim-org/opensim-core/issues/2196) via [**ZenHub**](https://www.zenhub.com/)
