### ISSUE TITLE
Working with Static Optimization: does not make progress past 97%

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#548]
### Steps to reproduce

1. Run static optimization as part of https://simtk-confluence.stanford.edu/display/OpenSim/__40__Working+with+Static+Optimization

### Expected result

Static runs to completion.

### Actual result

Static stops making progress at 97%. Output of Activity Monitor's "Sample Process": (Pending email from Mazen).

[Sample of OpenSim.txt](https://github.com/opensim-org/opensim-gui/files/1759999/Sample.of.OpenSim.txt)

### Environment and GUI version

Mac UEFS

**Comment by chrisdembia** [comment]
Mazen thinks this is an issue with permissions: static optimization was probably trying to write files to the Applications directory.  We should not expose these symlinks anymore. Would be partially fixed by #504.

**Comment by aymanhab** [comment]
On windows I can run this to completion. If that failed to complete in the past, it's likely due to #571 since progresbar would never reach 100%. If osx specific then possibly permissions

**Comment by jenhicks** [comment]
I was able to run to completion without issue on my mac. OpenSim 03d9220-2018-04-09
