### ISSUE TITLE
CMC/Forward dynamics muscle activations do not visualize, nor on playback

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#549]
### Steps to reproduce
1. Open SoccerKickModel.osim example file
2. Open Forward Dynamics ... tool
3. select controls_kick.xml
4. Run

### Expected result
Model animates with active muscles turning red.
Playback visualizes muscle colors.

### Actual result
All muscles remain blue during forward simulation.
All muscles remain blue upon playback.

### Environment and GUI version
Mac Feb-25

**Comment by aymanhab** [comment]
@aseth1 Where did you get the model from so I can follow your steps. Thanks

**Comment by aseth1** [comment]
@aymanhab you can find them [here](https://github.com/opensim-org/opensim-models/pull/67)

**Comment by jenhicks** [comment]
@aseth1 Can you verify that this is fixed now or send me the files to test?

**Comment by aseth1** [comment]
This is not working for me on Mac on version OpenSim e07981e-2018-05-15.

I am running through tutorial 1 and running CMC. CMC runs but muscles are not colored.

<img width="1388" alt="screen shot 2018-05-16 at 10 38 07 am" src="https://user-images.githubusercontent.com/6494122/40133781-950e79dc-58f5-11e8-90d3-556778a2fb67.png">
