### ISSUE TITLE
Trying to run FD on WalkerModelAddMagnet_Feet hangs

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#553]
### Steps to reproduce
Load, run FD from tool or running dude

### Expected result
Runs

### Actual result
Nothing happens
(include screen grabs where appropriate)

**Comment by aymanhab** [comment]
[WalkerModelAddMagnet_Feet.txt](https://github.com/opensim-org/opensim-gui/files/1760380/WalkerModelAddMagnet_Feet.txt)

**Comment by aymanhab** [comment]
Encountered by Scott during feedback session

**Comment by tkuchida** [comment]
Unable to reproduce:
![](https://user-images.githubusercontent.com/4203505/36698130-e66d83ee-1afd-11e8-8fc3-2e211c8f725b.png)
What .obj file should I be using?

**Comment by aymanhab** [comment]
Some context? Where the model came from? Does it run in 3.3? Where did it get the files then?

**Comment by aymanhab** [comment]
Sorry @tkuchida I didn't realize that I opened this issue 😕

**Comment by tkuchida** [comment]
I renamed the file (attached above) from .txt to .osim, then replaced all instances of "ThinHalfCylinder100mmby50mm.obj" with "blockMesh.obj" (using blockMesh.obj from the Geometry directory). Model opens, but :one: is not centered in the Visualizer window (so perhaps a malfunction occurred silently---but no red circle error); and :two: the :running_man: button doesn't do anything. Forward Tool also doesn't do anything after clicking *Run*.

**Comment by aymanhab** [comment]
Can you upload the modified .osim (renamed to .txt) so I can try to run in debug mode? Thanks @tkuchida

**Comment by tkuchida** [comment]
@aymanhab [WalkerModelAddMagnet_Feet_modified.txt](https://github.com/opensim-org/opensim-gui/files/1760567/WalkerModelAddMagnet_Feet_modified.txt)

**Comment by aymanhab** [comment]
Inertias all messed up: Messages from debug build below, not sure if only reason yet

WARNING: Body Pelvis has invalid inertia. 
SimTK Exception thrown at MassProperties.h:548:
  Error detected by Simbody method Inertia::Inertia(moments,products): Diagonals of an Inertia matrix must satisfy the triangle inequality; got 0.0001,0.00666667,0.0001.
  (Required condition 'Ixx+Iyy+Slop>=Izz && Ixx+Izz+Slop>=Iyy && Iyy+Izz+Slop>=Ixx' was not met.)

Pelvis Body's inertia being reset to:

[0.00384987,0,0]
[0,0.00384987,0]
[0,0,0.00384987]

WARNING: Body LeftThigh has invalid inertia. 
SimTK Exception thrown at MassProperties.h:548:
  Error detected by Simbody method Inertia::Inertia(moments,products): Diagonals of an Inertia matrix must satisfy the triangle inequality; got 0.0001,0.0001,0.00104167.
  (Required condition 'Ixx+Iyy+Slop>=Izz && Ixx+Izz+Slop>=Iyy && Iyy+Izz+Slop>=Ixx' was not met.)

LeftThigh Body's inertia being reset to:

[0.000606926,0,0]
[0,0.000606926,0]
[0,0,0.000606926]

WARNING: Body RightThigh has invalid inertia. 
SimTK Exception thrown at MassProperties.h:548:
  Error detected by Simbody method Inertia::Inertia(moments,products): Diagonals of an Inertia matrix must satisfy the triangle inequality; got 0.0001,0.0001,0.00104167.
  (Required condition 'Ixx+Iyy+Slop>=Izz && Ixx+Izz+Slop>=Iyy && Iyy+Izz+Slop>=Ixx' was not met.)

RightThigh Body's inertia being reset to:

[0.000606926,0,0]
[0,0.000606926,0]
[0,0,0.000606926]

WARNING: Body LeftShank has invalid inertia. 
SimTK Exception thrown at MassProperties.h:548:
  Error detected by Simbody method Inertia::Inertia(moments,products): Diagonals of an Inertia matrix must satisfy the triangle inequality; got 0.0001,0.0001,0.00104167.
  (Required condition 'Ixx+Iyy+Slop>=Izz && Ixx+Izz+Slop>=Iyy && Iyy+Izz+Slop>=Ixx' was not met.)

LeftShank Body's inertia being reset to:

[0.000606926,0,0]
[0,0.000606926,0]
[0,0,0.000606926]

WARNING: Body RightShank has invalid inertia. 
SimTK Exception thrown at MassProperties.h:548:
  Error detected by Simbody method Inertia::Inertia(moments,products): Diagonals of an Inertia matrix must satisfy the triangle inequality; got 0.0001,0.0001,0.00104167.
  (Required condition 'Ixx+Iyy+Slop>=Izz && Ixx+Izz+Slop>=Iyy && Iyy+Izz+Slop>=Ixx' was not met.)

RightShank Body's inertia being reset to:

[0.000606926,0,0]
[0,0.000606926,0]
[0,0,0.000606926]

**Comment by aymanhab** [comment]
Error was being thrown regarding missing mesh file while running tool but was captured silently. Going over all catches to make sure errors/exceptions are communicated properly to users.

**Comment by jimmyDunne** [comment]
I tested both the models attached above. Once I am able to visualize the models (there is a new issue to do with visualization that is documented in #672), and run Forward, I do get a exception message reported;

![exception_message.png](https://images.zenhubusercontent.com/544fc8297c6ccc6277a5b651/997c7970-401f-486c-93e3-bc16da382110) 

I assume that solves the 'Silent exception' problem, but it doesn't seem to solve the original issue. The folder with the model contains the correct .obj file. Even with the model Tom posted, with blockMesh, running forward results in an exception to do with finding geometry (which is not only in the folder but in the Geometry folder as well);

![exception_message_block.png](https://images.zenhubusercontent.com/544fc8297c6ccc6277a5b651/91c48e03-3795-4593-807b-bab530c85d2b)

If the error has to do with inertia's it is not obvious from this.

**Comment by aymanhab** [comment]
This boils down to the following:
- ForwardTool uses directory of Setup file or Model as working directory
- In the case of using the running_dude 🏃 there's no setup file and GUI clones the Model so we end up with a blank working directory
- Mesh files are located exclusively using working directory  during initSystem (ForwardTool:253) so loading fails.

Same would happen in API if a model with contact is clones then initSystem is invoked on the clone. Thoughts or suggestions to make the GUI and API consistent/predictable @aseth1 @chrisdembia @jimmyDunne

**Comment by aseth1** [comment]
Can you use the Model's directory as the Tool's working directory in the 🏃 case?

**Comment by aymanhab** [comment]
But the model's directory is lost on clone.

**Comment by aymanhab** [comment]
@aseth1 the GUI used to do that (keep track of model file and trick the tool to use it) up to 3.3 but the Model refactoring and changes to the Model/Tools broke that mechanism. I can try to find what changed. 
Possible solutions:
- Find change from 3.3 and apply it (will still be the case that cloning  a model with contact meshes by users will fail to run unless they are lucky to run from same directory as the model).
- Have ContactMesh follow same scheme as visualization meshes and use search path.
- Have ForwardTool expose some sort of working directory though this is likely an issue with other tools as well.
I absolutely am not proposing removing 🏃 at all, Im just reporting the issue and trying to find a satisfactory solution/workaround.

**Comment by aseth1** [comment]
Can you elaborate on how the changes to the inner workings of `Model` affect the directory that it lives in? The cloning issue is the same for any mesh-based geometry. I would prefer that meshes live with the model and not use search path since geometry names are grossly over used and leads to all sorts of visual anomalies. At least keeping a local Geometry is clear and we could later combine dependent geometry with the Model (e.g. as zipped folder) down the road.

**Comment by aymanhab** [comment]
Got to the bottom of this and why it used to work and not anymore. We have a backdoor to tell a model where to look for contact mesh files using Model::set/getInputFileName(), we used to set it to the file of the original model then clean it up after last call to initsystem but now the last call is done inside ForwardTool::run. Since the models in question are throwaway we can get away without cleanup and the tools run successfully.

**Comment by jimmyDunne** [comment]
WalkerModelAddMagnet_feet successfully runs using 🏃 and through Forward Tool 🎆

**Comment by jenhicks** [comment]
Where does the walker model live so I can test?

**Comment by chrisdembia** [comment]
@aymanhab where did you get this model file?

**Comment by aymanhab** [comment]
https://www.dropbox.com/sh/up5poxhuuxovuvy/AAB2-TkF4jb9JQURZwTOL5kTa?dl=0
