### ISSUE TITLE
Add button to get stack trace, for reproducing issues

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#554]
Sometimes, it's nice to get a stack trace for the GUI even when there is no red exception circle, so that we can reproduce a softer issue (visualization bugs). We could add a menu button that prints a stack trace. Maybe the scripting shell could be used for this.

**Comment by aymanhab** [comment]
@chrisdembia we assume you mean recording the call sequence so we can reproduce issues. Button callstack will show the callstack for the button itself and so is not very useful. Can you please explain? Thanks

**Comment by chrisdembia** [comment]
Ah good point. I am not exactly sure what I mean. Recording the call sequence seems really difficult. I'm thinking the stack trace for all threads, not just the one that picked up the button press. There is a command-line tool `jmap` that gives diagnostic information for a running java program; perhaps there's a useful guideline there.

**Comment by tkuchida** [comment]
Something like MATLAB's command history would be very useful for documenting and restoring GUI sessions. Even better if the command history were actually a script that could be run in the GUI. Could also be useful for automated testing.
