### ISSUE TITLE
Probes not shown in Navigator

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#556]
### Steps to reproduce
- open subject01_metabolics.osim from [Simulation-Based Design to Reduce Metabolic Cost](https://simtk-confluence.stanford.edu/display/OpenSim/Simulation-Based+Design+to+Reduce+Metabolic+Cost)

### Expected result
*Probes* -> *metabolics* shown in Navigator.

### Actual result
*Probes* does not appear.

### Environment and GUI version
OpenSim-2416f17a-2018-02-25.zip ("OpenSim 4.0 User Experience and Feedback Session" version)

**Comment by aymanhab** [comment]
Addressed by PR #573 and PR #565

**Comment by jenhicks** [comment]
Fixed on windows OpenSim-e7831221-2018-03-06
