### ISSUE TITLE
NullPointerException when editing muscle path points on Mac

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#558]
### Steps to reproduce
- open a model
- select a muscle and click "..." beside GeometryPath
- edit value in a textbox

### Expected result
Visualization of muscle path changes after editing value.

### Actual result
Visualization does not change. NullPointerException thrown after closing dialog.

### Environment and GUI version
Reported by Mazen on Mac (El Capitan).

**Comment by tkuchida** [comment]
Unable to reproduce on Windows (OpenSim-2416f17a-2018-02-25.zip: "OpenSim 4.0 User Experience and Feedback Session" version).

**Comment by aymanhab** [comment]
Ideally path edit in same Properties window or make dialog modaless to enable visual edit and copy/paste from other objects

**Comment by aseth1** [comment]
The fix for Mac is also holding on Windows OpenSim_cea85df3-2018-07-18. I did see the muscle edit change the visualization upon hitting *Enter*.

The issue now is that there is not way to undo the path edit. But that is related issue #815
