### ISSUE TITLE
Pink model markers are rendered without shading

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#559]
Might look better as spheres rather than flat circles. Perhaps the wrong Material?

**3.3**
![](https://user-images.githubusercontent.com/4203505/36702452-084840cc-1b0c-11e8-9a9e-6745df736451.png)

**4.0**
![](https://user-images.githubusercontent.com/4203505/36702456-0d8b2c48-1b0c-11e8-8764-48810cb85b7d.png)

**Comment by tkuchida** [comment]
> Tom, objects live in scene and don't choose what lights are used to illuminate them. We can only change material pproperties. Totally open to changing defaults.

I don't know the details. You can specify which objects cast/receive shadows, so I figured it might be possible to specify which objects are illuminated by each light. I've edited by comment (above).

**Comment by aseth1** [comment]
related to #509

**Comment by aymanhab** [comment]
Fixed in PR #647, please verify on next build that contains the PR

**Comment by jenhicks** [comment]
The pink spheres look nice to me in OpenSim 03d9220-2018-04-09

**Comment by jimmyDunne** [comment]
Pink Markers seem to have shading. From distance and from different angles, they can look flat.

![pink_markers.png](https://images.zenhubusercontent.com/544fc8297c6ccc6277a5b651/b51e81d1-5f97-432b-9c0f-a5c356b5c1ef)

**Comment by tkuchida** [comment]
The model markers do have shading now (they are no longer flat circles) but they blend into a white background. Already noted on #509.
