### ISSUE TITLE
Handle isDisabled removal from Component

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#56]
Previously GUI was leveraging the isDisabled property for common code to enable/disable Forces, Constraints and Controllers. Now removed from API in Alpha release.

**Comment by aseth1** [comment]
Verify that force, constraints, probes and controllers respond to their replacements for isDisabled

**Comment by aseth1** [comment]
@apoorvar can you confirm that the enabling/disabling capability of specific Components works as expected. These are:

- Forces: appliesForce
- Constraints: isEnforced
- Controllers: enabled

**Comment by aymanhab** [comment]
Probe::enabled has been fixed in PR #573

**Comment by aseth1** [comment]
**Muscles**: On latest [Windows build](https://www.dropbox.com/home/DevBuilds/frameEditBuild) multi-selecting all individual Muscles you get an *Enable* right-click option with a checked box. If you uncheck the box,  then each Muscle gets a red prohibited 🚯 icon next to it and each muscle's *appliesForce* flag becomes unchecked (muscles do not disappear from visualizer as they did in 3.3). This takes  ~45s on the drop landing model (49 muscles) which seems excessive. Re-enabling takes about the same amount of time.

**Constraints**: Top-level *Constraints* has Show/Hide options which doesn't apply to most (all) constraints to-date. Similar to muscles there is  an *Enable* right-click option when multi-selecting constraints which is already checked. Unchecking *Enable* causes the *isEnforced* flag on each Constraint to be unchecked.

Need to find a Model with Probes and Controllers to verify these.

**Comment by jenhicks** [comment]
This one has probes:
https://simtk-confluence.stanford.edu:8443/display/OpenSim/Simulation-Based+Design+to+Reduce+Metabolic+Cost

@jimmyDunne Do the associated files live somewhere on GitHub?

**Comment by jenhicks** [comment]
ToyLandingModel_AFO has controllers (In Models/ToyDropLanding)

**Comment by aseth1** [comment]
**Controllers:** When *Enable* is checked in the Navigator the the controllers' *enabled* property is also checked. Unchecking the *Enable* in the Navigator also unchecks the *enabled* property.  ✔️

**Comment by aseth1** [comment]
**Probes**: When Enable is checked in the Navigator the the probe's enabled property is also checked. Unchecking the Enable in the Navigator also unchecks the enabled property. When Probe Enble is unchecked, its values are excluded from the `ProbeReporter` results. ✔️

**Comment by aseth1** [comment]
@jenhicks we can move to verified since the GUI is responding to the new flags instead of the old (removed) *isDisabled* flag. The issues are now:

1. a mismatch with the Navigor *Enable* option with the *appliesForce* and *isEnforced* flags on the `Force`s and `Constraint`s. 
2. setting the flags on multiple objects (e.g. Forces/Muscles) is very slow

**Comment by jenhicks** [comment]
Thanks @aseth1 Can you make issues for the points you note above? I don't see existing issues.
