### ISSUE TITLE
GUI hangs while splash screen is up and GUI is loading

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#563]
### Steps to reproduce

Open GUI (in my case, not the first time).

### Expected result

GUI opens.

### Actual result

GUI hangs.

[GUICrashOnLaunch.txt](https://github.com/opensim-org/opensim-gui/files/1760725/GUICrashOnLaunch.txt)

### Environment and GUI version

Mac OpenSim 2416f17-2018-02-25

Related: https://github.com/opensim-org/opensim-core/issues/2067

**Comment by aymanhab** [comment]
Why do you think it's related to 2067?

**Comment by chrisdembia** [comment]
In the crash log, `LogBuffer::sync()` is part of the stack trace.
