### ISSUE TITLE
Not clear which offsetFrame applies to a particular piece of geometry 

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#567]
When Geometry is selected, there is no Transform property displayed in the Properties Window. 

4.0 GUI
![screen shot 2018-02-27 at 12 24 12 pm](https://user-images.githubusercontent.com/5296507/36752946-872e351a-1bb9-11e8-806b-e28d9de54e21.png)

3.3 GUI
<img width="801" alt="screen shot 2018-02-27 at 12 24 24 pm" src="https://user-images.githubusercontent.com/5296507/36752968-94aa549e-1bb9-11e8-90b6-9aeba52375ab.png">

I would like access to the Geometry Transform.

**Comment by aymanhab** [comment]
There's no standalone Transform that lives with the Geometry, instead the Geometry is attached to a Frame (along with potentially other objects). Possible solutions:
- Show Frames in navigator and they are edited independently (adds clutter but maybe useful anyway)
- Add Frame properties to Geometry properties (may have side effects if the frame has been re-used)
- Open to other ideas/suggestions

**Comment by aseth1** [comment]
Ideally we could select "Frame" (from the known Socket)  to edit the Frame it is on and also have a "new" option to create a new Frame (in which case we create an OffsetFrame) that would allow you to enter any transformation you desire relative to any Body or Ground you desire.
