### ISSUE TITLE
Reduce size of three.js copy in GUI installation

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#569]
We should look for opportunities to further reduce the size of the three.js we copy into our installation. The three.js utils folder takes up 23.7 MB, 16 GB of which is a Blender exporder.

**Comment by aymanhab** [comment]
Indeed 15M are for exporters that can be removed, also the min file under build is a minified version of the src folder which we can remove in distribution. Feel free to submit PR

**Comment by aymanhab** [comment]
Size is now 40M and rather minimal, this can be closed.
