### ISSUE TITLE
GUI reports internal model name "daCopy" to user in Messages window

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#574]
### Steps to reproduce
- open arm26.osim
- click arrow beside cartoon on :running_man: button and set end time to 1.0
- click :running_man: button

### Expected result
GUI calls the model "arm26".

### Actual result
GUI calls the model "daCopy".
<pre>
Running tool arm26.
No external loads will be applied (external loads file not specified).
MODEL: daCopy
...
</pre>

### Environment and GUI version
AppVeyor artifact OpenSim-6826a797-2018-02-28.zip

**Comment by tkuchida** [comment]
Should be fixed by #576.

**Comment by jenhicks** [comment]
This is fixed on Windows 10 OpenSim-e7831221-2018-03-06

**Comment by tkuchida** [comment]
Confirmed fixed on AppVeyor artifact OpenSim-e7831221-2018-03-06.zip. I didn't realize that Jen already tested on the same version. @jenhicks I presume you left this Issue open because you want it tested on mac also?

**Comment by jenhicks** [comment]
@tkuchida Sorry for the confusion. I moved the issues that I verified to a "Verified on Windows" column so that we could test issues as needed on Mac as well. It's also nice to have more than one person verify fixes.

**Comment by jenhicks** [comment]
Verified on mac as well
