### ISSUE TITLE
4.0 should have a different set of preferences from 3.3

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#578]
4.0 should have its own preferences that are separate from 3.x. Otherwise 3.3 and 4.0 could not be used side-by-side (users would need to keep changing the geometry path, etc.).

First raised in https://github.com/opensim-org/opensim-models/issues/65.

**Comment by jenhicks** [comment]
@aymanhab Thoughts on this one?

**Comment by aymanhab** [comment]
Yes, it would be nice to have, though not necessary since 3.3 can always read the 4.0 Geometry files without a problem. Main issue this would solve from my perspective is having a fresh Geometry path for 4.0 so that Models all load and appear above ground without worrying about users changing their local settings. Relatively easy to fix once behavior is agreed upon.

**Comment by jenhicks** [comment]
What are the items discuss re the behavior of the geometry path?

**Comment by aymanhab** [comment]
Traditionally, on Windows, we leave path untouched if it was ever set by
user, the intuition being that users may have gone to extra length to set
it for their current workflow, and also that they can switch between
versions easily. This makes transition to new version transparent but has
the side effect that if we change contents of geometry files as in 4.0 they
don't see the upgrade/change.

**Comment by chrisdembia** [comment]
Users may also install and uninstall the GUI, and it's possible for the geometry path to point to a location that no longer exists.

I would like the following behavior (as seen in other applications): on first launch of a new version, if preferences for a previous version of OpenSIm are detected, the user is asked if they want to copy the preferences or use default preferences for the new version of OpenSim.

**Comment by jenhicks** [comment]
Sounds reasonable to me @chrisdembia . We may need to provide some guidance to users about what is recommended.

**Comment by chrisdembia** [comment]
> We may need to provide some guidance to users about what is recommended.

Good idea. The dialog box could communicate the following:

- Most users should choose fresh preferences.
- You may want to use copy previous preferences if you used a custom geometry path to files that you want to use in the new version of the GUI.
