### ISSUE TITLE
User is prompted for desired location of models and scripts directory, but GUI does not copy them there and does not communicate this to the user

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#580]
### Steps to reproduce
- start OpenSim for the first time
- when prompted, specify desired directory for models and scripts

### Expected result
Models and scripts are installed to specified directory and the user is informed that the operation was successful.

### Actual result
Two dialog boxes appeared; neither was helpful. The *Models* directory contains models as expected, but the *sdk* directory contains only two empty directories: *APIExamples* and *Scripts*. I presume there are supposed to be API examples in the *APIExamples* directory, but there aren't any. The user isn't told whether the operation completed as expected or whether a something went wrong.

First dialog box:
![](https://user-images.githubusercontent.com/4203505/37240455-72968d74-2400-11e8-8538-049cf4f95ec0.png)
Second dialog box:
![](https://user-images.githubusercontent.com/4203505/37240461-7c8589e8-2400-11e8-8430-687ff985df8c.png)

Contents of *Messages* window:
<pre>
Copying resources to C:\Users\tkuchida\OpenSim 4.0 appveyor Mar 6 2018\Models and Scripts
</pre>

### Environment and GUI version
AppVeyor artifact OpenSim-e7831221-2018-03-06.zip

**Comment by jenhicks** [comment]
@aymanhab Is this new to 4.0?

**Comment by aseth1** [comment]
Yes. We now copy editable "resources" which include the Models and CodeExamples (instead of sdk) into the Users home space. This is typically:
`C:\Users\<user_name>\Documents\OpenSim`

**Comment by aymanhab** [comment]
Tom, we replaced this part with a zip/unzip mechanism, can you report status on latest appveyor build? Thanks. You should be able to reinvoke the process by typing installResources () in the scripting shell.

**Comment by aymanhab** [comment]
@chrisdembia The Resources.zip on the windows AppVeyor build ends up with CodeExamples but no Models. Any idea what might be different from the version I tested locally? Thanks

**Comment by tkuchida** [comment]
> Tom, we replaced this part with a zip/unzip mechanism, can you report status on latest appveyor build?

Dialog box appeared requesting destination. I specified `C:\Users\tkuchida\OpenSim 4.0 appveyor Mar 14 2018\Models and Scripts`. Dialog disappeared, Messages windows says `Copying resources to C:\Users\tkuchida\OpenSim 4.0 appveyor Mar 14 2018\Models and Scripts... Done.`, but I see only `CodeExamples` in the specified directory (i.e., no `Models` directory). AppVeyor artifact OpenSim-0d41eef3-2018-03-14.zip

**Comment by aymanhab** [comment]
Thanks @tkuchida that's what I observed as well, fix in open PR #600

**Comment by chrisdembia** [comment]
Does the original issue still exist (uninformative dialog)?

**Comment by tkuchida** [comment]
> Does the original issue still exist (uninformative dialog)?

The original issue is no longer present but the situation is no better: the user still doesn't get models and scripts in the location specified. I have updated the title. The situation is analogous to going to the doctor with a sore elbow and he hits you over the head, then asks "Does your elbow still hurt?"

**Comment by jenhicks** [comment]
I don't have this issue on my Mac. Is it Windows specific?

**Comment by aymanhab** [comment]
I don't think the part that shows the dialog and prompts users is platform specific, if an error happens (e.g. directory exists, is invalid, no permission) that part and downstream could be platform specific.

**Comment by jimmyDunne** [comment]
On W10 machine the resources folder is prompted and copied. If an existing folder is there, the prompt asks you to copy it somewhere else. 

System:W10
Build:04-27-2018
