### ISSUE TITLE
Connecting a Joint's Socket to another Frame crashes the GUI if it leads to invalid tree

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#587]
### Steps to reproduce
Open a model,  like leg6dof8musc.osim.
Edit any `Joint` `Frame`'s `Socket` to point to connect to another `PhysicalFrame`.
E.g make *hip_r* parent frame connect to *ground_offset*.

### Expected result
Hip and femur_r are now connected to the *ground_offset* frame instead of the *pelvis_offset*.

### Actual result
The topology change takes effect. I see the new model rendered for a moment (femur_r at ground) and then it crashes.

I believe the GUI crashes because it fails to restore the state on the model. It cannot do that when the topology has changed. The state and the system will be incompatible. 

In general we shouldn't be treating Socket changes as ordinary property edits. Sockets are specifically used to change topology. 

### Environment and GUI version
Windows build for Frame changes available [here](https://www.dropbox.com/home/DevBuilds/frameEditBuild).

@jenhicks also saw this in #344 discussion:

> Is this issue affected by current work on frames? I tried changing a frame in the property editor for the ankle joint in the Hamner 2010 model:
> https://simtk.org/frs/?group_id=516
> 
> OpenSim crashed.
> [hs_err_pid4616.log](https://github.com/opensim-org/opensim-gui/files/1794795/hs_err_pid4616.log)

**Comment by aseth1** [comment]
Related to #529

**Comment by aymanhab** [comment]
Likely because of fixes to API ComponentPath search, this works fine for me as long as the frame change does not result in an invalid multibody-tree. The fix in that case would likely be to undo the edit so we have a valid model/state under the GUI.

**Comment by aymanhab** [comment]
Can you verify @aseth1 if this is fixed by core fixes? Thanks

**Comment by aseth1** [comment]
Open gait2392_simbody.osim with Windows build OpenSim e07981e0-2018-05-15

- Update hip_r parent to ground takes 5-8 seconds to update the model in the visualizer with no feedback  (hourglass or spinning color wheel) during that time. 
- Connecting a frame to itself provides the error message from the Exception thrown in Joint.
- Connecting a frame to a frame that is on the same base frame (e.g. a `PhysicalOffsetFrame`) also provides a an error window, but it is blank. A secondary "Information" window opens with the detailed message from the Exception thrown in `Model::createMultibodyTree()`
![image](https://user-images.githubusercontent.com/6494122/40199805-762b109a-59cf-11e8-8624-3f54c6d959e0.png)
It then requires clicking OK three times: *Information*, blank *Error*, and then *Information* pops up again with the same message.  After 5-8s the view updates to be from top looking down with view tumbling tied to the mouse. GUI periodically crashes thereafter.
[hs_err_pid20384.log](https://github.com/opensim-org/opensim-gui/files/2014511/hs_err_pid20384.log)
- connecting the *hip_r* parent to *tibia_r* crashes OpenSim but two dialog windows upon just before that happens (but cannot read the message).  The out.log indicates an issue with tibia_r not being connected by a Joint and creating a slave body:
```
Body 'tibia_r' not connected by a Joint.
A FreeJoint will be added to connect it to ground.
Body 'tibia_r_slave_0' not connected by a Joint.
A FreeJoint will be added to connect it to ground.
```
Crash  log:
[hs_err_pid13888.log](https://github.com/opensim-org/opensim-gui/files/2014571/hs_err_pid13888.log)

**Comment by aymanhab** [comment]
In debug mode, there's exception thrown in the last scenario, message displayed below. Crash likely due to corrupt system downstream.
![capturesimtkexception](https://user-images.githubusercontent.com/3972208/40584178-d7230b08-6151-11e8-9843-f9655b307b41.JPG)

**Comment by aseth1** [comment]
@aymanhab only the fourth issue is related to the API. The third point with multiple windows and empty message remains a GUI issue. 

I will investigate the fourth. Likely there are topologies that are impossible/excessively challenging to satisfy and created by connecting in some random way (as in testing) and we likely need a way to catch those situations. If I catch and throw with an invalid model configuration (or topology) message, I think that will suffice. Yes?

**Comment by aymanhab** [comment]
Definitely, thanks @aseth1

**Comment by aymanhab** [comment]
I don't get the blank info messages any more. the last scenario (4) produces this dialog
![capture587](https://user-images.githubusercontent.com/3972208/42971335-b90f7e42-8b60-11e8-824b-df2a21a2bfe3.PNG)
then crashes. Nothing to do for this one on GUI side AFAIK.
