### ISSUE TITLE
TableReporter generated .sto files are not readable by the Plotter

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#588]
### Steps to reproduce
Run AnalyzeTool with an OutputReporter on any model.
(OR, use Scripting to add a `TableReporter` to a model and simulate.)
 
### Expected result
Results table(s) written to .sto file(s).
Can open .sto files in the plotter and plot the results.

### Actual result
Table(s) written to file(s).
Using plotter to fails to load .sto file due to failure to parse headers of the file:

![image](https://user-images.githubusercontent.com/6494122/37313317-e6d37028-260b-11e8-907d-7992a9fcb956.png)

Also file is apparently corrupt or invalid:
![image](https://user-images.githubusercontent.com/6494122/37313378-20dc1536-260c-11e8-84d5-cfd4e2be641d.png)

The file is neither corrupt nor invalid.  For some reason the GUI still requires that Storages declare the number of rows and columns as uses it to parse results files. The STOFileleAdapter does not have that requirement.

### Environment and GUI version
[Recent Windows build](https://www.dropbox.com/home/DevBuilds/frameEditBuild).

**Comment by chrisdembia** [comment]
Related: https://github.com/opensim-org/opensim-core/issues/2120

**Comment by jenhicks** [comment]
For the workshop, the steps I tried:
- Get ISB 2017 tutorial files (on simtk.org under Beta releases)
- Load jumper model
- Run IK
- Launch analyze tool, using IK results as motion
- Add OutputReporter analysis
- Add hand_r/position as an output
- Run analysis
- Try to plot results

The other potential issue I see is that the results are a vec3 separated by commas. Will the plotter be able to parse and allow user to select x, y, or z coordinate?

**Comment by aymanhab** [comment]
This could have been addressed by earlier fixes to Storage constructor but that needs testing, and the issue needs to be addressed on API side.

**Comment by jenhicks** [comment]
In the 3-18 build I am able to plot OutputReporter results that are scalar.

**Comment by jenhicks** [comment]
I was able to plot vec3 outputs from the OutputReporter with no issue. In the plotter, columns show up as position_x, position_y, etc.
