### ISSUE TITLE
Ground is not an available Frame when creating ExternalLoads and Motion Objects

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#591]
### Steps to reproduce
- Load leg6dof9musc or any other model.
- Load a motion file (e.g stance IK) and associate the ground reaction forces with the motion. 
- Then right click "Edit Motion Objects" and select one of the forces and click "Edit"
- it opens the panel identical to the ExternalLoads editor that allows you to associate forces, points and torques with PhyscialFrames in the model.

### Expected result
We are able to provide *Expressed in* frame for Forces and Points as **ground**.

### Actual result
![image](https://user-images.githubusercontent.com/6494122/37305737-b726e6c0-25f2-11e8-9fe6-ee04f02701a1.png)

We cannot select ground as *Apply to* or *Expressed in* frame from the provided pulldown list.

### Environment and GUI version
Not version specific.  On all 4.0 beta versions to date.

Remaining issue from list of *Ground* related issues #5.

**Comment by jimmyDunne** [comment]
Ground is available (W10, OpenSim-ba958aac-2018-04-30_threejs_r91.zip)

![ground_external_loads](https://user-images.githubusercontent.com/5296507/39552990-75061c7e-4e20-11e8-9fe7-52a99ded3d71.png)
