### ISSUE TITLE
Running OutputReporter Analysis loads a motion named UNKNOWN

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#594]
### Steps to reproduce
Ran OutputReporter Analysis with CMC results

### Expected result
Not sure -- does running analyze usually generate a motion in the GUI?
I wouldn't expect a motion named UNKNOWN, in any case

### Actual result
Motion is loaded and named "UNKNOWN"

(include screen grabs where appropriate)

### Environment and GUI version
Windows 10 VM

**Comment by aymanhab** [comment]
Since you can run AnalyzeTool on a loaded motion or on a motion from a file it's likely the tool will animate whatever  specified input motion. If motion was already loaded/used then we shouldn't add new motion, if not we should find out where the "UNKNOWN" motion originated

**Comment by aymanhab** [comment]
@jenhicks Reports the motion was created by GUI, rename to AnalysisResults

**Comment by aymanhab** [comment]
@jenhicks I'm having a hard time reproducing the "UNKNOWN" motion, can you keep an eye or give me the steps needed? The GUI explicitly names the Storages it creates as (Results) as far as I can tell. Thanks

**Comment by jenhicks** [comment]
Load gait2354
Launch Analyze tool
Load states from CMC (in the output ref)
Add an OutputReporter ... I chose a muscle and the active_fiber_force output
Run the tool
You'll see the UNKNOWN

You should also see the message about renaming the reporter due to duplicates that I mentioned in my email.

**Comment by aymanhab** [comment]
Fix in core PR 2125 (https://github.com/opensim-org/opensim-core/pull/2125)

**Comment by jenhicks** [comment]
Windows 10 VM: motion is now labeled "states"

**Comment by jimmyDunne** [comment]
Shows states on W10. 

Build: 04-27-18
