### ISSUE TITLE
User is asked to decide where to put models and scripts but is not given the information necessary to make a good decision

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#601]
### Steps to reproduce
Start OpenSim.

### Expected result
GUI provides information to user when it's needed.

### Actual result
A dialog box appears requesting location for models and scripts directory, but the user is not told (1) why these files don't already reside in the same directory as the software; (2) what operation is actually occurring (e.g., unzipping from a local file, not downloading from simtk.org); (3) about how much space is about to be consumed, how many files are going to be copied, or how long the operation will take; (4) what the user should consider when choosing a directory (e.g., not in a system directory like Program Files on Windows); (5) the fact that the operation can be repeated by… [I think there's a way but haven't tried]. A few sentences in the dialog box would be sufficient.

### Environment and GUI version
AppVeyor artifact OpenSim-0d41eef3-2018-03-14.zip

**Comment by aymanhab** [comment]
Good idea Tom. Please propose text and we'll try to fit it in. :+1:

**Comment by jenhicks** [comment]
Here is my attempt at a description.

"Please select a location to install OpenSim models and examples (~XX MB will be copied from the OpenSim installer). You should have permissions to read/write from this folder.  To reinstall the resources at anytime, type "installResources()"

**Comment by tkuchida** [comment]
> "Please select a location to install OpenSim models and examples (~XX MB will be copied from the OpenSim installer). You should have permissions to read/write from this folder. To reinstall the resources at anytime, type "installResources()"

I don't think the models and examples are being "installed". Perhaps "Please choose a location for the OpenSim models and examples (…"? Also, anytime -> any time, and "type installResources() in the ScriptingShell Window"?

**Comment by jenhicks** [comment]
V2 (not sure why the end of my sentence got cut-off) ... thanks Tom!

Please choose a location for the OpenSim models and examples (~XX MB will be copied from the OpenSim installer). You should have permissions to read/write from this folder. To reinstall the resources at any time, type "installResources()" in the ScriptingShell Window.

**Comment by chrisdembia** [comment]
Proposed edits:

- "models and examples " -> "resources (models and examples)" (it is useful to have a specific term for this folder, so that documentation can say "navigate to your resources folder."
- "will be copied from the OpenSim installer" -> "will be copied" (technically, the source files are not in the installer at this point).

**Comment by jenhicks** [comment]
Please choose a location for the OpenSim resources (models and examples). Approximately XX MB will be copied. You should have permissions to read/write from this folder. To reinstall the resources at any time, type "installResources()" in the ScriptingShell Window.

**Comment by jenhicks** [comment]
@aymanhab There is a lot of extra spacing in the message. Could you remove extra linebreaks?

**Comment by aymanhab** [comment]
![captureinstallresources](https://user-images.githubusercontent.com/3972208/38639668-c5bf4e88-3d86-11e8-8202-89035477e36b.JPG)
Does that look better? Layout may differ on osx

**Comment by jenhicks** [comment]
This seems better.  A period seems to be missing after "Window".

**Comment by chrisdembia** [comment]
Could the title bar text be updated to say "OpenSim resources" or "Choose a location for OpenSim resources"?  @tkuchida suggested avoiding the word "install." I don't know if this means we should also rename the `installResources()` function; I don't have any suggestions for alternative names.

On Mac, the CMake GUI uses the word "install" to refer to writing symlinks that allow using CMake from the Terminal:

<img width="459" alt="screen shot 2018-04-11 at 3 36 02 pm" src="https://user-images.githubusercontent.com/846001/38646778-33b533fa-3d9e-11e8-8f87-e55d084664b1.png">


I would still like to be able to reinstall resources using a menu bar item rather than using the scripting shell.

**Comment by aymanhab** [comment]
I'm not sure what's @tkuchida objection to using the word install, seems like a reasonable match to the functionality. @chrisdembia there's a class that maps scripting shell commands to actual functions so the internal name could stay the same even if we change the scripting shell command. Is everybody on agreement as to how to title the dialog? I think we should stick with something that refers to "Resources" for consistency.

**Comment by tkuchida** [comment]
> I'm not sure what's @tkuchida objection to using the word install, seems like a reasonable match to the functionality.

To me, the word "install" implies that there's more going on than a straightforward copy (e.g., creating registry entries). If you tell me that you've installed something, I would want an uninstaller to get rid of it; just deleting files that appear during an installation is generally not recommended. From [wikipedia](https://en.wikipedia.org/wiki/Installation_(computer_programs)): "Because code is generally copied/generated in multiple locations, uninstallation usually involves more than just erasing the program folder. For example, registry files and other system code may need to be modified or deleted for a complete uninstallation."

**Comment by chrisdembia** [comment]
What do we all think of `copyResources()` instead of `installResources()`? The word "install" implies those same things for me as @tkuchida mentioned but I still prefer `installResources()`.

One reason I prefer `install` to `copy` is that `copy` might imply the user knows the source of the copy, when we actually want to obscure where the files are being copied from (at least that's my opinion).

**Comment by jenhicks** [comment]
I prefer install for the reason Chris states.

**Comment by tkuchida** [comment]
Then I recommend informing the user that there is no uninstaller and they can delete/move the files without issue. Installers sometimes show a "details" window that lists every operation being performed; might consider showing this with each line being `Copying <source> to <destination>...`.

**Comment by chrisdembia** [comment]
Here is a revised proposal for the text in the dialog:

> Please choose a location for the OpenSim resources (models and examples). Approximately 60 MB will be copied. You should have permissions to write to this folder. To reinstall resources at any time, type "installResources()" in the ScriptingShell Window. Resources can be uninstalled by manually deleting the resources folder and updating the "OpenSimResourcesDir" preference (in Edit > Preferences...).

1. It would be nice if the first sentence were black and the rest of the text were gray (like it is now).
2. Consider placing the text starting from "To reinstall" below the text box.
3. Consider renaming the "OpenSimResourcesDir" preference to "Resources Path" or "ResourcesDirectory" for consistency with the "Geometry Path" or "WorkDirectory" preferences ("Dir" is currently used to mean "direction", in "DisplayOffsetDir").

**Comment by aymanhab** [comment]
Thanks @tkuchida and @chrisdembia Looks great. The preference "OpenSimResourcesDir" was kept in case user forgets where he/she installed so we can tell them or in case we use that folder in the future but is never used by the code, at least for now. I'd lean to remove references to it from the Dialog. Thoughts?

**Comment by jenhicks** [comment]
Looks good on Mac.

**Comment by aseth1** [comment]
Verified that message appears on Windows as follows:

![image](https://user-images.githubusercontent.com/6494122/43102641-8598700a-8e80-11e8-9bc7-afc5cab90b72.png)

Note, this required calling  `installResoruces()` manually in the GUI's scripting shell. I have not had the installer ask to install resources in at least a month.
