### ISSUE TITLE
no OpenSimConfig.cmake after build

### ISSUE THREAD

**Issue by idhamari** [opensim-org/opensim-gui#606]
Dear all,
I successfully built openSim 4.0 from the source in my ubuntu 16 using superbuild . There is no bin folder in my build so I added the build folder to the path. The problem now is there is no OpenSimConfig.cmake in the build folder. I need this file to build the GUI. 
Any suggestion?
Regards!
Ibraheem

**Comment by chrisdembia** [comment]
Hey Ibraheem:

OpenSimConfig.cmake is in the install directory, not the build directory. As mentioned in the README for this repo, we do not provide support for building the GUI from source.
