### ISSUE TITLE
leg6dof9musc replay of IK solution has disconnected patella

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#617]
### Steps to reproduce
 - load leg6dof9musc.osim model from Models with distribution. 
 - load the Swing/leg69_IK_swing.mot motion file
 - press play.

### Expected result
Swing motion plays and all patella is constrained to the knee. 

### Actual result
Overall leg motion is correct but the patella does not track the femur.
<img width="477" alt="screen shot 2018-03-22 at 9 45 27 pm" src="https://user-images.githubusercontent.com/6494122/37812664-59bd31ea-2e1e-11e8-848a-0a26e1d3d95c.png">

This seems to be a constraint enforcement issue, because when a coordinate slider is manually adjusted, the patella snaps back into place. 

This is likely related to #608 since the vectorized setting of state values does not enforce constraints. It expects that state values were obtained by satisfying constraints. Although IK computes the constrained  `knee_angle_pat_r` value (constrained to be the knee_angle), it does not report the constrained coordinate value, and `Model::formStateStorage` will use its default value.

The fix here is to add a final `Model::assemble(s)` for good measure OR detect when the input files are motions (e.g. does not have a complete state) and then do the assemble.

### Environment and GUI version
Windows [build 0321](https://www.dropbox.com/home/DevBuilds/build0321)

**Comment by aymanhab** [comment]
Thanks for the find @aseth1 Can you advise as to where to assemble()? e.g. right after calling setStateVariableValues? Should we do this only if there are constraints in the model, for efficiency? Also wouldn't that break #540 again if we assemble since constraints will be enforced? Thanks

**Comment by aseth1** [comment]
`Model::assemble()` will only assemble if there are constraints. For #540 the fix was to move clamping within the enforce constraints check, so the assemble should not push the values within the bound. What did you observe in #620?

**Comment by aymanhab** [comment]
Fixed by PR #620, Please verify and close as needed.

**Comment by jenhicks** [comment]
This is fixed on my Mac (3-26 build)

**Comment by jimmyDunne** [comment]
Fixed on W10.

Build 04-27-18
