### ISSUE TITLE
Can't manually enter floor height in visualizer controls

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#624]
You can only use the slider, which makes it hard to get precisely to a desired floor level.

**Comment by tkuchida** [comment]
@jenhicks If I click and drag the slider left/right, I can get floor heights of ..., -0.13, -0.08, -0.04, 0.01, 0.05, 0.1, 0.14, ..., but I've discovered that you can click and drag up/down on the number itself. With a mouse (not laptop trackpad), I get resolutions of 0.01 that way. Ideally, I agree that the user should be able to enter a number in the textbox. Further, I don't think it should be possible to change numeric values by dragging them up/down.

**Comment by aymanhab** [comment]
Although selecting text has side effects of changing value due to gesture interpretation, but you can manually enter values now in the latest build

**Comment by tkuchida** [comment]
I opened a model and clicked in the textbox beside the "Floor > Height" slider, then pressed the left arrow key on my keyboard to move the cursor back one character and the model moved in the Visualizer. Should I open a new Issue?

**Comment by tkuchida** [comment]
Also, the backspace key doesn't seem to work.

**Comment by aymanhab** [comment]
@tkuchida the interaction between the Visualizer Control menu and the 3D view is already an open issue (although it specifies the floor dropdown, it's across the board), but please open an issue so it doesn't fall through the cracks

**Comment by tkuchida** [comment]
> please open an issue so it doesn't fall through the cracks

Opened #648.

**Comment by jimmyDunne** [comment]
Issues raised in 648 are still present and make it difficult to make manual edits. Will test again and  move/close this once #648 is fixed.

**Comment by jimmyDunne** [comment]
Backspace is working but arrow keys are not. 
W10, OpenSim-8d665089-2018-05-03.zip

**Comment by tkuchida** [comment]
> Since you can manually enter what you want, I think this should be closed.

Original issue has been addressed (per @jimmyDunne's testing). Arrow key issue already covered by #648.
