### ISSUE TITLE
Floor texture changes when up/down keys are pressed even after Controls window has been closed

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#625]
### Steps to reproduce
- open a model
- open the Controls window (click *Open Controls* in the top-right corner of the Visualizer Window)
- expand "Floor" option
- select the "graybricks" texture from the drop-down box
- close the Controls window (click *Close Controls* at the bottom)
- press the up/down arrows on the keyboard

### Expected result
The camera moves up and down.

### Actual result
The camera moves up and down. The floor texture also changes, cycling through the textures as if selecting them from the drop-down box.

### Environment and GUI version
AppVeyor artifact OpenSim-587ee9d9-2018-03-21.zip

**Comment by jenhicks** [comment]
I see similar behavior on Mac

**Comment by jimmyDunne** [comment]
Issue persists (OpenSim-ba958aac-2018-04-30_threejs_r91.zip).

![floor_changes](https://user-images.githubusercontent.com/5296507/39540767-82ff8090-4df8-11e8-9d71-a373dec03f57.gif)

**Comment by jenhicks** [comment]
Fixed on my Mac as well
