### ISSUE TITLE
Only floor texture selection is persistent on GUI open/close

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#626]
Other visualizer controls revert to default.

**Comment by aymanhab** [comment]
@jenhicks my earlier plan was to enable saving scene including not only these but also lights and camera position but that's a bit too much for 4.0 timeline. Let me know which subset you'd consider 4.0 worthy. Thanks.

**Comment by aymanhab** [comment]
Changed initialization code so that background color is also preserved, in latest build.
