### ISSUE TITLE
Latest intaller (03-26) uses 3.3 style application icon instead of 4.0. 

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#628]
### Steps to reproduce
Install OpenSim build 0326_01 from [here]( https://www.dropbox.com/home/DevBuilds/build0326_01)

### Expected result
![image](https://user-images.githubusercontent.com/6494122/37929471-eb9736a0-30f4-11e8-9401-b5b3830caf22.png) both on the opensim64.exe in explorer and on application dock.

### Actual result
![image](https://user-images.githubusercontent.com/6494122/37929414-c8a057f8-30f4-11e8-9a56-eeb8f8bea61e.png)

### Environment and GUI version
Listed above.

**Comment by aymanhab** [comment]
We don't have an "ico" file with the "4.0" style, we have to have these in sizes 48x48, 32x32, 16x16

**Comment by jenhicks** [comment]
![opensimlogowindows_48](https://user-images.githubusercontent.com/4510959/37931238-dba8eb4e-30f9-11e8-9ca7-d78b00028420.png)

We had tried adding an outline to the logo, but perhaps making the jumper dude grayscale would look better

**Comment by jenhicks** [comment]
@aymanhab I just emailed you some new icons. Let me know if there are issues.

**Comment by aymanhab** [comment]
Ok, thanks @jenhicks though not showing up yet, maybe Dropbox easier?

**Comment by jenhicks** [comment]
I emailed you a dropbox link

**Comment by aymanhab** [comment]
Fixed in latest posted installer, thanks @jenhicks for the icons

**Comment by aseth1** [comment]
I don't see the fix. There is no application icon associated (just default provided by netbeans) with OpenSim. This on Windows installer OpenSim e07981e0-2018-05-15:

![image](https://user-images.githubusercontent.com/6494122/40323882-a8469b7a-5ceb-11e8-89d4-b9fbbb65f713.png)

**Comment by aymanhab** [comment]
@aseth1 the change of the icon is done using a tool that's not integrated into the automated build process. @chrisdembia was working on the integration on appveyor last week. Not sure where it stands but worst case we can do this manually for actual release builds.

**Comment by chrisdembia** [comment]
I started working on this at the end of last week. I hope to find some time to continue working on it this week but no guarantees.

**Comment by aseth1** [comment]
I think this can be easily verified on a manual build, so @chrisdembia don't worry about it while you are away.

**Comment by chrisdembia** [comment]
A related issue is that the icon used in the installer contains the older logo (upper left corner of the window; not the mini icon in the toolbar):

<img width="492" alt="screen shot 2018-05-30 at 8 38 20 pm" src="https://user-images.githubusercontent.com/846001/40754856-6df4c4fa-6449-11e8-82e8-afa365242717.png">

**Comment by aymanhab** [comment]
@jenhicks do yo think this is worth fixing 4 4.0?

**Comment by jenhicks** [comment]
If you mean that the logo coming out of the box is the old-style one, no I don't think this should hold up the release.
