### ISSUE TITLE
Unhiding a hidden model reveals all its wrapping surfaces and turns muscles red

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#644]
### Steps to reproduce
- Load two models.
- Load two motions, one for each model.
- Associate motion data.
- hide one Model
- hide the other
- unhide a the first model

### Expected result
The unhidden model appears exactly as it appeared when it was hidden.

### Actual result
- Wrapping objects now appear
- muscles turn red irrespective of the state they were in when hidden

<img width="940" alt="screen shot 2018-04-01 at 7 25 38 pm" src="https://user-images.githubusercontent.com/6494122/38180653-115ee3d6-35e3-11e8-941e-3250c8829dbe.png">

### Environment and GUI version
Mac OpenSim 651d29f-2018-03-30

**Comment by jenhicks** [comment]
I tested this with Apoorva's model on my Mac and I don't see the wrapping surfaces appear or muscles turn red after following the steps that @aseth1 describes.

**Comment by jimmyDunne** [comment]
Used Apoorva's model and states files. The wrapping surfaces do not open when 'show' is selected on the top level model. 

System:W10
Build:04-27-2018
