### ISSUE TITLE
Backspace and arrow keys do not work as expected when editing floor height using keyboard

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#648]
### Steps to reproduce
- open a model
- click "Open Controls" in top-right corner of Visualizer Window
- click "> Floor"
- click in textbox beside "Height" slider
- (a) press left and right arrows on keyboard to move cursor left and right
- (b) move cursor to the right of a character and press backspace key

### Expected result
- (a) cursor should move left and right in the textbox; nothing else should change
- (b) pressing backspace should delete the character to the left of the cursor

### Actual result
- (a) cursor moves left and right in the textbox, but the model also moves left and right
- (b) pressing backspace has no effect

I would expect most users to use the backspace key when editing the height. Then, when that doesn't work, they will press the left arrow key and use the delete key instead---but pressing the left arrow key moves the model.

### Environment and GUI version
AppVeyor artifact OpenSim-4077dd7b-2018-03-29.zip

**Comment by jimmyDunne** [comment]
Issues still exists on (OpenSim-ba958aac-2018-04-30_threejs_r91.zip, W10)

![floor_changes](https://user-images.githubusercontent.com/5296507/39540575-e0d561ae-4df7-11e8-9c05-3cb28437bd13.gif)

**Comment by aymanhab** [comment]
@jimmyDunne the threejs branch doesn't have the latest fixes on master, only threejs upgrade for code base of last week. I can merge master but the main issue is WebGL support, were you able to test/verify that? Thanks

**Comment by jimmyDunne** [comment]
Backspace now works! The arrow keys don't 😢 
When the text boxes are selected and I press the arrows, the scene camera changes. We would expect that left-right arrows would move the cursor and up-down keys would do nothing. 

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/5296507/39590919-15ddde70-4eb7-11e8-98c7-d81acd2f1b28.gif)

**Comment by jimmyDunne** [comment]
Ayman and I met to discuss the use of arrow keys in the text boxes. We agree that long-term we would like to use the arrow keys to move the text box cursors, but the implementation of this may be too time-consuming right now. Since the backspace works, the use of arrow keys is secondary. We will document that the arrow keys are only for moving the camera and we can try to add this in a future release.

**Comment by jenhicks** [comment]
Sounds good ... closing.
