### ISSUE TITLE
Visualizer doesn't display first frame when previewing experimental data

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#653]
### Steps to reproduce
- File -> Preview Experimental Data...
- Select Gait10dof18musc\ExperimentalData\subject01_walk.trc

### Expected result
- Data loads, visualizer displays first frame, camera adjusts appropriately

### Actual result
Camera is zoomed in on one marker (reported in #508):
![](https://user-images.githubusercontent.com/4203505/38527683-decf3a68-3c10-11e8-81fe-daac4676ddc3.png)

Unlike in #508, there are now no other markers after zooming out:
![](https://user-images.githubusercontent.com/4203505/38527689-e37dc25a-3c10-11e8-8378-e6450c00ca5c.png)

Markers appear after forcing time update (in this case, I clicked the :previous_track_button: button):
![](https://user-images.githubusercontent.com/4203505/38527694-e99d1e24-3c10-11e8-90f1-24ddf0ff19f4.png)

### Environment and GUI version
AppVeyor artifact OpenSim-587ee9d9-2018-03-21.zip

**Comment by jimmyDunne** [comment]
Markers loaded and (appears) to open at correct frame of data (no erroneous marker on first frame)

**Comment by tkuchida** [comment]
@jimmyDunne What environment and build were you using? Please test with this file: [test.zip](https://github.com/opensim-org/opensim-gui/files/1931194/test.zip) (contains test.trc). On my machine using AppVeyor artifact OpenSim-dbbbb0c5-2018-04-16.zip, when I preview the first time, the camera is looking at nothing and I can't find the markers:
![](https://user-images.githubusercontent.com/4203505/39037086-511f08a2-4434-11e8-94c2-bea050b3686a.png)
The markers appear after *File > Close All* and previewing a second time.

**Comment by jimmyDunne** [comment]
Hey, @tkuchida. I used the .trc you included (thanks!).  Below is a gif of me trying to hunt for the markers. When I 'preview experimental data', there are no markers seen. I then have to search the space by trying a few different views until I 'spot' a marker and focus in. 

![marker_hunt](https://user-images.githubusercontent.com/5296507/39062464-6f4723da-447c-11e8-9989-cbf708c54910.gif)

So, it is important to know that I already knew where these markers were and I still could not center on them easily- to find them originally I had to open a model, or some data, that was close to the global origin. As far as I can see visualizing the global XYZ axis like we could in 3.3 so you get lost easily if the markers are far off the initial camera pose.

I have opened a issues for the camera changing position when data is opened (#675) and drawing a Global to help find where you actually are (#676). But I would also like to suggest that (i) Markers (both experimental and model) have a too small a default radius, (ii) The default color for markers aren't as 'bright' as in previous versions which also makes it harder to spot. 

Tom, are there any other issues I can open here? I feel that #447 could also apply here; if the marker data is far off the screen, you select a marker in the navigator, and press on of the camera view buttons, then the camera should center of the marker that is selected. Let me know if that makes sense.

**Comment by jimmyDunne** [comment]
> Are there different TRC versions that are handled differently, or are the markers in my TRC file just further from the origin and thus more difficult to find?

The markers in the TRC you provided are relatively far from the Origin and, with the camera issues I suggested above, it is very difficult to find them. When I open another trc that is close to the origin I don't have the same issue.
