### ISSUE TITLE
An extra marker is shown when experimental data is previewed the first time after starting the GUI

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#654]
### Steps to reproduce
1. Start OpenSim
2. File -> Preview Experimental Data...
3. Select Gait10dof18musc\ExperimentalData\subject01_walk.trc
4. File -> Close All
5. File -> Preview Experimental Data...
6. Select Gait10dof18musc\ExperimentalData\subject01_walk.trc

### Expected result
- Data loads, visualizer displays first frame, camera adjusts appropriately
- The user should see no difference in the GUI following steps 3 and 6

### Actual result
**After step 3 (red circle added):**
![](https://user-images.githubusercontent.com/4203505/38528119-0cd69a26-3c13-11e8-9c8a-29613892dda7.png)

**After step 6:**
![](https://user-images.githubusercontent.com/4203505/38528052-cfb0a0e2-3c12-11e8-83c2-42ef560e4b00.png)

### Environment and GUI version
AppVeyor artifact OpenSim-587ee9d9-2018-03-21.zip

**Comment by jimmyDunne** [comment]
Repeating the steps above, with described data as well as new files, the 'Ghost' marker did not appear.

**Comment by tkuchida** [comment]
Fixed on AppVeyor artifact OpenSim-d8bfa962-2018-05-09-win64.exe
