### ISSUE TITLE
Static Optimization Tool window is really wide on Mac

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#656]
I just downloaded and installed OpenSim 03d9220-2018-04-09.

The Static tool is very wide. I don't recall this being an issue on other releases.

**Comment by jenhicks** [comment]
<img width="656" alt="staticwindow copy" src="https://user-images.githubusercontent.com/4510959/38631427-93d8de6a-3d6e-11e8-9acd-fb89b19438ec.png">

**Comment by aymanhab** [comment]
Can you look into this @chrisdembia? Thanks

**Comment by aymanhab** [comment]
Looks perfectly normal on my iMacPro

**Comment by jenhicks** [comment]
Closing ... this may have been an isolated incident that resulted from switching from my external monitor to built-in display.
