### ISSUE TITLE
Preference to persist models results in error message on osx launch - turn off by default

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#657]
Since this is no longer supported

**Comment by aymanhab** [comment]
Actually in my own windows environment, this works fine the two issues that I need help with are:
1. Whether it works on osx, 
2. Where to keep the AppState.xml file then
3. If this continues to work on other slow machines (when it is slow to launch server etc.)

Thoughts on OSX, @chrisdembia ? We could switch to using UserDirectory as defined by NetBeans. http://wiki.netbeans.org/FaqWhatIsUserdir

**Comment by jenhicks** [comment]
As of OpenSim ed2365e-2018-04-12, persist models does not work on osx.

**Comment by jimmyDunne** [comment]
Persist Model On works. Also, when switching to Off, no model is opened on reboot. 
W10. OpenSim-8d665089-2018-05-03.zip

**Comment by aymanhab** [comment]
Awesome, need to try latest build on osx

**Comment by jenhicks** [comment]
5-31 build on OSC: With the persist model option on, I almost always get the error message "This site can't be reached". If I click the blue "reload" button in the bottom right corner, the visualizer will appear.
