### ISSUE TITLE
Selecting experimental Markers don't give feedback to users on selection

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#664]
### Steps to reproduce
Load any trc file in Preview mode, in 3D view select one Marker

### Expected result
Some feedback to user which marker is selected (e.g. pick in navigator)

### Actual result
Exception thrown

(include screen grabs where appropriate)

### Environment and GUI version
latest as of 04-11-2018

**Comment by jimmyDunne** [comment]
With the latest build (OpenSim-04-16-2018), when I select markers in the visualizer, the marker is highlighted in the navigator and the name is displayed in the bottom left-hand corner of the GUI. 🎉 

![marker_selection](https://user-images.githubusercontent.com/5296507/38887123-d07240c4-422c-11e8-8917-756c9a3f2b91.png)



#670 
W10
opensim-04-16-2018
