### ISSUE TITLE
Immediately after Scale and IK, motion playback fails. 

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#665]
### Steps to reproduce
Scale the Hamner running model. With the scaled model, run IK. Try to play the motion in the GUI

### Expected result
Motion of the IK trial would play

### Actual result

![hamner_running](https://user-images.githubusercontent.com/5296507/38703463-d4042240-3e92-11e8-9710-e7e2b5e52d53.gif)

### Environment and GUI version
Windows 10
opensim-04-11-2018

### Notes
I repeated the sequence (scale, IK, play motion) using the gait2392 pipeline data. I didn't get 'unplayable' motion like here, but it was very choppy and, if I messed with the motion slider, it would eventually stop playing the motion (though the motion slider kept moving)

**Comment by tkuchida** [comment]
There might be some relevant discussion/investigation on #283.

**Comment by aymanhab** [comment]
Looks more like #333 with the issue being multiple models in the visualizer rather than the type of motion. Would be good to see if replacing IK results with CMC results would be different. We now convert all motions to states on loading so they all should perform relatively similar.

**Comment by jimmyDunne** [comment]
model is located in opensim-org/opensim-models/Models/Hamner

**Comment by aymanhab** [comment]
There was a blip during the first couple gait cycles but afterwards smooth sailing. Not sure there's a bug here, frame rate is a bit high  (rendering 60 frames per second)

**Comment by jenhicks** [comment]
I see the same results that you report @aymanhab . These steps do seems to tax the visualizer a bit, but I see a smooth motion after a couple gait cycles. This is testing on Mac. I'm going to mark it as verified on Mac OSX

**Comment by aseth1** [comment]
On Windows OpenSim_cea85df3-2018-07-18 Scale->IK was smooth. It solved IK while animating smoothly for 600 frame in under 12s. Upon pressing the motion play back to replay, the replay was froze and then was jerky, choppy. Stopping and replaying was then smooth looked like how it was playing when IK was solving. This behavior is kind of odd. One would expect the replay (no solving at all) to be at least as fast as when IK is solving without any initial hiccups.

**Comment by aseth1** [comment]
@jenhicks should we create a new issue for the initial hiccup/choppiness or hold back from confirming this as verified?

**Comment by jenhicks** [comment]
From my testing, the performance seems good enough, so I think we could mark as verified and create an issue for further optimization.

**Comment by aymanhab** [comment]
To prove that the issue is multiple models, I closed the original model post scaling and IK animated smoothly without a hitch.
