### ISSUE TITLE
External Loads pane returns exception when trying to Specify Forces/Torques for model

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#666]
### Steps to reproduce
Open (scaled) gait2392, load motion, open RRATool, edit external loads, specify Force data file, click add (also happens with loaded external forces (xml) and clicking edit). 

I have repeated this procedure with three different models and data, all had the same error.

### Expected result
I should be able to edit or add the 'Specify Forces/Torques for Model' pane.

### Actual result
Red ring of death. 

![external_loads_error](https://user-images.githubusercontent.com/5296507/38706104-8d2ddb00-3e9b-11e8-9fd9-47fefc1151bc.gif)

### Environment and GUI version
opensim-04-11-18
Windows10

**Comment by aymanhab** [comment]
#585

**Comment by jenhicks** [comment]
I'm going to keep both open. This one has a more informative title as far as the external loads issue. And we should also verify the 2354 pipeline works out of the box.

**Comment by aymanhab** [comment]
Making a clone fixes the crash going in, there's still an issue with using "ground" which is not a Body and is a valid/default option for get/setXXXXXXBodyName methods. Will switch to use PhysicalFrame underneath but that may expose problems somewhere else. Testers beware.

**Comment by jimmyDunne** [comment]
I am able to edit existing external loads defined from a setup file, but whenever I select 'Add' the entire application crashes.

![external_loads_crash](https://user-images.githubusercontent.com/5296507/39273265-25bba266-4893-11e8-8454-63e08a451c5c.gif)

The stack trace is here;
[hs_err_pid25416.log](https://github.com/opensim-org/opensim-gui/files/1948874/hs_err_pid25416.log)

Testing models/data can be found in Dropbox/OpenSim Beta Testing Files\4.0 Testing\external_loads_works

**Comment by aymanhab** [comment]
Catch 22 with creation of ExternalForce from data file is that you need valid labels/IDs to connect the new ExternalForce to the model but labels/IDs aren't available until edit time. Creaton and Edit can't reuse the same code which is a bummer. Investigating options.

**Comment by jimmyDunne** [comment]
Can add and edit external loads. Can make external loads from scratch 🎉 
W10, OpenSim-a0d644b3-2018-05-04.zip
