### ISSUE TITLE
Walker Model only appears when second model is opened

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#672]
### Steps to reproduce
Open Walker model with magnet knees and feet. Open any typical gait model

### Expected result
When you open the Walker model, the model should be viewable. 
### Actual result
Walker model is not seen until a second model is opened

![walker_model_missing](https://user-images.githubusercontent.com/5296507/38951094-5b5f01de-42fc-11e8-87e2-ec41f37bb513.gif)

### Environment and GUI version
W10, build 04-16-18

**Comment by aymanhab** [comment]
@jimmyDunne The likely issue (unless you're menu picking very fast or model loading is extremely slow on your machine) is that there was an error loading the walker model that aborted the visualization process and the second  model loading cleared the pipe. Please point me to the specific version of walker model you used. Thanks

**Comment by jimmyDunne** [comment]
The testing folder for this is in Dropbox/DevBuild/Testing/walker_with_magnet

**Comment by jimmyDunne** [comment]
Fixed.
