### ISSUE TITLE
Visualizer Window buttons are missing frames

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#680]
### Steps to reproduce
Open a model.

### Expected result
Buttons in Visualizer Window have frames around them so the user knows where to click.

### Actual result
Buttons are missing frames. Also, the lens in the camera icon is not filled.

![](https://user-images.githubusercontent.com/4203505/39099325-fb774ba2-462d-11e8-9b36-b4d23e7cadae.png)

### Environment and GUI version
AppVeyor artifact OpenSim-e5f97340-2018-04-20.zip

**Comment by jenhicks** [comment]
@aymanhab is adding background that appears upon hover.

**Comment by tkuchida** [comment]
Looks great :+1: on AppVeyor artifact OpenSim-bf3e61b9-2018-05-09-win64.exe.

**Comment by jenhicks** [comment]
Also looks great on my Mac. Closing ..
