### ISSUE TITLE
Features in OpenSim 3.3 that are missing or broken in 4.0

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#685]
0. drag and drop models into the 3D view. #422
1. ~~displaying the axes of the OpenSim global view origin in the 3D view, #676~~
2. differentiation of parent and child joint frames in the 3D view (Joint -> Toggle Parent/Child Frame). #550
3. capping of geometry (muscle) paths, #581 
4. selection/moving/editing of muscle/path points in the 3D view, #485
5. Bone/body specific highlighting. In 3.3 the bone geometry was highlighted and 4.0 a yellow wireframe box encompasses the body and it is unclear what inside the box was selected (e.g. a muscle or the bone?)
6. Clicking a view projection button with an object highlighted no longer zooms and centers the highlighted object in the view, #447 
7. viewable and editable absolute Model display-offsets with respect to OpenSim global origin, #88 
8. unexplained offset between experimental data preview and global origin, #538
9. 4.0 pollutes 3.3 preferences (#578)
10. Preferences... -> Marker Display Radius has no effect in either version (#301)
11. Preferences..-> Muscle Display Radius has no effect, #539
12. associate image/texture to a Body/Frame. Useful for overlays silhouetting OpenSim model with subject image in the same pose. Also handy for moving around walls, steps, equipment and other parts of the simulation or just visible stuff in a scene (#705)
13. loading model and pose/scene from previous session (raised by @jryong and others at UEFS) (#688)
14. in many instances (especially after arranging a scene specifically for a high-quality image, e.g. for a publication) the snapshot functionality does not work and provides a blank image of the background color. #299
15. Motion->Color Muscles From File does not work or persist (#701, #161)
16. IK motion files play with colors persistent from previous CMC states file with activations (#279)
17. support for multiple views (#700)
18. camera dolly for movie capture (#892)
19. annotation of selected markers during preview of experimental data (#718)
20. Visualizer is not updated/functional after machine awakens from sleep/hibernation (#523)
21. multiple selection of objects in the 3D view. Cannot select path points to shift all at once or select bodies or markers. (#795)
22. graphical selection of path points and other Objects (Components) to highlight/view in Navigator. (#814)
23. graphical path point editing cannot be undone (#815) 

I don't think this list is exhaustive.  @opensim-org/dev-team please add any items you have come across that are not listed. We should update the list and check off one-by-one as they are verified by users.

**Comment by jenhicks** [comment]
Thanks for the list @aseth1 

As far as tracking issues and testing for the release, while you were on vacation:
1) @aymanhab and I sorted the issues flagged for 4.0 on the Zenhub board. Issues in the Next Up column are high priority to definitely include in the release. Items in the backlog are ones we will get to if time allows.
2) @jimmyDunne created a google doc that builds on the UEFS list and testing lists that we have compiled for past releases. After he verifies the set of issues under "Needs Verifying", he will move to running through this list for testing. https://docs.google.com/spreadsheets/d/1a-1Tz9LacB0Z5QIHLzEfaJJ75iArqwxWbtveJGnn82M/edit#gid=9

If there is anything in your list that does not have an associated issue on github, please file one. If there is anything in the Backlog that you think is a must have for the 4.0 release (by June 1), please comment on the associated issue.

Now that you're back and the paper revision is submitted it would be great to loop you into helping with testing, etc. in preparation for the release. We could discuss how best to do this tomorrow morning (hopefully @aymanhab is feeling better).

**Comment by aseth1** [comment]
@jenhicks I generated this list (referring to issues) because I believe we are not explicitly tracking the functionality being lost as we gain a new visualizer. The individual issues do not capture the scope of the problem. This list makes the losses more evident- at least to me.  I don't think users should expect to lose functionality. If we have different or new ways to accomplish the same things that would be great, but that is not currently the case. I am happy to scratch off the items in the list as they are resolved.  More important, however, is to make sure this list is comprehensive, which it is not. I am hoping the team can contribute to the list.

I agree with including these items in our user testing "protocol" and we should schedule another testing body well before the desired release date.  I have been and will continue to test and provide feedback on functionality throughout OpenSim, GUI and otherwise.

IMHO these issues do not stem from a lack of testing.
