### ISSUE TITLE
Unexpected behavior when hiding/showing bodies

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#686]
### Steps to reproduce
1. open arm26.osim
2. in Navigator, right-click *ground* and select *Display > Hide*
3. in Navigator, right-click *Bodies* and select *Display > Show*

### Expected result
Geometry attached to bodies appears after operation 3.

### Actual result
Visualizer Window remains blank. The logic here seems inconsistent: right-clicking *ground* and selecting *Display > Hide* causes everything to disappear, so it seems like hiding *ground* propagates down the ownership tree to everything below it. If so, right-clicking *Bodies* and selecting *Display > Show* should make the bodies (and everything below them in the ownership tree) reappear. Furthermore, if only some components are shown and the user right-clicks *ground* and selects *Display > Show*, nothing happens (expected everything to appear).

### Environment and GUI version
AppVeyor artifact OpenSim-e5f97340-2018-04-20.zip

**Comment by jenhicks** [comment]
Same on Mac (5-31 build)
