### ISSUE TITLE
OpenSim closes if GeometryPath point is deleted and then "appliesForce" checkbox is clicked

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#690]
### Steps to reproduce
- open arm26 model
- select TRIlong muscle
- click ellipsis button beside GeometryPath
- Delete > 2
- click Close
- click *appliesForce* checkbox

### Expected result
Checkbox toggles.

### Actual result
OpenSim closes.

### Environment and GUI version
AppVeyor artifact OpenSim-e5f97340-2018-04-20.zip

**Comment by aymanhab** [comment]
Deleting pathpoint with no wrapping involved works without an issue. This has to do with updating book-keeping to generate wrappoints when the muscle has wrapping. In Progress

**Comment by carmichaelong** [comment]
Fixed on W10 71c8c385.

**Comment by chrisdembia** [comment]
Fixed on Mac OpenSim 3d029e5-2018-08-15
