### ISSUE TITLE
Markers are scaled instead of moved when selected and dragged

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#695]
### Steps to reproduce
Select a model marker, try to move the marker

### Expected result
Marker can be moved around scene

### Actual result
Marker gets scaled 

![marker_scaling](https://user-images.githubusercontent.com/5296507/39402393-ff712a4a-4b12-11e8-98bf-9661a0a7f433.gif)

### Environment and GUI version
System:W10
Build:04-27-2018

**Comment by aseth1** [comment]
I think scaling markers is not helpful. Adjusting its size (via radius) would be helpful. The expected behavior of being able to translate the marker while dragging makes the most sense to me.

**Comment by aymanhab** [comment]
Scaling was a side effect of shortcuts built into the visualizer, these have been removed. Only supported functionality now is moving Markers. If that works, please close otherwise change label accordingly. Thanks

**Comment by tkuchida** [comment]
Markers can indeed be dragged around, but the *location* property is not updated and the new location is not saved. Opened #748.
