### ISSUE TITLE
Rendering quality in snapshot is not publication quality

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#697]
### Steps to reproduce
- open Resources\Models\Gait2392_Simbody\gait2392_simbody.osim
- center model in Visualizer Window
- set Controls > Snapshot Quality to maximum (4)
- click front-facing camera button

### Expected result
The saved PNG has lots of pixels and the shapes are smooth where smoothness is expected.

### Actual result
The saved PNG has lots of pixels but the rendering quality is poor.

**Full image (Snapshot Quality = 4):**
![](https://user-images.githubusercontent.com/4203505/39507018-ea979caa-4d90-11e8-9fd1-e86b4b52fba9.png)

**Zoomed in, with annotations:**
![](https://user-images.githubusercontent.com/4203505/39507024-f048e320-4d90-11e8-824b-6077119ed1e4.png)
(A) Intersection between muscle cylinder and bone mesh is jagged.
(B) It is impossible for two cylinders to intersect like this.
(C) There are holes in the muscles.

### Environment and GUI version
AppVeyor artifact OpenSim-dbbbb0c5-2018-04-16.zip

**Comment by tkuchida** [comment]
Should add that this region of the model looks fine in the Visualizer Window when I zoom in (this is the rendering quality I would expect in the snapshot):
![](https://user-images.githubusercontent.com/4203505/39507163-939ed854-4d91-11e8-83a6-7193125bed86.png)

@aymanhab

**Comment by tkuchida** [comment]
Artifacts are particularly bad if you change the field of view (to reduce the perspective effect):
![](https://user-images.githubusercontent.com/4203505/39507413-9ef74794-4d92-11e8-97a6-e432b1c11c53.png)

**Comment by tkuchida** [comment]
@aymanhab: I presume we're seeing [Z-fighting](https://en.wikipedia.org/wiki/Z-fighting), which has been reported by other Three.js users (though Z-buffer issues seem to be most common when rendering objects that are transparent). I've tried adjusting the properties of `renderer` related to the Z/depth buffer and anti-aliasing (in OpenSimViewport.js `renderHiRes()`) but haven't found a solution. Setting the pixel ratio (`renderer.setPixelRatio(10.0);`) looked promising and might be worth investigating if you haven't already. Other possible solutions I haven't investigated:
- [This stackoverflow answer to a similar question](https://stackoverflow.com/questions/23697275/wrong-triangle-z-index-in-three-js-create-an-artifact) suggests tessellating the geometry. How many faces are you using to create the cylinders? Can we increase this number just when generating the snapshot?
- [This answer](https://stackoverflow.com/questions/17588666/three-js-canvasrenderer-artifacts) suggests using `WebGLRenderer` instead of `CanvasRenderer`. (I don't know which renderer `renderer` is (the one used in OpenSimViewport.js `renderHiRes()`) and can't seem to find the line where it's defined.)

**Comment by aymanhab** [comment]
@tkuchida The number of sides is at OpenSimLoader.js (default to 8)
https://github.com/opensim-org/three.js/blob/8f992d9fe4e03f345dc3436ff776fdcdd1063852/editor/js/OpenSimLoader.js#L258

We're exclusively using WebGLRenderer

**Comment by aymanhab** [comment]
I'd say making the tesselation denser is a very low hanging fruit that you can start with.

**Comment by tkuchida** [comment]
Thanks, @aymanhab. Increasing the [`radialSegments`](https://threejs.org/docs/#api/geometries/CylinderGeometry) argument from its current value of 8 (default) to 32 makes the cylinders look nicer in the Visualizer Window (see below), but the difference will be much less noticeable once we have hemispherical endcaps. Unfortunately, there was no improvement in the resolution of the snapshot. I'm still investigating as it will be too time-consuming to touch up the current images in Photoshop.

**`radialSegments = 8`:**
![](https://user-images.githubusercontent.com/4203505/39607945-e4b9ed48-4ef2-11e8-886c-aae6dba622b8.png)

**`radialSegments = 32`:**
![](https://user-images.githubusercontent.com/4203505/39607955-ec0ab8ac-4ef2-11e8-99ed-8ae4de7b3c22.png)

**Comment by tkuchida** [comment]
@aymanhab I've found a solution that I can use. The problem is, indeed, Z-fighting. I don't know how to (or whether I can) increase the number of bits in the depth buffer, so I've moved the far clipping plane forward. The floor in the background of the image will get clipped away, but I can render it separately with different clipping planes and combine later. I've opened a separate Issue about holes in the muscle geometry (#716).

![](https://user-images.githubusercontent.com/4203505/39664338-a7bd8220-5036-11e8-9c25-2fc0d5e716f0.png)

**Comment by tkuchida** [comment]
> do you think there's value in exposing clipping planes, even in some expert mode?

No, I don't think exposing clipping planes would be good for the user. I can see a user wanting to move a light to adjust the shadows, for example, but I think it's very unlikely that even an expert user would look at their image and want to adjust the clipping planes.

I think the scene in the Visualizer Window looks good with the floor extending back. To avoid the rendering artifacts in high-resolution snapshots, a solution (perhaps for 4.1) might be to make three rendering passes to the canvas rather than just two:
1. Floor and sky cube only. Clipping planes as they are now.
2. Models and part of floor (to pick up shadow). The far plane is currently set to `10000` and it can be moved way forward without bumping into the models. To be safe, you could measure the distance between the camera and model, then add a large safety factor.
3. Orthographic pass for logo.

**Comment by tkuchida** [comment]
@aymanhab You could also try setting [`logarithmicDepthBuffer`](https://threejs.org/docs/#api/renderers/WebGLRenderer) to `true`. I didn't have much luck with that, but I didn't investigate too deeply; it might work if you adjust the near clipping plane based on the distance between the camera and the model. Here's a cool demo: https://threejs.org/examples/#webgl_camera_logarithmicdepthbuffer
