### ISSUE TITLE
NSIS Uninstaller.exe does not remove the installed files.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#712]
### Steps to reproduce

Install OpenSim using the NSIS installer. Then go into the installation and run the Uninstall.exe.

### Expected result

The OpenSim files are removed.

### Actual result

Only Uninstall.exe is removed.

### Environment and GUI version

Master branch, building the installer locally.

**Comment by jimmyDunne** [comment]
Uninstaller deletes folder and files and removes the path from system path. 
W10, OpenSim-32ef4769-2018-05-12-win64.exe
