### ISSUE TITLE
Loading the WalkerModel.osim causes an error related to MobilizedBodyIndex

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#72]
I tried loading models/DynamicWalker/WalkerModel.osim into the GUI and I got the following error:
![image](https://cloud.githubusercontent.com/assets/846001/23544579/657f5b12-ffac-11e6-9fc7-ec8b16663913.png)

This was with the 64-bit version.

**Comment by aymanhab** [comment]
Model has been removed from repo, is there a recent version to test with @jimmyDunne ? or should we close?

**Comment by jenhicks** [comment]
@jimmyDunne where does the WalkerModel.osim file live?

**Comment by chrisdembia** [comment]
The code to build the walker model is updated in core (https://github.com/opensim-org/opensim-core/pull/2073), and that model can be loaded into the GUI successfully. In my opinion, we should remove the WalkerModel from the opensim-models repo and close this issue.

**Comment by jenhicks** [comment]
The WalkerModel is not in the opensim-models repo anymore, so I'll close this issue. Thanks for testing.
