### ISSUE TITLE
"Gear" button at top of Controls window displays a box that is incomprehensible

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#726]
### Steps to reproduce
Click "gear" button at top of Controls box.

### Expected result
Not sure---perhaps intended to remove this button?

### Actual result
![](https://user-images.githubusercontent.com/4203505/39844340-6e24e820-53a4-11e8-837c-6504628219ad.png)

I don't think users will know what any of that means. Why does the message refer to only one parameter when there appear to be many parameters in the textbox? Where do I pass arguments to the GUI's constructor? What is localStorage? What happens if I check the box to automatically save values to localStorage on exit?

### Environment and GUI version
AppVeyor artifact OpenSim-bf3e61b9-2018-05-09-win64.exe

**Comment by tkuchida** [comment]
Not ready for testing.

**Comment by tkuchida** [comment]
Re-opening as requested, for later verification.

**Comment by jenhicks** [comment]
I don't see a gear box. Can I close this?

**Comment by tkuchida** [comment]
> I don't see a gear box. Can I close this?

This specific issue has been addressed by removing the gear button, but there's still a "Save As" button that prompts the user for a name but it doesn't appear in the drop-down box. The underlying issue is still there: saving/restoring environment settings is not implemented. AppVeyor artifact OpenSim-cedd8d22-2018-05-31-win64.exe

**Comment by jenhicks** [comment]
Strange ... I'm using the same build but the Mac version and it's behaving as I would expect.

(I enter some new settings ... click Save As ... enter a name ... then I can toggle between all the various settings configurations via the dropdown).

I will close this issue since in any case there is no longer an incomprehensible gear box.
