### ISSUE TITLE
Skybox persists after setting "Image" to "nobackground"

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#727]
### Steps to reproduce
- open a model
- click *Open Controls*
- set *Image* to "mars"
- set *Image* to "nobackground"

### Expected result
Mars disappears, revealing background whose color is *Background Color*.

### Actual result
Visualizer Window is in a state that should be impossible: *Image* is set to "nobackground" yet the previously selected background is still shown. Forcing a re-render (by rotating the camera, for example) does not update the background. Workaround is to click *Background Color* box, drag the selection circle, then return it to the desired color.

![](https://user-images.githubusercontent.com/4203505/39844626-e1700408-53a5-11e8-9c51-9150b590dc0b.png)

### Environment and GUI version
AppVeyor artifact OpenSim-bf3e61b9-2018-05-09-win64.exe

**Comment by tkuchida** [comment]
Not ready for testing.

**Comment by jenhicks** [comment]
Looks fine on 5-31 build. Can I close?

**Comment by tkuchida** [comment]
There is still a bug somewhere; I had a solid background but the "Image" drop-down box said something other than "nobackground". I will attempt to reproduce and file a new Issue.
