### ISSUE TITLE
Model no longer illuminated after creating new environment

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#729]
### Steps to reproduce
- open a model
- click *Open Controls*
- click "New"
- enter a string
- click "OK"

### Expected result
Nothing changes in the Visualizer (the settings of the new environment match the current settings in the Visualizer).

### Actual result
Model is no longer illuminated. Changing settings like *Scene Light X*, etc. did not restore the light, nor did moving the camera, nor did setting the environment back to "Default". There does not seem to be a way to turn the light back on. :bulb:

**Before clicking "OK":**
![](https://user-images.githubusercontent.com/4203505/39844939-afb46d4e-53a7-11e8-953c-45f6b01ec282.png)

**After clicking "OK":**
![](https://user-images.githubusercontent.com/4203505/39844941-b2725ef6-53a7-11e8-8278-43580f30b539.png)

### Environment and GUI version
AppVeyor artifact OpenSim-bf3e61b9-2018-05-09-win64.exe

**Comment by aymanhab** [comment]
Tom, the visualizer control menu is still work in progress. My initial pass
was intended to get feedback on what we expose or hide. Please don't trat
it as productizes yet. Thanks

**Comment by tkuchida** [comment]
Ok, thanks.

**Comment by jenhicks** [comment]
Appears to be working as expected on 5-31 build. OK to close?
