### ISSUE TITLE
Model persists in Visualizer Window after closing if body is double-clicked

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#730]
### Steps to reproduce
- open arm26.osim
- double-click skull
- *File* > *Close All*

### Expected result
Navigator and Visualizer Window are both cleared.

### Actual result
Navigator is cleared but model remains in Visualizer Window. Not fixed by closing and re-opening Visualizer Window.

![](https://user-images.githubusercontent.com/4203505/39846007-160f1d72-53ae-11e8-8cb6-221a24a64fdb.png)

### Environment and GUI version
AppVeyor artifact OpenSim-bf3e61b9-2018-05-09-win64.exe

**Comment by aymanhab** [comment]
This was due to an execption handling messages from visualizer, fix submitted,

**Comment by jimmyDunne** [comment]
Model is now closing. 
W10, OpenSim-32ef4769-2018-05-12-win64.exe

**Comment by jenhicks** [comment]
Fixed for me as well ... closing.
