### ISSUE TITLE
Selecting a muscle in Navigator draws large box in Visualizer Window and does not update label below Properties panel

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#738]
### Steps to reproduce
- open Gait10dof18musc\subject01.osim
- in *Navigator*, expand *walk_subject01 > Forces > Muscles*
- double-click "tib_ant_r"
- double-click "soleus_r"

### Expected result
Soleus muscle is highlighted in Visualizer Window and "soleus_r" appears below "Properties" panel.

### Actual result
Feedback in Visualizer Window is unclear and "tib_ant_r" is still shown below "Properties" panel.
![](https://user-images.githubusercontent.com/4203505/39955464-a0b7abac-5583-11e8-87d3-d7593dfaf42a.png)

The feedback in the Visualizer Window is unhelpful when many objects are contained in the yellow box. A potential alternative to illustrate selection is for the geometry to flash:
![](https://user-images.githubusercontent.com/4203505/39955554-942008ec-5585-11e8-876e-878f2e9661dc.gif)

### Environment and GUI version
AppVeyor artifact OpenSim-75fdf108-2018-05-11-win64.exe

**Comment by jimmyDunne** [comment]
Seen in Tutorial 2. Rather off-putting. Is there a plan to address this @aymanhab ?

**Comment by aymanhab** [comment]
Update label/status bar is relatively easy, updating box is harder and expensive while in motion. We never allowed selection of muscles anyway so I don't think it affects tutorial.
