### ISSUE TITLE
"Properties" panel now holds more than just properties

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#74]
"Properties" panel currently has two tabs: *Properties* and *Outputs*. Perhaps rename the panel to something like "Attributes" or "Component Info" (or move the list of Outputs elsewhere). It might be helpful to list the Inputs and Sockets as well, and to indicate what they're connected to.

**Comment by aseth1** [comment]
@jenhicks @aymanhab we should also resolve this issue. IMHO it is strange to ave the Window called *Properties* and then have a *Properties* tab and then a *Properties* [-] collapsible list.

![image](https://user-images.githubusercontent.com/6494122/37304546-1f7c83fa-25ef-11e8-9fe6-e3f4c6693659.png)

I think the Window should be "Object Viewer", "Object Attributes" or simply "Attributes". Having tabs for two types also does not seem necessary. Why are *Sockets* under the *Properties* tab? 

Perhaps just having *Properties*, *Sockets*, *Inputs* and *Outputs* as the generic layout of collapsible lists is more clear and sufficient. If the Object doesn't have any one of these, that attribute does not appear (similar to how the *Output* tab only appears for Components with outputs). Is that doable?
