### ISSUE TITLE
Marker's "location" property is not updated when marker is dragged in Visualizer, and new location is lost when model is saved and re-opened

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#748]
### Steps to reproduce
- open Resources\Models\Gait10dof18musc\OutputReference\subject01.osim
- drag "Sternum" marker in the Visualizer Window
- save, close, and re-open model

### Expected result
- *location* property updates while dragging (or, at least, upon selecting a different item in the *Navigator* and then re-selecting the "Sternum" marker)
- new "Sternum" marker location is preserved if model is saved, closed, and re-opened

### Actual result
- *location* property does not update when marker is being dragged, and does not update if a different marker is selected in the *Navigator* and then the "Sternum" marker is re-selected
- "Sternum" marker reverts to original location when model is saved and re-opened

**Before dragging marker:**
![](https://user-images.githubusercontent.com/4203505/40093197-ebceb604-5875-11e8-9afb-f9ea2247ef1b.png)

**After dragging marker:**
![](https://user-images.githubusercontent.com/4203505/40093204-f05bf4b6-5875-11e8-820f-512dbe99d81c.png)

### Environment and GUI version
75fdf108-2018-05-11

**Comment by jimmyDunne** [comment]
When moving a marker, the marker location is updated when the marker is released (not a live update).

When I close the model, I am prompted if I want to save, I select Save. I reopen the same model and the marker changes I have made have **not** been saved.

**Comment by aymanhab** [comment]
This turned out to be unrelated to visualizer/dragging. Same behavior happens when text editing location. Prompt to save on close was not actually saving (bug dates back to 3.3!) Fixed.

**Comment by jimmyDunne** [comment]
Save is resolved. 

W10. OpenSim-cedd8d22-2018-05-31-win64.exe

**Comment by jenhicks** [comment]
Marker move is respected on save and re-open. I also see the location property being updated after I drag the marker to a new location
