### ISSUE TITLE
Lag when toggling back to "Properties" tab in "Properties" panel

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#75]
**Steps to reproduce**
- Open leg6dof9musc.osim
- No lag when clicking bodies or when toggling between *Properties* and *Outputs* tabs in the "Properties" panel, but…
- Lags (~1 second) after clicking a joint in the "Navigator" panel

**More information**
- Same lag occurs when a joint is selected in the "Navigator" panel and the "Properties" panel is toggled from the *Outputs* tab to the *Properties* tab
- Same lag occurs if a joint is selected in the "Navigator" panel when the GUI window is minimized/restored (lag occurs when restoring)
- Lag is worse with other models (e.g., ~45 seconds with arm26.osim)
- No lag when a joint is selected in the "Navigator" panel and the "Properties" panel is toggled from the *Properties* tab to the *Outputs* tab
- No lag when "Properties" panel is closed

**Comment by tkuchida** [comment]
Still lags in Dec 2017 beta.

**Comment by jenhicks** [comment]
@tkuchida Can you test whether this is an issue? I am not currently noticing lags in my Mac for the scenarios you describe.

**Comment by tkuchida** [comment]
Lag no longer detected on my :turtle: laptop (AppVeyor artifact OpenSim-be3c7698-2018-04-05.zip); closing.
