### ISSUE TITLE
[Tutorial 1] Dragging motion slider does not work

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#753]
### Steps to reproduce
Open Gait2392, load 'Normal' motion, select motion slider and drag back and fouth. 

### Expected result
Motion plays smoothly at all times no matter how fast I move the slider. 

### Actual result
Anything but a crawl results in no motion being displayed

![motion_slider_bug.gif](https://images.zenhubusercontent.com/544fc8297c6ccc6277a5b651/b39fe323-3f9a-43a8-b664-5ba0af8d99e0)

### Environment and GUI version
Mac, OpenSim e07981e-2018-05-15

**Comment by jimmyDunne** [comment]
Sorry, but I doubt I will have time in the next five-sided days to do that. I'm swamped.

**Comment by aymanhab** [comment]
No worries, I'll try things on my own and let you know. I just thought you
may Have tried the tutorial recently so we can zone in on culprit faster
but no worries. It's binary search for date -> repo-> commit 😀

**Comment by tkuchida** [comment]
@aymanhab It looks like the opensim-org/three.js repo is still on r78 of three.js (June 20, 2016); the latest release is r92 (April 18, 2018). Have there been any performance improvements in the last 2 years? I haven't looked through the release notes in detail, but it might be worthwhile to pull a more recent release.

**Comment by aymanhab** [comment]
@tkuchida there's a branch on threejs that is r91. It proved a little slower for our workflow, out of the box. Didn't spend time investigating/tuning. The promising part was that it worked on some machines that reported missing WebGL support in the past (more forgiving) If speed is not the issue for you now or you want use latest features  you can use that branch  (https://github.com/opensim-org/three.js/tree/update_threejs_r91)

**Comment by aymanhab** [comment]
Latest optimizations in PR #837, #838 should improve performance

**Comment by jenhicks** [comment]
The behavior I see in the latest build (on OSX), is very similar to what @jimmyDunne reports. I am un-assigning myself to get some input from others. 

That being said, if I drag quickly, it does snap pretty quickly to the pose it should be in.

**Comment by aymanhab** [comment]
I spent time on this trying to figure out if we're sending unnecessary frames to visualizer and we're not. We can try regulate how fast we can send these since a user can go arbitrarily fast without serving any meaningful function. Will leave here for others to try as well.

**Comment by tkuchida** [comment]
Is the vizualizer not robust to receiving more messages than it can process? I would have expected it to have an input buffer for collecting messages, and the handler always just processes the most recent message (to completion). If that were the case, the model would lurch forward when the slider is moved quickly, which would be the expected and desired behavior.

**Comment by tkuchida** [comment]
> If a frame is sent while another is in process, it gets skipped.

Then why would the visualizer stop updating when the slider is moved quickly?

**Comment by aymanhab** [comment]
While we control processing of frames, some rendering is done in callbacks and finally on the GPU so we can't be sure that a frame processing is complete before processing the next one. I think this is what hapens here.

**Comment by tkuchida** [comment]
Ah, ok I get it now. Thanks for the explanation, @aymanhab. If we wait long enough, all the slow computers will die off and it won't be a problem anymore :wink:
