### ISSUE TITLE
Box is drawn using half-lengths as actual lengths

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#760]
### Steps to reproduce

- Load the Hopper model in the GUI. 
[Dennis.osim.zip](https://github.com/opensim-org/opensim-gui/files/2015043/Dennis.osim.zip)

### Expected result

- The model looks the same as in the Simbody Visualizer:

<img width="369" alt="image" src="https://user-images.githubusercontent.com/846001/40209408-d01831e0-59f3-11e8-9648-0d8dc98030f1.png">

### Actual result

- The dimensions of the box atop the mode appear to be half of what they should be.

<img width="422" alt="screen shot 2018-05-17 at 5 01 15 pm" src="https://user-images.githubusercontent.com/846001/40209431-f2a6a2d2-59f3-11e8-96a7-48fddaed7441.png">

### Environment and GUI version

Mac OpenSim b4cabd0-2018-05-17

**Comment by jenhicks** [comment]
Display of the block is as expected on my Mac (5-31 build)

**Comment by jimmyDunne** [comment]
As expected on W10. 
OpenSim-cedd8d22-2018-05-31-win64.exe
