### ISSUE TITLE
Pink model markers do not appear to be spheres

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#761]
### Steps to reproduce
Open a model with markers; load corresponding experimental marker data.

### Expected result
Blue experimental markers and pink model markers intersect in the Visualizer Window as if they are spheres.

### Actual result
The blue experimental markers seem to "poke through" the pink model markers when the markers are close (which is often the case):

![](https://user-images.githubusercontent.com/4203505/40210611-a7c109cc-59fa-11e8-9cc4-54fc1839829a.png)

Not sure how this can happen (perhaps the pink spheres have front face culling on rather than back face?), but it doesn't look so good and might make it difficult for users to place markers on the skeleton in the correct positions, which is a critical step in the pipeline.

### Environment and GUI version
75fdf108-2018-05-11

**Comment by tkuchida** [comment]
Perhaps the [`Material.side`](https://threejs.org/docs/#api/materials/Material.side) has been set to `THREE.BackSide` rather than `THREE.FrontSide`?

**Comment by jimmyDunne** [comment]
Model makers seem to be spheres. I don't see the issue that Tom reported. 

@tkuchida, I will move this to verified- please let me know if you see this behaviour again? Thanks.

W10, OpenSim-2888c1c6-2018-05-28-win64.exe

**Comment by jenhicks** [comment]
Marker intersections appear as I would expect on Mac, as well
