### ISSUE TITLE
User is not prompted before overwriting existing model file

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#766]
### Steps to reproduce
- open arm26.osim
- select *File > Save Model...* (accidentally---instead of the *Close All* item above it)

### Expected result
User is prompted before the existing arm26.osim file is overwritten.

~~Also note that the ellipsis following a menu item is typically used to indicate that the user will be prompted for additional information (e.g., destination directory, filename) before performing an operation. There should not be an ellipsis following "Save Model" (even if the user is asked to confirm).~~ [Edit: opened Issue #769]

### Actual result
GUI silently overwrites existing file. The old model file is lost!

### Environment and GUI version
d8bfa962-2018-05-09

**Comment by aymanhab** [comment]
Tom, it's very typical if a model comes from a file and you're saving to overwrite old file. Same as all other software e.g word. If you do save as then you should be prompted. If model didn't have a file as in scaling output you should be prompted. Behavior is same in 3.3 but open to ideas for improvement.

**Comment by tkuchida** [comment]
Please let me know how the user experience has been designed for the following use case:

User has many model files in version 20303, one for each subject in several experimental conditions. Diffing these files reveals the unique properties for each subject, and user has developed other infrastructure that works with model files in version 20303. User opens one of the model files and deletes a model marker. The "undo" button remains disabled so the user proceeds to close and re-open, but accidentally saves. The model file is now in version 30516; there are thousands of differences. User is unable to undo the conversion.

**Comment by tkuchida** [comment]
> Same as all other software e.g word.

I don't think OpenSim is providing users with the typical feedback. Here's a use case:
- open arm26.osim from Resources directory (version 20303)
- *File > Close Model*

The model closes without prompting the user to save changes. The user's mental model tells them that a "save" operation would not have had any effect because, if there were any changes, the user would have been prompted to save changes before closing. Now:

- open arm26.osim from Resources directory (version 20303)
- *File > Save Model...*
- *File > Close Model*

The model file is different (now version 30516). Telling the user "it's your own fault for not saving a backup copy" or "it's your own fault for clicking *Save Model*" or "you need to update your existing infrastructure if you're using 4.0" makes for a very negative user experience.

I would expect that many users will open their existing model files to try out the new version of OpenSim. Clicking *Save Model* performs an irreversible change to the file which could negatively affect their research. That could be their first interaction with OpenSim 4.0.

> It's customary when other software does similar irreversible change in format that they offer an "import" style function so that users are aware of the irreversible change to their files, and maybe at this point save to a different file. Do you think this would make for a better user experience?

*File > Import*? No, I don't think that would be good—unless, perhaps, we had changed the extension of the model file. I think a better design would be, after *File > Open*, do 2 things if the original model file's version < 30516 (or whatever official version we assign for 4.0):

1. Display a dialog box stating that the model was successfully updated from version [the original model file's version] to 30516.
2. Tell the GUI that the model has been changed (presumably there's a flag somewhere). Then the user would be prompted to save changes before closing, which would build the correct mental model.

Thoughts, @aseth1?

**Comment by jenhicks** [comment]
@tkuchida 's proposal seems reasonable to me. How challenging is this to implement @aymanhab ?

**Comment by aseth1** [comment]
I agree that this process is more inline with user expectations. 

> The flag needs to be maintained on API side.

Not sure what this flag is referring to. A flag on Model that says I've been updated? That doesn't sound like maintenance to me but adding a new capability. We should discuss exactly where this functionality should live.

**Comment by aseth1** [comment]
I agree with the need and the rationale, but what I don't understand is what the interface should be and if the API should even be involved. At high level I see it simply as:
1. load (read in, update and finalize) the Model and note the document version (e.g. `model.getDocument().getDocumentVersion()` )
2. determine if the version is different from the latest version (document that is now in effect) (`XMLDocument::getLatestVersion`) and if so pop up an error message that the model has been updated. Also mark the model as "dirty" in the GUI as to prompt the user to save changes upon closing or exit
3. upon save (exit or menu->Save), if user selects the same file to overwrite, they are warned that the existing file will be overwritten and ask if they are sure they want to do that.

In this scenario, what is the flag that the API should maintain?

**Comment by aymanhab** [comment]
@aseth1 getDocument() is not exposed (has protected access), if you want to expose some form of DocumentVersionNumber() then we should be good. Same with XMLDocument.

**Comment by aymanhab** [comment]
@tkuchida @chrisdembia @jimmyDunne @jenhicks @aseth1
