### ISSUE TITLE
Marker deletion is not recognized as a change to the model (it is not undoable, and user is not prompted to save changes before closing model)

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#768]
### Steps to reproduce
- open arm26.osim
- in *Navigator*: expand "Markers", right-click "r_acromion", click *Delete*
- *File > Close Model*

### Expected result
User is prompted to save changes before model is closed. For example, if a muscle's maximum isometric force is edited, the following dialog is displayed following *File > Close Model*:

![](https://user-images.githubusercontent.com/4203505/40274964-1d1cdd3c-5b99-11e8-9175-38655f9d000a.png)

### Actual result
Model is closed immediately.

### Environment and GUI version
75fdf108-2018-05-11

**Comment by jimmyDunne** [comment]
User is now notified of change. 
W10
OpenSim-2888c1c6-2018-05-28-win64.exe
