### ISSUE TITLE
Preferences -> Experimental Marker Size Preference has no effect

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#787]
### Steps to reproduce
- Have any experimental marker data open in the GUI.
- Open the Preference dialog.
- Edit the "Experimental Marker Size" to 2.0, click OK, Close the GUI.
- Re-open the GUI, re-open any experimental data

### Expected result
The Preference name should be "Default marker size scale" and apply to both experimental and model markers. 

When re-opening the GUI, the default value for Marker Property "marker size scale" would be 2.0

### Actual result
No difference in either the experimental or model marker scaling. 

### Environment and GUI version
Mac and Windows 
OpenSim 543e2ec-2018-05-27

**Comment by aymanhab** [comment]
As the name of the preference suggests, it should only affect Experimental Markers (Model Marker are managed by API and GUI has no control on their size, shape or color). Is this worth keeping/wiring or removing? Changes are possible on the fly anyway.

**Comment by jimmyDunne** [comment]
The Default scale factor should be persistent. If I want my experimental markers to always be scaled up by, say, 2, then this would be the mechanism I would use. Every time I open experimental data, I shouldn't have to adjust the scale factors, again. 

> Model Marker are managed by API and GUI has no control on their size, shape or color

Then how does a user change the size of the model markers in GUI? Is the GUI not able to communicate with the API? Why can't the GUI draw the model markers? I don't think it is reasonable to shrug our shoulders and say that there is nothing we can do about the model marker sizes. I personally think the markers are too small, but as a User I can never change their properties?

**Comment by tkuchida** [comment]
Related: #643
