### ISSUE TITLE
Model Motion isn't updated while RRA is running

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#794]
### Steps to reproduce
- Run through gait2392 pipeline

### Expected result
When IK, RRA, or CMC are run, the model motion in the visualizer should update at each step.

### Actual result
The model motion doesn't update until the analysis is complete. 

### Environment and GUI version
W10 and Mac
OpenSim-543e2ecd-2018-05-27-win64.exe

**Comment by jimmyDunne** [comment]
IK, SO, and CMC all played the motion during the simulation 🎉 . RRA did not play and also resulted in choppy/unplayable motion when finished. This was using the gait2354 model and running through the standard pipeline. Below is a gif of the RRA simulation performed on a W10 machine using OpenSim-2888c1c6-2018-05-28-win64.exe.

![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/5296507/40669050-e15d4b9a-631a-11e8-8dac-295df9bc0e27.gif)

**Comment by jenhicks** [comment]
Model animates for me during RRA on Mac

**Comment by jimmyDunne** [comment]
Model animates during RRA on Windows
