### ISSUE TITLE
{Tutorial 2} Can't Select multiple muscle path points to move

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#795]
### Steps to reproduce
Tutorial asks to select multiple muscle path points, simultaneously, and move them as a group. This either isn't available anymore or the hot keys have changed (used to be shift+ctl)?

### Environment and GUI version
W10
OpenSim-543e2ecd-2018-05-27-win64.exe

**Comment by aymanhab** [comment]
Not supported any more, only single selection is possible.  Tutorial needs reworking

**Comment by aymanhab** [comment]
The technical issue is that the threejs editor that we base the visualizer on was designed to have one object selected, and accordingly  have one box associated with this selection, and that same single selection is used all over the place (e.g. to focus) and to drag or to edit in expert mode as of now. While possible to change "in theory" it's not something to be taken lightly or can be done as a simple "bug-fix".
