### ISSUE TITLE
Default pathpoint scale up should be 1.05

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#796]
Previous OpenSim versions had the muscle pathpoints coloured in a slightly different shades of red and the sphere was distinguishable from the muscle. Path points are essentially indistinguishable from the muscle path. 

**OpenSim 4.0**
![muscle_paths_40](https://user-images.githubusercontent.com/5296507/40629896-f6830df4-6282-11e8-9636-b2d20e88e9e2.png)

**OpenSim 3.3**
![muscle_paths_33](https://user-images.githubusercontent.com/5296507/40629897-f88ca88a-6282-11e8-873d-4f10428aef06.png)

I don't necessarily have an issue with this, but it could now be easy to miss a path point if the deviation of the new path is very slight. It also doesn't make intuitive sense that this is a path point now- it looks as if the muscle path is just kinked. 

There feels like there is an asthetic vs function trade off here so it should be discussed. 

### Environment and GUI version
W10
OpenSim-543e2ecd-2018-05-27-win64.exe

**Comment by tkuchida** [comment]
Could make the radius of the path point spheres slightly larger than the radius of the muscle cylinders, and display only when the muscle is selected.

**Comment by aymanhab** [comment]
They are in fact kinks, except you have a handle to drag them. Larger radius will make ends look a bit worse though may improve z-fighting issues. How large considering size is user specified? 5%, 10%? Would be expensive to do on selection or to keep multiple geometries around for same pathpoint.

**Comment by aymanhab** [comment]
@jimmyDunne @tkuchida in latest devBuild 0608, there's a separate command to toggle pathpoints to bigger size that should make it much easier to move/edit/grab. you either activate by doubleclick in navigator or explicit selection of command.

**Comment by jenhicks** [comment]
On Mac, delete preferences

**Comment by aseth1** [comment]
What is the default `PathPoint Scaleup` supposed to be?  Do we expect users to know what it means?

Setting it to a small (or large) value looks quite ridiculous.
![image](https://user-images.githubusercontent.com/6494122/43173702-2601f4ae-8f6b-11e8-8f04-3256a4e43805.png)

If the point is that it useful for selection, then they should always be of selectable size and should not be a user setting. For the time being. Setting the scaleup to1.05 appears to be reasonable (similar in appearance to 3.3).

Maybe the preference should just be a flag to make path points visible? Ideally the path points only appear when the muscle is selected and with different (highlight) color.

I don't believe the current solution addresses clearly addresses the user need to see and manipulate pathpoints when editing and have smooth continuous muscles when simulating and generation images and animations.

**Comment by aymanhab** [comment]
@aseth1 Thanks for the feedback. The current default scaleup is 1.0.
The tradeoff we're trying to meet is:
- Make ends look smooth and pathpoint not prominent (for paper, book, most users not editing paths) for these 1.0 seems a good fit, what we loose is ease of grabbing points for editing.
- Make Pathpoints prominent so it's easy to do tutorial 2 and interactively modify paths.

I'm fine with 1.05 as a compromise, in fact I'm using 1.03 myself but I'm happy to remove the Preference altogether if we have a fixed number that we're all happy with.
@jenhicks @tkuchida @jimmyDunne @apoorvar @chrisdembia 
If no number satisfies all we can switch to a binary preference "Use large pathpoints" to toggle.

**Comment by jenhicks** [comment]
I think we could make the default 1.03 or 1.05. I would keep the number preference for now and we can update/improve this feature later depending on priorities

**Comment by jenhicks** [comment]
Set preference to 1.05 by default.

**Comment by tkuchida** [comment]
> Isn't there an issue if we leave preferences that they pollute the user's registry (on Windows) and even appear in 3.3 preferences?

@aseth1 There was some discussion in PR #708.

**Comment by tkuchida** [comment]
> Muscles look like tubes not particularly well soldered together.

I think the issue here is that the muscles are drawn as tubes with only 8 faces (https://github.com/opensim-org/three.js/blob/115fc131d44d01a89ba4f038deaac6c6cfac9241/editor/js/OpenSimLoader.js#L258). The renderer does a pretty good job of smoothing, but perhaps we need more faces now that there are these intersections to resolve?
