### ISSUE TITLE
Disable editing via the diamond and only allow editing along one axis at a time

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#798]
### Steps to reproduce
- Select muscle path point
- Move in an x/y/z plane

### Expected result
Path point would only move in current plane

### Actual result
Path point moves out of plane. 

This was seen on a small scale initally, below is a video demonstrating the issue. 

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/5296507/40630560-67003552-6288-11e8-8da3-52d3c2147770.gif)

### Environment and GUI version
W10
OpenSim-543e2ecd-2018-05-27-win64.exe

**Comment by aymanhab** [comment]
I see the post/bad effects but not sure how you got there, can you provide more details? If you use the arrows of the pickable arrows of the triad can you get the points where you want them? Not perfect but functional for me.

**Comment by jimmyDunne** [comment]
I don't really know what more details to provide. There is clearly an error in how the location of the pathpoint is calculated. If I select a pathpoint and move it I get erroneous locations. If you are only moving the pathpoint a short distance the error isn't very large, but it is still there. 

![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/5296507/41359584-ac7010d6-6edf-11e8-92b1-3d2371ba49a1.gif)

**Comment by jenhicks** [comment]
Maybe disable moving via the diamond

**Comment by aymanhab** [comment]
Build with fix (diamond removed) is available here
https://ci.appveyor.com/project/opensim-org/opensim-gui/build/1.0.1605/artifacts
