### ISSUE TITLE
{Tutorial 2} Muscles, in different groups, have different Show Only effects. 

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#799]
### Steps to reproduce
- Open the Wrist model, expand Forces/Muscles in the Navigator
- Right-click on extensors/ECRB and select Show Only

### Expected result
- Only the ECRB is shown

### Actual result
- ECRB and the entire flexor group are shown. 

![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/5296507/40630796-81d04758-628a-11e8-9e0b-8788a44d7c98.gif)

### Environment and GUI version
W10
OpenSim-543e2ecd-2018-05-27-win64.exe

**Comment by aymanhab** [comment]
@jimmyDunne I know this could be confusing but let me explain the behavior. It boils down to what showOnly means, as of now it's relative to the parent node in the navigator. In effect you'r hiding other extensors. I'd suggest you change instructions to "show only" extensors group, then "show only" ECRB from the group.

**Comment by aymanhab** [comment]
@jimmyDunne @jenhicks Please let me know if this needs a fix or documentation. Thanks

**Comment by jenhicks** [comment]
I agree this is a bit confusing. If the behavior is the same as 3.3, I think we should just update the documentation for now.

**Comment by jimmyDunne** [comment]
This still requires a fix. We can put a band-aid on it for the tutorial, but the behavior is broken and should be fixed before release.

**Comment by jenhicks** [comment]
I believe the behavior is the same as in 3.3. It's not broken but implemented in a way that I agree is confusing.

If you go to the "all" heading under muscles, and find the muscle of interest and select "Show Only" do you get the behavior you expect James?

**Comment by jenhicks** [comment]
The logic is as follows:

Consider all the muscles in the current group (all, extensors), and show me only the ECRB

**Comment by aymanhab** [comment]
@jenhicks and @jimmyDunne Please let me know if you'd prefer I change current behavior or will just document. Thanks

**Comment by aymanhab** [comment]
@jenhicks and @jimmyDunne Still waiting for feedback if the documentation will update or we need to change behavior. please advise, thanks

**Comment by jenhicks** [comment]
Per discussion last week, the plan for upcoming 4.0 beta is to keep behavior as-is and change the documentation.

**Comment by jenhicks** [comment]
Show only now has the effect I expect. The speed with which display has updated seems slower than I recall. @aymanhab Is there any reason for this?

**Comment by aymanhab** [comment]
The change in interpretation of "show only" means there're more muscles to toggle/hide at least initially when all muscles are shown, While there're more muscles to process (usually <100) this should be negligible compared to the cost of sending command to visualizer to flip the visible flag, so I'd say if it is slower then  only because it's doing more work.

**Comment by chrisdembia** [comment]
Must consider if Tutorial 2 needs to be updated for the new meaning of "Show Only".
