### ISSUE TITLE
Visualizer is unresponsive for 20 seconds after selecting "Display > Show Only" on a muscle

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#803]
### Steps to reproduce
- open Rajagopal2015 model
- in Navigator, right-click *Forces* and select *Display > Hide*
- expand *Forces* / *Muscles* / *all*
- right-click "glmax1_r" and select *Display > Show Only*

### Expected result
Muscle appears in Visualizer window essentially immediately.

### Actual result
Visualizer window is unresponsive for ~20 seconds, then muscle appears. CPU usage spikes to 100%. The muscle appears after only ~2 seconds if *Display > Show* is selected instead.

### Environment and GUI version
AppVeyor artifact OpenSim-d577f2dd-2018-05-29-win64.exe

**Comment by tkuchida** [comment]
Possibly a side effect of #802 (fix for #691).

**Comment by aymanhab** [comment]
Optimized code to render/refresh once at the end.

**Comment by jenhicks** [comment]
It isn't 20 seconds on my machine (with gait2392), but it is slower than I expect.
