### ISSUE TITLE
Installer hangs for ~1 minute with progress bar at 100%

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#809]
### Steps to reproduce
Install OpenSim-e1c6a4db-2018-05-30-win64.exe.

### Expected result
Installer provides feedback to user about progress of install.

### Actual result
New behavior not seen in installer from earlier today: after the progress bar reached 100%, a Windows dialog something like [this](https://msdn.microsoft.com/dynimg/IC726238.png) appeared. After clicking *OK*, the Windows dialog disappeared and nothing seemed to be happening for ~1 minute—long enough that I think many users would have [killed the process](https://i.redditmedia.com/_PSxMEdL3NulmUYRFndAKSk2SlLHl_tMYJ98GpMPtQA.png?w=745&s=c969218ac3413f24180451710f3ce8af).

![](https://user-images.githubusercontent.com/4203505/40755928-8249e192-6435-11e8-8042-8eddfffa8a7c.png)

### Environment and GUI version
OpenSim-e1c6a4db-2018-05-30-win64.exe

**Comment by aymanhab** [comment]
This is likely while running the redistributable (a side effect of /quiet), so maybe not quiet by default @chrisdembia ?

**Comment by chrisdembia** [comment]
Thanks @aymanhab. I fixed this issue in PR #811.
