### ISSUE TITLE
Editing/moving of a path point in the Visualizer cannot be undone

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#815]
### Steps to reproduce
Load arm26.osim, select a path point (double-click) and drag it around.

### Expected result
Undo arrow becomes highlighted/active and clicking it undoes the change.
![image](https://user-images.githubusercontent.com/6494122/40812815-b1d73f60-64ec-11e8-9980-bed7b311ea47.png)

### Actual result
Undo option is not available. Only closing without saving and reopening can restore the model.
![image](https://user-images.githubusercontent.com/6494122/40812850-d2a98694-64ec-11e8-9467-262dedb06c7d.png)

### Environment and GUI version
Windows OpenSim-43c1be65-2018-05-30

**Comment by aymanhab** [comment]
Dragging can now be undone (you may need to select the muscle in navigator to enable the undo) but that's an already open/separate issue.

**Comment by jenhicks** [comment]
> Dragging can now be undone (you may need to select the muscle in navigator to enable the undo) but that's an already open/separate issue.

This is what I observe on mac. (Strangely you can redo without selecting in the navigator). Moving to verified since you said there is a separate issue for having to click int he navigator to enable the undo

**Comment by aseth1** [comment]
On Windows OpenSim_cea85df3-2018-07-18 this issue remains unresolved.
I followed the same steps as listed above. The difference is that muscle now reverts to the "kinked" state which it assumes during the edit process.

![image](https://user-images.githubusercontent.com/6494122/43107303-3c6f7aac-8e91-11e8-9948-4a8cfa9cb4a0.png)

**Comment by aymanhab** [comment]
see comments in #816

**Comment by aymanhab** [comment]
This has been fixed by other fixes and no artficial kinks are obaserved.

**Comment by chrisdembia** [comment]
Verified on Windows 4.0-2018-09-04-a2736979
