### ISSUE TITLE
Graphically moving path point displays a convoluted path

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#816]
### Steps to reproduce
Load arm26.osim. Select TRILat middle via point and drag.

### Expected result
Path drawing updates contiguous with existing path points.

### Actual result
Path point moves and is redrawn with respect to two phantom path points which remain stationary with respect to the other via points.
![image](https://user-images.githubusercontent.com/6494122/40813495-0630d974-64f0-11e8-98ca-1be33cbe77f1.png)

### Environment and GUI version
OpenSim-43c1be65-2018-05-30

**Comment by jenhicks** [comment]
I see the same behavior, though if you wait a seconds, the muscle path is redrawn as you would expect.

**Comment by aseth1** [comment]
Still present in Mac OpenSim 1e476f2-2018-06-13.
Discussed with @aymanhab and he felt that because this transitory (I am still dragging) that the kinks are not important since they disappear on release. I think it is goofy.

**Comment by tkuchida** [comment]
> I think it is goofy.

![](https://user-images.githubusercontent.com/4203505/41374990-90fce7fa-6f09-11e8-8af1-c8c484431723.png)

Perhaps only the point (sphere) should be dragged and the path should update only once the mouse button has been released? That would also allow the user to see where they're moving the point in relation to the existing muscle path.

**Comment by aymanhab** [comment]
@tkuchida Since pathpoints can't exist in multiple places at the same time, and they need to exist in the old location for the old path to be drawn, I don't think this solution is sustainable without major rework.  
We can try to update the visualization based on a timer (e.g. every .1 sec while dragging) but we need to prioritize relative to other issues.

**Comment by aymanhab** [comment]
While the transient behavior is likely to stay, there's a bug where graphically moving pathpoitns doesn't follow the full protocol of updating path and recreating system as done for other editing in Dialog. Fix in progress.

**Comment by aseth1** [comment]
On Windows OpenSim 11d7a130-2018-08-03 I still don't think the behavior is correct.
Starting off like this:
![image](https://user-images.githubusercontent.com/6494122/43670612-7f231534-9742-11e8-8ba3-5a601ed055dd.png)

Selecting points to edit seems to add a new path point and doesn't move the existing point! And unlike before it is not transitory - it persists. Undo does not work here either and undoes the hiding of muscles that were hidden rather than undo the current pathpoint edit.

![image](https://user-images.githubusercontent.com/6494122/43670623-a0d2258a-9742-11e8-9f20-6eb8c222269e.png)

**Comment by chrisdembia** [comment]
This behavior is different on Windows vs Mac. On Mac, the path looks proper after one is done dragging.

**Comment by aymanhab** [comment]
Verfied fixed on windws

**Comment by chrisdembia** [comment]
Verified.
