### ISSUE TITLE
Make sure you can't move a muscle

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#819]
### Steps to reproduce
- Open Model
- Select any muscle
- Move the muscle

### Expected result
either (i) I am unable to move the muscle or (ii) if I can move the muscle, the pathpoints come for the ride.

### Actual result

I can move the muscle path However, the pathpoints stay behind. 

![ezgif com-video-to-gif 6](https://user-images.githubusercontent.com/5296507/40861468-0acab104-659e-11e8-907a-c832e6927a92.gif)

### Environment and GUI version
W10. OpenSim-cedd8d22-2018-05-31-win64.exe

**Comment by aymanhab** [comment]
Muscle selection will not be possible in 3D view, double click in navigator will toggle pathpoints display

**Comment by jenhicks** [comment]
Verifying that I can't move a muscle

**Comment by jimmyDunne** [comment]
![ezgif com-video-to-gif 4](https://user-images.githubusercontent.com/5296507/43154268-c4752fd6-8f41-11e8-9278-2933d475c727.gif)
