### ISSUE TITLE
Markers' body property should be removed

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#82]
The PhysicalFrame:parent_frame connector has no value for Markers and is also uneditable.

This was discovered with Kate Saul's upper extremity dynamic model.

![image](https://cloud.githubusercontent.com/assets/846001/23584402/75c0d96e-0115-11e7-895c-9f0fc7c2f6b5.png)

Windows 64-bit build.

**Comment by aseth1** [comment]
Socket, `parent_frame` is  editable. But Marker is not correctly mapped when changed. They are put onto the origin of the other frame (R.ASIS after changing pelvis to femur_r is at hip joint center). Not clear when the transfer happens. As soon as frame is selected from pull-down or when changing context (clicking on visualizer window or navigator).

Also, CPU begins to throttle on Mac build OpenSim 2112110-2018-01-31. Using >%130 CPU. Had to quit OpenSim to stop.
