### ISSUE TITLE
Visualizer does not open models with a ConstantDistanceConstaint(). No exception provided 

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#820]
### Steps to reproduce
- open model that has constant distance constraint (Ravi's wrist model) 

### Expected result
Be able to see in the visualizer 

### Actual result
No Model in the Visualizer. Model opens in the navigator, no exception in the Messages Window

![wrist](https://user-images.githubusercontent.com/5296507/40865412-f5f1ea40-65ac-11e8-8a09-ec0bbdafc1bb.png)

### Environment and GUI version
W10. OpenSim-cedd8d22-2018-05-31-win64.exe

**Comment by aymanhab** [comment]
@jimmyDunne can you post this model to the devBuilds/testing Dropbox folder? Is that for the paper figure?

**Comment by jimmyDunne** [comment]
/Dropbox/OpenSim Beta Testing Files/4.0 Testing/wrist_ravi/Wrist Model

Yes, this is for the paper.

**Comment by tkuchida** [comment]
@aymanhab Is this going to be a quick fix, or should I modify the model and proceed with OpenSim-4.0.Beta-win64.exe from Dropbox?

**Comment by tkuchida** [comment]
> You should modify the model and proceed. The constraint generates a "Line" in generateDecorations which was never shown in 3.3 anyway.

Thanks. I'll modify the model and proceed---but please be aware that the model opens in 3.3 and nothing shows up in 4.0. It would be nice to know why nothing appears in 4.0.

- `Dropbox\OpenSim40Paper\Figures\figure_8\Wrist Model\ForFigure.osim` shows levers in the expected locations in OpenSim 3.3:
![](https://user-images.githubusercontent.com/4203505/40870191-e22e366c-65de-11e8-902e-c76c44f7c064.png)

- same model opened in AppVeyor artifact OpenSim-cedd8d22-2018-05-31-win64.exe:
![](https://user-images.githubusercontent.com/4203505/40870194-e603e2d2-65de-11e8-9d75-6a509afda0ee.png)

**Comment by jenhicks** [comment]
I can open a model with the ConstatDistanceConstraint() on Windows. Forward dynamics leads to issues with the assembly solver

Model relaxing constraints and trying again.
Model unable to assemble with relaxed constraints: AssemblySolver::assemble() Failed: SimTK Exception thrown at Assembler.cpp:227:
  Error detected by Simbody method AssemblerSystem::objectiveFunc(): calcGoal() method of assembly condition System Constraints returned a negative or non-finite value nan.
  (Required condition 'goalValue >= 0' was not met.)

I'm not sure if this is expected or not

**Comment by aymanhab** [comment]
Tested on Windows and loaded just fine.
