### ISSUE TITLE
Wheel mouse moves Coordinates panel up/down by only 1 pixel at a time

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#827]
### Steps to reproduce
- open gait2392 model
- go to Coordinates panel
- click in a textbox to give panel focus
- use wheel mouse to scroll up/down

### Expected result
One click of the wheel mouse scrolls window up/down by about one textbox height—similar to the scrolling resolution in the Navigator panel, where one click of the wheel mouse scrolls window up/down by the height of one item in the tree.

### Actual result
One click of scroll wheel moves window only 1 pixel, which is not useful for the user. I cannot think of a use case in which the user would need such a small scrolling resolution. Typical use case is the user is looking for a coordinate in the list; moving the mouse to the scroll bar slows this process.

![](https://user-images.githubusercontent.com/4203505/40881235-5f9e1de6-6676-11e8-9b8c-1e07804e69b3.gif)

### Environment and GUI version
AppVeyor artifact OpenSim-cedd8d22-2018-05-31-win64.exe

**Comment by jenhicks** [comment]
Scrolling works as expected on the Mac build.

**Comment by aymanhab** [comment]
If you look at the scrollbar to the right in @tkuchida screen capture, it looks like it is moving up/down so the issue may be that somehow when he gets the focus on the coordinates window the mouse wheel is bound to the scrollbar. Not much we can control but may explain.

**Comment by tkuchida** [comment]
> when he gets the focus on the coordinates window the mouse wheel is bound to the scrollbar

Why is the scroll resolution in the Navigator different?
