### ISSUE TITLE
Editing OffsetFrame properties do not update its axes in the GUI

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#843]
### Steps to reproduce
1. Load the attached model. 
[pendulumIMU.osim](https://github.com/opensim-org/opensim-gui/files/2092147/pendulumIMU.osim.txt)
2. Select  `link_imu_offset`  from Bodies->link, right click to *Show Axes*
3. Edit the `link_imu_offset`'s properties in the Property editor. E.g. set the Translation to (0 0 0.05).

### Expected result
The `link_imu_offset` and the `link_imu` geometery are drawn at the new location (near origin of the link).

### Actual result
The the `link_imu` geometry is drawn at the new location (near origin of the link), but the  `link_imu_offset`' axes are still drawn its original location (at ground).

![image](https://user-images.githubusercontent.com/6494122/41263848-54dad92e-6d9e-11e8-8145-535d5fc05e65.png)

### Environment and GUI version
Windows, on both:
OpenSim-558d3e9f-2018-06-04, &
OpenSim-0ac2967b-2018-06-08

**Comment by aseth1** [comment]
Ran into this issue again during model building demo for webinar practice.

**Comment by aymanhab** [comment]
Can this be closed as verified?
