### ISSUE TITLE
Cannot add Wrap Object to Muscle Path

### ISSUE THREAD

**Issue by clnsmith** [opensim-org/opensim-gui#845]
### Steps to reproduce
Open arm26.osim Model in GUI
Navigate Forces->Muscles->TRILong->GeometryPath
Try to add wrap object to muscle path, the available wrap objects appear in the drop down menu, but when they are selected nothing happens. 

![image](https://user-images.githubusercontent.com/1234687/41294403-45ef42a0-6e58-11e8-86c3-5d40d94239f4.png)
(note in the image above I deleted the TRILongglen out of the original path, so it now appears as a possibility to add it back)

### Environment and GUI version
APPVeyor GUI version: OpenSim 32ef476-2018-05-12
Windows 10

**Comment by aymanhab** [comment]
This was due to not calling initSystem in OpenSimContext::addPathWrap. Fix is in the pipe.
