### ISSUE TITLE
Previously-closed models do not disappear from the threejs visualizer

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#85]
I previously had Kate Saul's model open, but I closed it. I then opened Apoorva's model, but both showed up in the threejs visualizer.

![image](https://cloud.githubusercontent.com/assets/846001/23584552/b7be2a98-0119-11e7-8720-455ab2a8a8e2.png)

Windows 10; 64-bit GUI build.

**Comment by aymanhab** [comment]
@aseth1 Can you please verify if this happens with actual models or only with experimental data. The latter scenario is covered by separate issue #475 which I fixed very recently and the fix may not have been integrated into the build you're using. Thanks

**Comment by aseth1** [comment]
Its an actual model- not experimental data preview.

**Comment by aymanhab** [comment]
This could happen if an exception is thrown and an error occurs while closing a model. Impossible to reproduce without specific model/steps. I suggest either closing or specifying the steps that leads to this.

**Comment by jenhicks** [comment]
Closing ... will reopen if we find a specific scenario that causes this issue.
