### ISSUE TITLE
In the Navigator, Bodies can have multiple components of the same name

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#853]
### Steps to reproduce

1. Open WalkerModel.osim in the GUI
2. Expand Bodies > LeftThigh

### Expected result

- The LeftThigh cannot contain multiple objects with the same name.

### Actual result

- The LeftThigh conatins two `LeftThigh_offset`s. These offsets actually belong to joints in the model, not bodies.

<img width="243" alt="screen shot 2018-06-13 at 12 52 50 pm" src="https://user-images.githubusercontent.com/846001/41374700-c7a17d1c-6f08-11e8-9e2b-361cd4826539.png">

### Environment and GUI version

Mac OpenSim 1e476f2-2018-06-13

**Comment by tkuchida** [comment]
Related: #825.
