### ISSUE TITLE
Changing coordinate values in the Coordinates panel doesn't work if the user first generates a plot of muscle moment arms

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#854]
Reported by @jryong

### Steps to reproduce
- open arm26.osim
- Tools -> Plot...
- Y-Quantity... -> moment arm -> r_shoulder_elev
- Muscles... -> select all shown
- X-Quantity... -> r_shoulder_elev
- click Add
- close Plotter
- go to Coordinates panel and move slider

### Expected result
Joint angle shown in Visualizer changes as Coordinate slider moves.

### Actual result
Model in Visualizer does not move.

### Environment and GUI version
OpenSim-1e476f28-2018-06-13-win64.exe from Dropbox

**Comment by aymanhab** [comment]
Tested in latest build and can't reproduce.

**Comment by carmichaelong** [comment]
Tested on W10 71c8c385, can't reproduce

**Comment by chrisdembia** [comment]
Tested on Mac OpenSim 3d029e5-2018-08-15, can't reproduce.
