### ISSUE TITLE
Coordinate Sliders have no effect when a motion is loaded and time > 0

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#859]
### Steps to reproduce
1. load arm26.osim
2. load arm26_InverseKinematics.mot from OutputReference
3. Move coordinate sliders to pose model
4. Play motion and stop, step forward or or fast forward so time > 0
5. Move coordinate sliders to change pose of the model

### Expected result
3D View updates whenever coordinate sliders are moved.

### Actual result
Although sliders move and coordinate values appear to change the model pose is not updated in the Visualizer.

### Environment and GUI version
Mac and Windows 2018-06-08

**Comment by tkuchida** [comment]
Possibly related to #854

**Comment by jenhicks** [comment]
This appears to be fixed for me on the latest build OpenSim 461c0df-2018-06-22

**Comment by aseth1** [comment]
This appears to be fixed OpenSim_cea85df3-2018-07-18 with IK motion playback and states from forward. Do we agree that muscles should be drawn red with posed? I don't mind, since it reminds the user that it isn't a result of the simulation, but perhaps there is a better way to indicate that while leaving muscle states the same.

In the drop-landing case the model motion became disconnected from the motion playback slider.  That is the motion playback remained grayed out at fixed while the play, rewind and fast forward buttons continued to work. I was not able to reproduce, however.
