### ISSUE TITLE
Hiding muscles leaves orphaned path points still displayed

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#866]
### Steps to reproduce
1. Open a model with muscles.
2. Double-click on muscles to make path points visible
3. Show only a single muscle

### Expected result
Only muscle selected is drawn and all other muscles are hidden.

### Actual result
Muscles are hidden but their path points still appear.
<img width="433" alt="screen shot 2018-06-25 at 4 40 38 pm" src="https://user-images.githubusercontent.com/6494122/41881209-1dc13510-7897-11e8-850b-fabdce1306f0.png">

### Environment and GUI version
Mac OpenSim 461c0df-2018-06-22

**Comment by jenhicks** [comment]
Fixed on OSX

**Comment by aseth1** [comment]
Verified on Windows OpenSim_cea85df3-2018-07-18
