### ISSUE TITLE
Update links to help in the GUI Help Menu and the welcome page

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#867]
In past GUIs, we provided a local copy 
1) user's guide 
2) tutorials
3) doxygen

The links in the menu pointed to the online versions first, and then local if the user isn't online. Given that people are almost always online we could provide perhaps just the tutorials and doxygen as local copies. The way we structure the links, the documentation associated with the release will be saved (i.e., when we release 5.0, the GUI will still link to the 4.0 documentation online).

Let me know your thoughts. @jimmyDunne @aseth1 @aymanhab @chrisdembia

**Comment by chrisdembia** [comment]
We still distribute "user doxygen" with the GUI but I don't know if the GUI has been updated to find the location of this documentation.

**Comment by jenhicks** [comment]
Also need to update link to "Workshops and Events" (name changed) ... alternately I think each confluence page may have an id number that we could link to instead that might be robust to name changes. We also need to make sure that the links to Doxygen, Examples and Tutorials, and Documentation point to "OpenSim40"

**Comment by jenhicks** [comment]
All the links in the help dropdown and welcome page work for me when online.

When offline, the tutorials and doxygen local copies are accessible, as expected. Other links do not work.

**Comment by jenhicks** [comment]
The help buttons in the tools (Scale, etc.) are still pointing to 3.3 versions. 
The help button for plotter, excitation editor, preferences, still points to 3.3

I will open a separate issue.

**Comment by aymanhab** [comment]
Will verify all but the dialog buttons as they're still in PR.

**Comment by aymanhab** [comment]
Installation Guide link on welcome page says only Windows Vista, XP, Windows 7!! I'm not sure we tested XP and Vista  😃

**Comment by chrisdembia** [comment]
> Will verify all but the dialog buttons as they're still in PR.

#902
