### ISSUE TITLE
Saving transformed experimental data erroneously rotates data by 180 degrees

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#894]
### Steps to reproduce
Preview Experimental data , expand node in navigator and choose Transform from context menu

### Expected result
Dialog to allow for transforming the data and saving it.

### Actual result
Exception thrown

(include screen grabs where appropriate)

### Environment and GUI version
4.0 stream

**Comment by jenhicks** [comment]
Please also test whether data is transformed as expected when saved and reloaded

**Comment by aseth1** [comment]
The data appears to be transformed correctly. But when saved and reopened the data is 180degs off.
![image](https://user-images.githubusercontent.com/6494122/43173036-73cb5846-8f67-11e8-8ae8-69c6f61c922d.png)

**Comment by jimmyDunne** [comment]
Dito on Mac.

**Comment by nickbianco** [comment]
I observed the proper transformation behavior via #911.

**Comment by jimmyDunne** [comment]
Transform is correctly saved on Mac 🍾
