### ISSUE TITLE
Deploy CI artifacts for PRs, not just merges into master

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#904]

**Comment by chrisdembia** [comment]
I just learned that, on Travis-CI (and thus Mac), [we are not able to deploy PRs](https://docs.travis-ci.com/user/deployment/#pull-requests). We could deploy for every branch but I think that's not what we'd want (we could end up with subtle differences between the Travis-CI branch builds and AppVeyor PR builds). So for now I think we should limit the scope to just AppVeyor.

**Comment by aymanhab** [comment]
This has been tested by me and works great. I'll move it to verified @chrisdembia unless you think there's some more work to be done. Thank you.
