### ISSUE TITLE
Build in Ubuntu 18.4

### ISSUE THREAD

**Issue by idhamari** [opensim-org/opensim-gui#915]
### Environment and GUI version
Ubuntu 18.4, Netbeans 8.2 openSim 4.0

I was able to build and run openSim Gui in my Ubuntu 18.04 machine. at first there was an error related to JxBrowser. By trying **/tmp/jxbrowser-chromium-55.0.2883.87.6.14.2/jxbrowser-chromium64** there were some errors related to some missing libraries. I copied the libraries in this folder to **/usr/local/lib** and install the missing libraries then   **sudo ldconfig -v**

openSim App works but only inside Netbeans. Tried package as Installer but I get windows exe file. Tried Package as zip but when I run the shel script it opens empty netbeans.

**Comment by tkuchida** [comment]
Thank you for reporting. However, please note the following comment in README.md: "NOTE: Due to the small development team working on the GUI, we do not provide support for building or altering the OpenSim GUI source code. Advanced users can refer to the appveyor.yml or .travis.yml scripts in this folder."

**Comment by idhamari** [comment]
Thanks for replying. I am aware of that. I just put it here as maybe someone has the same problem and solved it as Ubuntu is very popular open-source developers environment.

**Comment by idhamari** [comment]
This issue should be closed now.

**Comment by chrisdembia** [comment]
If there are changes to the repository that you made to facilitate building on Ubuntu, you could share those changes with us (if you're interested).

**Comment by idhamari** [comment]
Thanks for your suggestion, so far the modifications above are the one I did. I am writing and testing a script to do everything (download, install required tools and build opensim-dependencies, opensim-core and opensim-gui). As soon as I finish, I will share it with everyone.
