### ISSUE TITLE
Distributed Models and Geometry Folder are out of sync

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#922]
The last few versions of the application have been distributed with the latest Geometry files but older models. Because the names changed, now you get missing bones. You won't see this if you have older versions of the Geometry on your path. 

![missing_bones](https://user-images.githubusercontent.com/5296507/43461200-e2a215be-94a0-11e8-984e-70520350e184.jpg)

**Comment by jenhicks** [comment]
Thanks for reporting. I put this in the backlog for our current sprint. We can discuss at today's stand-up.

**Comment by aymanhab** [comment]
@jimmyDunne Did you do installResources() This is the only mechanism we use to copy Models from the distribution to the local machine, and it's now off by default (to protect users/testers who install frequently). That may help us find out if the files are out of sync or the installation wasn't invoked.

**Comment by jimmyDunne** [comment]
Thanks, @aymanhab, that seems to have done the trick. Seems like the current models needed to just be re-installed.
