### ISSUE TITLE
Undoing a "Hide" body or group of bodies takes many more clicks than expected

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-gui#924]
### Steps to reproduce
1. Open arm26.osim
2. Hide multiple bodies or a body with multiple objects:
a) Bodies -> Display -> Hide.
b) Bodies, r_humerus -> Display -> Hide.
3. Hit Undo

### Expected result
a) One undo action shows all bodies
b) One undo action shows the humerus and all related wrapping surfaces

### Actual result
Only one object is "undone" at a time.

### Environment and GUI version
W10 a6d9c27-2018-07-27

**Comment by tkuchida** [comment]
Related: #513

**Comment by carmichaelong** [comment]
Whoops, thanks @tkuchida. I think this could be closed since your issue is a better description.

**Comment by jenhicks** [comment]
Closing since this is a duplicate.
