### ISSUE TITLE
Ubuntu build script

### ISSUE THREAD

**Issue by idhamari** [opensim-org/opensim-gui#939]
For a clean Ubuntu 18.04, writing and testing bash script to:

1. Download and Install all required libraries e.g. gcc, java, netbeans, etc.
2. Download opensim-core and opensim-gui 
3. Build opensim-dependencies 
4. Build and install opensim-core
5. Copy required files for opensim-gui 
6. Build opensim-gui

So far, I completed the first 4 parts (still need more testing). It is not clear how to process step 5, what are the sources and destination files for these projects CopyOpenSimCore, CopyVisualizer, CopyModels, CopyJRE,PrepareInstaller? it would be nice if you put the paths here.

**Comment by chrisdembia** [comment]
Refer to the `.travis.yml` script.

**Comment by idhamari** [comment]
If I am java expert I would not ask this question. It is much easier if you put in a simple copy commands. I am not sure why the need for a visual studio or cmake project to do that when simple batch or shell script can do it.  

I found a work around by using the files after the build, the compressed size is around 500 MB. so it is still downloadable.  Testing in progress ...!

**Comment by chrisdembia** [comment]
FYI We are less likely to use a script that does not conform to our current practices, unless there are clear advantages.

**Comment by idhamari** [comment]
Sure! 

This [script](https://github.com/opensim-org/opensim-gui/files/2259383/buildOpenSim.zip) is tested in a new Ubuntu 18.04. I zipped the source-codes and upload it to our server (if there is a branch for a stable source-code, it can be used instead). Feel free to modify the script or re-upload the zipped files based on your need. If there is any legal conflict, please let me know and I will just remove the shared links. 

Next step: if there is no binary packaged already for Ubuntu, I will try to figure out how to make one.

**Comment by chrisdembia** [comment]
Thanks @idhamari! I've downloaded your scripts. We will try to take a look when we get a chance.

**Comment by chrisdembia** [comment]
Keep in mind that we still have no timeline for releasing on Ubuntu.

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab Yes, this is the final place for build instructions. This way we can follow all of the changes in the wiki.
