### ISSUE TITLE
Always installResources() on a fresh install

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#941]

**Comment by aymanhab** [comment]
@chrisdembia Please let me know if you need help working on this one or I can take it over. Thank you

**Comment by aymanhab** [comment]
@chrisdembia I think we will need a build-id and have it accessible from the GUI code so that we can check for a new build and use that to call installResources. This will be very helpful anyway for frequent build/distributions long term maintenance.

**Comment by chrisdembia** [comment]
Should we use a combination of the opensim-gui, opensim-models, and opensim-core commit hashes?

**Comment by aymanhab** [comment]
But opensim-models is a submodule, it needs new commit to make it to opensim-gui
HHashes are good but don't provide order so date followed by gui-commit may be good enough ID

**Comment by chrisdembia** [comment]
Ah good point. However, `opensim-core` is not being used as a submodule (even though it currently exists as a submodule).

I'm fine with adding the date as well.

**Comment by aymanhab** [comment]
I wasn't prompted to install resources on subsequent builds so that part seem to have worked as expected.

**Comment by aymanhab** [comment]
If anybody has cycles to verify this that would be great. @carmichaelong @jimmyDunne @nickbianco Specifically:
- install build from PR
- Verify you get prompted to installResources on first launch and never after
- Report what you see in About dialog for "Product Version"
I got expected results on my windows machine but would like to see what others see as well.

**Comment by chrisdembia** [comment]
I can fix the CI scripts to avoid the version appearing twice.

**Comment by aymanhab** [comment]
Any volunteers to verify on either Mac or Windows @jenhicks @carmichaelong @nickbianco @jimmyDunne

**Comment by jenhicks** [comment]
I tried out on Mac. I think everything worked as expected. See images below.

![installresources](https://user-images.githubusercontent.com/4510959/44550751-fc8ccc80-a6d9-11e8-9eb8-8276220b0608.png)
![about](https://user-images.githubusercontent.com/4510959/44550756-ff87bd00-a6d9-11e8-8fdb-e74dfa3cc45a.jpeg)

**Comment by aymanhab** [comment]
Perfect, thank you @jenhicks

**Comment by chrisdembia** [comment]
Verified on Windows 4.0-2018-08-23-480caf33.
