### ISSUE TITLE
External Loads Pane exception thrown when .xml is version=2

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#949]
This seems to be a problem between GUI and the API in what constructor to call...

If you use the STOFileAdapter() to write forces to a .mot file, the motion file will have version=2. When I try to use the written mot file with version=2 in the GUI (External Loads Panel)I get an exception from Storage(). 

Message window shows 

> Storage: FileAdpater failed to read data file.
> Cannot read headers only if not a STO file or its version is greater than 1.
> 	Thrown at Storage.cpp:206 in Storage().

The section causing the caught exception in storage seems to be [here](https://github.com/opensim-org/opensim-core/blob/dae70d09e419eac1b37d16a193f53b526a513135/OpenSim/Common/Storage.cpp#L201-L224). 

I don't get this issue in Matlab API so I checked the GUI and it seems like the GUI may be [using a constructor](https://github.com/opensim-org/opensim-gui/blob/71c8c385873b86900d6c46aaf8595227a33b4d44/Gui/opensim/tracking/src/org/opensim/tracking/EditExternalLoadsPanel.java#L134) that is tripping the exception.

This may be an API issue, a GUI issue, or both— not sure.

**Comment by chrisdembia** [comment]
@aymanhab what is the reason that the GUI passes `readHeadersOnly=true`?

**Comment by aymanhab** [comment]
@chrisdembia The GUI doesn't actually use anything other than the headers to establish mapping, no need to read/parse a potentially huge file unnecessarily to throw it away.

**Comment by chrisdembia** [comment]
Thanks @aymanhab then we need to chat about how to fix this in opensim-core.

**Comment by chrisdembia** [comment]
@aymanhab have you already started working on this? I could look into it.

**Comment by aymanhab** [comment]
Not yet but I can work on it today. Let me know if there's anything else that came up in scrum that's higher priority

**Comment by chrisdembia** [comment]
Nothing else came up.

**Comment by chrisdembia** [comment]
Okay I will work on other things then.

**Comment by aymanhab** [comment]
How do I get a version 2 .mot file @chrisdembia @jimmyDunne

**Comment by chrisdembia** [comment]
@aymanhab I created the attached file using the `STOFileAdapter`.

[subject01_walk_grf_version2.mot.txt](https://github.com/opensim-org/opensim-gui/files/2329891/subject01_walk_grf_version2.mot.txt)

**Comment by aymanhab** [comment]
Thanks @chrisdembia

**Comment by aymanhab** [comment]
PR https://github.com/opensim-org/opensim-gui/pull/974 does away with using the optimized constructor. Please use the build of this PR @jimmyDunne to check if you get the correct behavior from ID, other tools downstream.

**Comment by aymanhab** [comment]
@jimmyDunne If you can try this branch artifact with actual version 2 file that would be great since I tested with a manufactured file provided by Chris.

**Comment by jenhicks** [comment]
OK to merge the PR and close this issue
