### ISSUE TITLE
Update documentation regarding saving movies

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#957]
https://simtk-confluence.stanford.edu/display/OpenSim/Taking+Snapshots+and+Making+Movies
Refers to camera dolly and AVI format from 3.3

**Comment by jenhicks** [comment]
Issue moved to [opensim-org/opensim-core #2259](https://github.com/opensim-org/opensim-core/issues/2259) via [**ZenHub**](https://www.zenhub.com/)
