### ISSUE TITLE
Reporting scaling marker errors separately for anatomical and tracking markers

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-gui#960]
Michael Asmussen from the visiting scholars group requested a new feature for reporting marker errors after scaling in the GUI. His comment is below.

"I am trying to scale a model of a person cycling.  During the scaling, I am getting RMS errors of about 4 cm. With my study, I first placed EMG on the participants and then adjusted my clusters of markers on the participant's soft tissue based on EMG locations.  This resulted in large differences in marker placements (sometimes 10-20 cm apart).  As a result, during the scaling, the RMS error is inflated based on the marker clusters on soft tissues even though I do not use them for scaling.  I am wondering if there is a way to exclude marker errors from the scaling RMS value that are A) On soft tissues and/or B) Not used for the scaling procedure."

This could also apply to reporting IK marker errors.

**Comment by sebastianskejoe** [comment]
+1

I believe this was also the behaviour in 3.3. If a marker was disabled in Static Pose Weights, it would not by included when calculating the RMS. In 4.0 all markers are included even if they are disabled.
