### ISSUE TITLE
Keyboard shortcut for Save Script is displayed as Ctrl-W but it's actually Cmd-W

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#963]
The GUI says to use Ctrl-W to save a script:

<img width="234" alt="image" src="https://user-images.githubusercontent.com/846001/44231604-8aedd500-a153-11e8-8176-821d9102a809.png">

However, on Mac, I have to use Cmd-W (Ctrl-W deletes the preceding word).

**Comment by aymanhab** [comment]
The issue is that using Cmd-W in configuration files causes it to disappear altogether because it conflicts with another built-in NetBeans command. I can try to look for a different combination (this is not code change, it's a configuration file change)

**Comment by chrisdembia** [comment]
Ah yes usually `Cmd-W` is Close Window.

**Comment by aymanhab** [comment]
Any other shortcuts to try?

**Comment by chrisdembia** [comment]
`Cmd-D`?

**Comment by chrisdembia** [comment]
Here are the existing keyboard shortcuts that the GUI lists:

<img width="740" alt="image" src="https://user-images.githubusercontent.com/846001/44752639-71904580-aad0-11e8-89f1-38ea3980a54f.png">

I don't see `Cmd-D` above.

**Comment by aymanhab** [comment]
Ctrl-D works fine on Windows, will make PR and see if it shows and works on osx.
