### ISSUE TITLE
runTutorialTwo.py causes GUI to crash

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#966]
Related to #736.

@aseth1 or @chrisdembia can read through the script to identify likely causes for the crash.

**Comment by chrisdembia** [comment]
I suspect the issue is `replacePathPoint()`: https://github.com/opensim-org/opensim-gui/blob/be6c2dfbaf114a7edbf1a95d12895c97390a92a7/Gui/opensim/Scripts/runTutorialTwo.py#L57

**Comment by jimmyDunne** [comment]
I did bring this up in meeting— it is almost certainly because the number of points on ECU_post is greater than the number on ECU_pre.

**Comment by jimmyDunne** [comment]
I pushed a (apparent) fix [here](https://github.com/opensim-org/opensim-gui/pull/908/commits/710e2f77bb9c7fcdd3c4b43f5ea6ea94b39f5007).

I tested by running the script 10 times in a row in the GUI (clearing the models and plots in between). I didn't get any crashing. I did this on Mac so perhaps someone can test on Windows?

**Comment by chrisdembia** [comment]
Ah I missed that part of the meeting.

**Comment by jimmyDunne** [comment]
@chrisdembia, it was my bad—Im just sorry that you guys had to waste some time looking for the issue. Hopefully the changes I propose are a decent fix.

**Comment by aymanhab** [comment]
@jimmyDunne @chrisdembia is this issue resolved?

**Comment by chrisdembia** [comment]
I tested locally just now and the issue seems fixed. I was able to run `runTutorialTwo.py` 4 times without the GUI crashing. Closing.
