### ISSUE TITLE
Artifact uploaded from travis build should have standard naming convention

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#972]
### Steps to reproduce
As of now the latest build of master branch creates opensim-latest.pkg making it harder to track actual build if multiple are downloaded.

### Expected result
pkg name is on the form "OpenSim-4.0-2018-x-x-zzzzzz.pkg"

### Actual result
"opensim-latest.pkg"

(include screen grabs where appropriate)

**Comment by chrisdembia** [comment]
@aymanhab I think it's named `OpenSim-master.pkg` (`OpenSim-latest.pkg` is the old name). This is done to avoid using up too much space, and to easily track which build comes from which PR.

If we want to change behavior, it'll be easy to do, but we should then have an automated way of deleting builds from Sourceforge.

**Comment by aymanhab** [comment]
If we had the date as part of the pkg file name then we can either auto or manually remove builds that are a week old for example.
