### ISSUE TITLE
Windows uninstaller leaves behind shortcuts in Start Menu

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-gui#979]
### Steps to reproduce
install any distribution artifact in 4.0, uninstall, directories are removed but shortcuts in startup menu are left behind
### Expected result
shortcuts in startup menu are removed
### Actual result
shortcuts in startup menu are left behind
(include screen grabs where appropriate)

**Comment by aymanhab** [comment]
I fixed this last week in PR #980

**Comment by chrisdembia** [comment]
I just tested locally and indeed the start menu items are gone. However, the desktop shortcut remains.

It would also be nice to give users an option about whether or not to create a desktop shortcut.
