### ISSUE TITLE
Update sections on preparing and previewing data

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#990]
https://simtk-confluence.stanford.edu:8443/display/OpenSim/Preparing+Your+Data This section should be updated and the last couple pages are missing navigation. May want to make a separate issue for this one.

https://simtk-confluence.stanford.edu:8443/display/OpenSim/Previewing+Motion+Capture+%28Mocap%29+Data

**Comment by jimmyDunne** [comment]
Updated Sections and fixe navigation

**Comment by jenhicks** [comment]
Thanks @jimmyDunne  . I reopened so that someone could give the updates a quick review. I can take a look. Unless someone else already did?

**Comment by jenhicks** [comment]
Thanks for working on this James. Here is some feedback:

- Update overview page to clarify compatibility with C3D.
- Update "Next" link on the overview page (should point to "Collecting Experimental Data"
- Maybe call the page "C3D Files" to better match naming of other pages in this section.
- Move C3D page to follow .sto page in the tree
- Would it be possible to make the page a little bit more accessible to users who aren't as familiar with the API, but are fairly comfortable with Matlab scripting? (e.g., many people won't know what forked means".) You also mention TimeSeriesTable, which people will not be familiar with. 
- Can you add some text at the beginning of the page describing how C3D reading fits in with the pipelines people have used in the past? How does it relate to other file types? 
- Can you add text to introduce what each of the pieces of example code is doing?

**Comment by jimmyDunne** [comment]
Thanks, @jenhicks. I have made edits form your suggestions. Let me know if there is anything else I can add/change. 

https://simtk-confluence.stanford.edu/display/OpenSim/Preparing+Your+Data

**Comment by jenhicks** [comment]
Thanks @jimmyDunne . These updates look good. Moving to verified ...
